### ISSUE TITLE
rsync failed to exec sshpass

### ISSUE THREAD

**Issue by yumyo** [welaika/wordmove#10]
I'm getting the following error after a word move push:
`rsync: Failed to exec sshpass: No such file or directory (2)
rsync error: error in IPC code (code 14) at /SourceCache/rsync/rsync-42/rsync/pipe.c(86) [sender=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [sender=2.6.9]
Error executing "rsync -azLK -e 'sshpass -p [...] ssh' --exclude-from`

I have my local SSH public key already installed on the remote machine. So what's wrong?

**Comment by jontrujillo** [comment]
I know this issue is closed but i ran into an issue with this and i found that i needed to install sshpass this link was helpful. https://gist.github.com/arunoda/7790979

**Comment by pioneerskies** [comment]
Thanks for commenting, but please, keep this in mind: https://github.com/welaika/photocopier#password-gotchas

Cheers
