### ISSUE TITLE
db pull issue

### ISSUE THREAD

**Issue by joeguilmette** [welaika/wordmove#100]
I had a mountain of issues to work around, and I finally got through them all and wordmove is now pushing and and pulling just fine.

```
▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=127.0.0.1 --user=user --password=pswd project_db > /vagrant/www/project/wp-core/wp-content/local-backup-1412909727.sql
   remote | mysqldump --host=localhost --user=remote_user '--password=remote_pswd' remote_db > /remote/path/to/dump.sql
   remote | get: /remote/path/to/dump.sql /vagrant/www/project/wp-core/wp-content/dump.sql
   remote | delete: /remote/path/to/dump.sql
    local | adapt dump
    local | mysql --host=127.0.0.1 --user=user --password=pswd --database=project_db < /vagrant/www/project/wp-core/wp-content/dump.sql
    local | rm /vagrant/www/project/wp-core/wp-content/dump.sql
```

Looks good, but when I reload project.dev/, the db changes are nowhere to be found. Everything else pulls just fine.

Here are the server entries for my local wp_config.php - it's pointing to the same db right?

```
// ** MySQL settings ** //
/** The name of the database for WordPress */
define('DB_NAME', 'project_db');

/** MySQL database username */
define('DB_USER', 'user');

/** MySQL database password */
define('DB_PASSWORD', 'pswd');

/** MySQL hostname */
define('DB_HOST', 'localhost');
```

I am using VVV, and running wordmove through `$ vagrant ssh`. Perhaps the issue is with Nginx?

**Comment by onlyskyguy** [comment]
I'm running a [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) setup too and having a similar issue with pull. The database dump downloads fine but nothing happens after that, and nothing gets updated on the local site. Am I missing something?

I'm running the following command from vagrant ssh (vagrant@vvv:/srv/www/MYSITE):

```
$ wordmove pull -d -v
```

This is the output:

```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=wp --password=wp MYSITE --result-file=/srv/www/MYSITE/htdocs/wp-content/local-backup-1447257718.sql
    local | mysqldump --host=localhost --user=wp --password=wp MYSITE --result-file=/srv/www/MYSITE/htdocs/wp-content/local-backup-1447257718.sql
   remote | write /remote/path//MYSITE/wp-content/dump.php
    local | download http://remotesite.com/MYSITE/wp-content/dump.php?shared_key=6bb8741cbc3b664ff3a7b3710099092c40fd15997cbdc082fe35c2d14a5352cf2fb035b9a649696e > /srv/www/MYSITE/htdocs/wp-content/dump.sql
   remote | delete: /remote/path/MYSITE/wp-content/dump.php
    local | adapt dump
mysql --host=localhost --user=wp --password=wp --database=project-db --execute=SOURCE\ /srv/www/MYSITE/htdocs/wp-content/dump.sql
    local | mysql --host=localhost --user=wp --password=wp --database=project-db --execute=SOURCE\ /srv/www/MYSITE/htdocs/wp-content/dump.sql
    local | rm /srv/www/MYSITE/htdocs/wp-content/dump.sql

```
It doesn't seem like anything is happening with the remote dump once it makes it to my local environment, although the remote-backup-#.sql files are created in the local wp-content directory.

> Hey, if they are equal after a successful pull than is possible that they were really equal :)

I am in the process of testing this all, so I specifically made a change to the remote site and a different change to the local site to see what would happen during the pull. But so far nothing happens at all.

Would appreciate any help or insight into what I may be missing. Thanks!
