### ISSUE TITLE
mkdir: Access failed: 550 Can't create directory: File exists (/public_html/)

### ISSUE THREAD

**Issue by Mte90** [welaika/wordmove#103]
Why i get this with a `wordmove pull -w`?

```
mkdir: Access failed: 550 Can't create directory: File exists (/public_html/)
```

**Comment by LudovicFauchet** [comment]
Hello,

I open again the ticket, i tried to do a `wordmove pull -w` but it doesn't work, if i have understood it's a problem with lftp, but how to correct that problem ?

The terminal respond is 
`mkdir: Access failed: 550 Can't create directory: File exists (/agencedelest/)`

Thanks a lot

**Comment by pioneerskies** [comment]
Hi @LudovicFauchet and thanks for enquiry.

Could you tell us what is the consequence of that message? The transfer stops? Is it incomplete? What else?

Thanks in advance for the clues :)

**Comment by LudovicFauchet** [comment]
Hi @pioneerskies ,

Yes the transfer stop and thats all... :'(

Cheers

**Comment by pennantcreative** [comment]
I am experiencing the same issue. My transfer also gets hung up after the error. Was there a fix for this?

**Comment by rotexhawk** [comment]
Same here. I get the error message. I tried deleting the folder to see if it will create it but didn't seem to fix the issue. For me the process continues but nothing gets uploaded. 

It will be great to get a solution for this.  

"WordMove" is awesome. Great job guys...

**Comment by pioneerskies** [comment]
```bash
✔ ~/dev/xxxxx [2.2.0]  (git: master △ )
↳ $ gem list | grep wordmove
wordmove (1.2.0)

✔ ~/dev/xxxxx [2.2.0]  (git: master △ )
↳ $ lftp --version
LFTP | Version 4.6.1 | Copyright (c) 1996-2014 Alexander V. Lukyanov
```

Testing the same `pull` as the reported one:

```bash
▬▬ ✓ Pulling wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /htdocs /Users/fuzzy/dev/xxxx .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-05-18T11:06:25.115120 #2174]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://xxxx:yyyy@zzzz.it; mkdir -p /htdocs; cd /htdocs; lcd /Users/fuzzy/dev/xxxx; mirror --delete --use-cache --verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --exclude-glob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*.sql --exclude-glob wp-content/*'
mkdir: Access failed: 550 /htdocs: File exists
Removing old file `.DS_Store'
Removing old file `.htaccess'
Removing old file `Wordfile'
Removing old file `google8837655dda00198d.html'
Removing old file `index.php'
Removing old file `robots.txt'
Removing old file `wp-activate.php'
Removing old directory `wp-admin'
[...cutting the rest of the list...]
```

You can see in the produced command

    mkdir -p /htdocs; cd /htdocs;

and the consequent response

    mkdir: Access failed: 550 /htdocs: File exists

Re-launched the same command; the expectation is a 0 file transfer, because already up-to-date with the remote env

```bash
✔ ~/dev/larc [2.2.0]  (git: master △ )
↳ $ wordmove pull -w -e production

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /htdocs /Users/fuzzy/dev/xxxx .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-05-18T11:13:07.240212 #2740]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://xxxx:yyyy@zzzz.it; mkdir -p /htdocs; cd /htdocs; lcd /Users/fuzzy/dev/xxxx; mirror --delete --use-cache --verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --exclude-glob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*.sql --exclude-glob wp-content/*'
mkdir: Access failed: 550 /htdocs: File exists
```

The 550 "error" is always there and any file transferred; as expected. As far as I can reproduce, if nothing gets transferred, there's nothing to be transferred.

Another note: pay attention when the FTP connection hangs; Wordmove can't manage connection problems, FTP problem in any way; but assure yourself to be using the right FTP connection type between _passive_ and _active_. I've worked with a lot of bad FTP servers, too slow or w/ unstable connections but ... FTP sucks and it really is not an opinion :stuck_out_tongue: 

Last note: working via FTP should be mandatory to set both relative and absolute path as per README:

```markdown
In order for wordmove to work with FTP, you need to install lftp on your machine. Then in the remote host section in your Movefile:

Use the relative FTP path as wordpress_path
Use the absolute FTP path as wordpress_absolute_path (you may need to recover this from the __FILE__ constant)
```

At least I hope this could help someone... :\
