### ISSUE TITLE
Add in the readme Wordmove-Tools

### ISSUE THREAD

**Issue by Mte90** [welaika/wordmove#104]
I've created many scripts for auto detection of settings for the Movefile and that genberate the wp-config.php with the data of movefile.

The repo: https://github.com/Mte90/Wordmove-tools

is possible add this script in the readme?

**Comment by pioneerskies** [comment]
We're really really sorry about having never replied...

In the meantime we have decided that those type of contributions have to be placed in the project's wiki. It is open. Just create a new page and edit as desired.

Cheers

**Comment by Mte90** [comment]
Perfect :-)
