### ISSUE TITLE
Simple permissions question

### ISSUE THREAD

**Issue by joeguilmette** [welaika/wordmove#106]
First off- I love this tool. You guys rock, and have been very kind to me in the past when posting ridiculous questions. Feel free to link me to google. Anyway. I'm using *VVV locally* and *EasyEngine in production*. 

The issue I'm having is in production, /var/www is owned by www-data:www-data, which is set to `www-data:x:33:33:www-data:/var/www:/sbin/nologin` in /etc/passwd, as (I've read) it should be.

So, this leaves me in a tough spot with Wordmove. In my local Movefile I can set Wordmove to ssh via the normal non-root user I ssh in with via public_key. But I get permission errors spit back at me after running `wordmove push` because my user doesn't have write access to /var/www.

I can have Wordmove use root, but that is bad, and anyway it mucks up the permissions on the moved files. The best way I can find to do it is to temporarily set www-data to `www-data:x:33:33:www-data:/var/www:/bin/bash` and then Wordmove goes along swimmingly, at which point I then have to revert /etc/passwd back to /sbin/nologin, and then chmod files to 644 and folders to 755 because this method borks those.

It works, but you guys are all smart and maybe have a better way?

**Comment by delphaber** [comment]
@joeguilmette any news? :)

**Comment by joeguilmette** [comment]
Kinda - I've made some progress but been pretty busy! When I finally get this sorted I'll add a wiki for using Wordmove with EasyEngine, which is what I'm trying to do here.

What do you guys do for this? How do you deal with permissions/ownership on remote?

**Comment by delphaber** [comment]
@joeguilmette can you try with the prelease version of `wordmove` (#174) and those rsync options @pioneerskies told you?

**Comment by delphaber** [comment]
Hi @joeguilmette can we close this?

**Comment by joeguilmette** [comment]
Yes! All works wonderfully, thanks guys.
