### ISSUE TITLE
Prevent database push

### ISSUE THREAD

**Issue by Boztown** [welaika/wordmove#113]
Is there any option in the Movefile or a simple hack I could introduce to basically disable the "push" command for the database?  I love being able to pull the database and pushing it up is handy initially but could be really dangerous for my team at a certain point.

**Comment by pioneerskies** [comment]
I'll close this due to inactivity, but always ready to see a PR happen :)

**Comment by essenmitsosse** [comment]
I would still find this feature super handy. Would be great if someone could implement it.
