### ISSUE TITLE
Error on illegal byte sequence

### ISSUE THREAD

**Issue by miya0001** [welaika/wordmove#114]
I got an error on `wordmove pull --all` and `wordmove pull --db`.

```
.rvm/gems/ruby-2.1-head/gems/wordmove-1.2.0/lib/wordmove/sql_adapter.rb:44:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)
```

And I found a solution like following so sql dump file sometimes contain illegal byte sequence.

https://github.com/miya0001/wordmove/compare/fix-when-illegal-byte-sequence-found

This problem happen only `wordmove pull` and it doesn't happen on `wordmove push`.

I can't found cause about why dump file contain illegal byte sequence.
How do you think about?

**Comment by delphaber** [comment]
Closing: Please read this https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db
