### ISSUE TITLE
Cannot install Wordmove on OS X Yosemite 10.10.1

### ISSUE THREAD

**Issue by rcorbari** [welaika/wordmove#115]
Hello,

I tried to follow a guide to install Wordmove from my OS X Terminal, but it cannot be installed. Is there any step-by-step guide on how to do it?

Thanks to all who will answer.

**Comment by nonchiedercilaparola** [comment]
i think that i have MRI ruby interpreter second this guide: https://www.ruby-lang.org/it/downloads/

**Comment by pioneerskies** [comment]
I thought you were using rubinius due to your rbenv path: `/Users/nonchiedercilaparola/.rbenv/versions/rbx-2.2.10/gems/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:2`. Rbx stands for rubinius AFAIK.

This has not to be a problem, but we have never tested our code against that interpreter.

**Comment by pioneerskies** [comment]
@nonchiedercilaparola news? :)

**Comment by nonchiedercilaparola** [comment]
nothing i have to fix the homebrew error and than fix the rbenv error. i think i have installed too many things:(

**Comment by pioneerskies** [comment]
Ok... I wish you better luck.
I'll close this ticket; feel free to request to reopen it.

Cheers!

**Comment by nonchiedercilaparola** [comment]
i'm a stupid...i used rbenv to install ruby because i wanted use multiple version of ruby. I simply have to install "mri version" and use this to install wordmove. i'll try.

**Comment by pioneerskies** [comment]
I'm glad you have a path to follow.
Let we know about your success if you'll have the time ;)
