### ISSUE TITLE
Duplicating WordPress core in languages folder

### ISSUE THREAD

**Issue by tikot** [welaika/wordmove#118]
A weird bug. 

If I don't have a languages folder in contents folder and will run `wordmove push --all` it will make a `languages` directory and upload the WordPress core into languages folder. 

the config `Movefile` : nothing is special only different is I used ftp this time.

```
✓ Pushing Languages 
/projects/test/wp-content/languages: No such file or directory
Transferring file `index.php'
Transferring file `license.txt'
Transferring file `readme.html'
Transferring file `wp-activate.php'
Making directory `wp-admin'
Making directory `wp-includes'
...
```

**Comment by defaria** [comment]
I have the same exactly same issue. I get a language folder inside wp_content with the entire wp core again.

**Comment by pioneerskies** [comment]
@tikot @defaria thanks for opening the issue and for the feedback.

The remaining operations will work as expected?
Have your tried creating the `languages` folder?

**Comment by delphaber** [comment]
This is fixed in the new prelease version.

If you want to test, `gem uninstall wordmove && gem install wordmove --pre`.

*Please* backup local/remote files/db if you want to try the prerelease (beta) version
