### ISSUE TITLE
Various characters in ftp password

### ISSUE THREAD

**Issue by dmassiani** [welaika/wordmove#119]
My password is like this : "Md5-e];97" and wordmove doesn't accept ";" 
He try to connect from 97@ftp.com 
I tried "Md5-e]\;97" but doesn't work

**Comment by delphaber** [comment]
Could be a problem with `photocopier` gem. Have you tried to URL encode your password?

`Md5-e];97` becomes `Md5-e%5D%3B97` for example. Let us now!

**Comment by delphaber** [comment]
We fixed this in `https://github.com/welaika/photocopier`

We are going to release a new version in the very next weeks

**Comment by dmassiani** [comment]
Ok, Thank you !
