### ISSUE TITLE
Git support

### ISSUE THREAD

**Issue by esaheiskanen** [welaika/wordmove#121]
It would be nice to have git and git sub repository support.

Thanx for great work.

**Comment by pioneerskies** [comment]
Hi @esaheiskanen :)

Thanks for your suggestions; could I ask you to elaborate a bit on it? How do you think Wordmove should support GIT? Could you try to describe an example workflow?

Thanks for your patience and thought

**Comment by pioneerskies** [comment]
I'll close due to the loss of iteration on the subject. Please feel free to reopen and reply when you'll have time :)
