### ISSUE TITLE
nodename nor servname provided, or not known when pushing folder

### ISSUE THREAD

**Issue by sayedwp** [welaika/wordmove#123]
After reading a lot about wordmove, thought to include this in my workflow but after trying the whole day could not get any success which is certainly because of my ignorance.  I am trying to use FTP to push and pull files and I did the following.

1) Installed wordmove. 
2) Installed rudix and then lftp.
3) cd /Applications/MAMP/htdocs/naija/wp-content/themes/naija 
4) wordmove init (which created the Movefile )
5) Entered the server information which looks like below

<pre>
local:
  vhost: "http://localhost:8888"
  wordpress_path: "/Applications/MAMP/htdocs/naija/" # use an absolute path here

  database:
    name: "naija"
    user: "root"
    password: "root"
    host: "127.0.0.1"

staging:
  vhost: "Enteredhold"
  wordpress_path: "/public_html/naija/wp-content/themes/naija" # use an absolute path here

  database:
    name: "entereddbname"
    user: "entereduser"
    password: "enteredpass"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  paths:
    wp_content: "wp-content"
    uploads: "wp-content/uploads"
    plugins: "wp-content/plugins"
    themes: "wp-content/themes/naija"
    languages: "wp-content/languages"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
    user: "entereduser"
    password: "enteredpass"
    host: "host"
    passive: true

# production: # multiple environments can be specified
#   [...]

</pre>

Now I get this error when trying to push a theme folder. Cannot figure out why it is not connected and where I need to enter more information.

![screentshot](https://cloud.githubusercontent.com/assets/6297436/5933814/be3119f6-a6eb-11e4-88bb-a8b34a4c033e.png)

**Comment by pioneerskies** [comment]
Hi! :)

I think you've a problem here:

```
ftp:
    user: "entereduser"
    password: "enteredpass"
    host: "host"
    passive: true
```

moreover in your `host` setting. Simply `lftp` can't connect to the host you told him; probably you have maintained the default "host" setting as far as I can see in your screenshot: `ftp://xxxxxxx:xxxxxx@host`

Let we know if it helped

Cheers

**Comment by sayedwp** [comment]
Wow this is super awesome and super fast. Have been looking for something like this for years. And yes the problem was in the ftp details, fixed now. Just one more thing, how do I push or pull a single file, is there any place where I can see the list of all commands?

**Comment by pioneerskies** [comment]
I'm really happy it was helpful and you enjoy Wormove :))))

Try `wordmove push help` to get a list of all possible actions it can accomplish.

Push a single file is not possible, but:

1. only modified files will be transfered (permission, time, contents, etc.)
2. you can exlcude files within the, you betcha, `exclude` section in the `Movefile`

I'll close the issue. Feel free to reopen if you'll need.

Cheers

**Comment by sayedwp** [comment]
Thanks a lot, that was very helpful.
