### ISSUE TITLE
Help with pull --all

### ISSUE THREAD

**Issue by realves** [welaika/wordmove#125]
Hi guy! I have installed wordmove and configurated my Movefile. When I pull from my site, no data was tranfered from online wordpress site. wordmove pull only db dump, and create the wordpress dir structure... how can i fix?
This is my Movefile:
local: 
  vhost: "localhost"
  wordpress_path: "E:\\Vincenzo\\www\\wordmove\\iw\\htdocs\\" # use an absolute path here

  database:
    name: "iw" # Nome del Database
    user: "vincenzo.casu" # Utente MySQL
    password: "mypass" # Password MySQL
    host: "localhost" # URL host MySQL

staging:
  vhost: "http://www.informaticaworld.it/"
  wordpress_path: "/htdocs/" # use an absolute path here

  database:
    name: "informat" # Nome del Database
    user: "informat" # Utente MySQL
    password: "mypass" # Password MySQL
    host: "sql.informaticaworld.it" # URL host MySQL
    
  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    
  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  ftp:
    user: "informaticaworld.it"
    password: "mypass"
    host: "ftp.informaticaworld.it"
    passive: true

And this is the wordmove command call:

C:\wamp\www\wordmove\iw>wordmove pull --all
DL is deprecated, please use Fiddle

▬▬ V Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ V Pulling wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /htdocs/ E:\Vincenzo\www\wordmove\iw\htdocs\ .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-co
ntent/*
I, [2015-02-21T23:22:19.031082 #33120]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://informaticaworld.it:mypass@ftp.informaticaworld.it; mkd
ir -p /htdocs/; cd /htdocs/; lcd E:\Vincenzo\www\wordmove\iw\htdocs\; mirror --delete --use-cache --verbose --allow-chown --allow-suid --no-umask --pa
rallel=2 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --exclude-glob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* -
-exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*'

▬▬ V Pulling Uploads ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /htdocs/wp-content/uploads E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/uploads .git/ .gitignore .sass-cache/ bin/ tmp/* G
emfile* Movefile wp-config.php wp-content/*
I, [2015-02-21T23:22:19.043097 #33120]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://informaticaworld.it:mypass@ftp.informaticaworld.it; mkd
ir -p /htdocs/wp-content/uploads; cd /htdocs/wp-content/uploads; lcd E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/uploads; mirror --delete --use-cach
e --verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --exclude-gl
ob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*'

▬▬ V Pulling Themes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /htdocs/wp-content/themes E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/themes .git/ .gitignore .sass-cache/ bin/ tmp/* Gem
file* Movefile wp-config.php wp-content/*
I, [2015-02-21T23:22:19.055085 #33120]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://informaticaworld.it:mypass@ftp.informaticaworld.it; mkd
ir -p /htdocs/wp-content/themes; cd /htdocs/wp-content/themes; lcd E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/themes; mirror --delete --use-cache -
-verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --exclude-glob
bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*'

▬▬ V Pulling Plugins ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /htdocs/wp-content/plugins E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/plugins .git/ .gitignore .sass-cache/ bin/ tmp/* G
emfile* Movefile wp-config.php wp-content/*
I, [2015-02-21T23:22:19.055085 #33120]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://informaticaworld.it:mypass@ftp.informaticaworld.it; mkd
ir -p /htdocs/wp-content/plugins; cd /htdocs/wp-content/plugins; lcd E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/plugins; mirror --delete --use-cach
e --verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --exclude-gl
ob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*'

▬▬ V Pulling Languages ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /htdocs/wp-content/languages E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/languages .git/ .gitignore .sass-cache/ bin/ tmp
/* Gemfile* Movefile wp-config.php wp-content/*
I, [2015-02-21T23:22:19.067086 #33120]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://informaticaworld.it:mypass@ftp.informaticaworld.it; mkd
ir -p /htdocs/wp-content/languages; cd /htdocs/wp-content/languages; lcd E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/languages; mirror --delete --us
e-cache --verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --excl
ude-glob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*'

▬▬ V Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=vincenzo.casu --password=mypass iw > E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/local-backup-142455
7339.sql
Warning: Using a password on the command line interface can be insecure.
   remote | write /htdocs/wp-content/dump.php
    local | download http://www.informaticaworld.it/wp-content/dump.php?shared_key=cf8f2cc0b887b9d83e4db7f8e83f9c7ed4e974d9a6f5969135b03dd4ca7a30bf78e
f7765c89f05a8 > E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/dump.sql
   remote | delete: /htdocs/wp-content/dump.php
    local | adapt dump
    local | mysql --host=localhost --user=vincenzo.casu --password=mypass --database=iw < E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/dump.sql
Warning: Using a password on the command line interface can be insecure.
    local | rm E:\Vincenzo\www\wordmove\iw\htdocs\wp-content/dump.sql

C:\wamp\www\wordmove\iw>

**Comment by realves** [comment]
The www dir in wamp is located on a second partition. I create a link from C:\wamp\www to E:\Vincenzo\www. I don't that can be a problem... right?

**Comment by pioneerskies** [comment]
To replay to your second question: I don't think it should be a problem.

Stranger is the path on your ftp server: @/htdocs/@. I think a good try could be to follow [these instructions](https://github.com/welaika/wordmove#ftp-support) and use both the parameters inside the @Movefile@.

Unfortunately working w/ ftp is actually a little pain...

Looking forward to hear some news from you :)

Cheers

**Comment by pioneerskies** [comment]
Hey @realves have you managed to put it at work?

**Comment by delphaber** [comment]
I'm closing this: no feedback.
