### ISSUE TITLE
Nothing happend when wordmove pull or push

### ISSUE THREAD

**Issue by Antoinebr** [welaika/wordmove#127]
Hi i'm trying to use the script but for now that's a total failure.

Im on on MacBook Pro late 2012 10.9.5 and i use MAMP 3.05

I create a Movefile with wordmove init

This is my Movefile (i replaced all sensitive datas)
This seems valid on Yam validator

local:
  vhost: "http://localhost:8888/ltts/wordpress/"
  wordpress_path: "/Users/Antoine/Google - Drive/localhost/ltts/wordpress" # use an absolute path here

  database:
    name: "ltts-wordpress"
    user: "root"
    password: "root"
    host: "localhost"

staging:
  vhost: "http://antoine-host.com/preprod/ltts/"
  wordpress_path: "/home/antoine/www/preprod/ltts" # use an absolute path here

  database:
    name: "ltts-wordpress"
    user: "root"
    password: "dnsddsds"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
    user: "antoine"
    password: "Aedeze"
    host: "antoine-host.com"
    passive: true

# production: # multiple environments can be specified
#   [...]

but when i do wordmove push

Nothing happen only : 
![nothing](https://cloud.githubusercontent.com/assets/8248256/6412703/9e365ea0-be87-11e4-8eff-8d608d5b42d4.png)

Please help :) I really want to use that tools

**Comment by mariojankovic** [comment]
I think you will want to use wordmove push --all.

**Comment by pioneerskies** [comment]
@Antoinebr any news from your side?

**Comment by delphaber** [comment]
Should we consider to warn user when he/she runs wordmove `push` or `pull` withouth any options?

**Comment by pioneerskies** [comment]
@Antoinebr @mariojankovic now we warn users when no true actions are passed as flag to wordmove.

Closing. Cheers :)

**Comment by romanrandom** [comment]
I didn't get a warning when using it without flags.

**Comment by pioneerskies** [comment]
@romanrandom I think you're using 1.3.1. The fix will be in the next major release and is in current pre-release version.

**Comment by romanrandom** [comment]
OK, I thought you were talking about the released version.
