### ISSUE TITLE
warnings with ruby 2.2.0

### ISSUE THREAD

**Issue by mukkoo** [welaika/wordmove#129]
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::BASE
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_ALL
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_NaN
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_INFINITY
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_UNDERFLOW
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_OVERFLOW
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_ZERODIVIDE
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_MODE
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_UP
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_DOWN
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_UP
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_DOWN
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_CEILING
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_FLOOR
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_EVEN
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NaN
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_ZERO
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_ZERO
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_FINITE
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_FINITE
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_INFINITE
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_INFINITE
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::INFINITY
~/.rvm/gems/ruby-2.2.0@wordless/gems/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::NAN

**Comment by delphaber** [comment]
Cannot reproduce with ruby 2.2.1

**Comment by charmcat** [comment]
I'm having the same issue above.

**Comment by aks** [comment]
I have the same bug (with BigDecimal 1.2.7)

**Comment by Chrisedmo** [comment]
Why is this closed? I'm also getting a similar issue when trying any command.

    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::BASE
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_ALL
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_NaN
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_INFINITY
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_UNDERFLOW
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_OVERFLOW
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_ZERODIVIDE
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_MODE
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_UP
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_DOWN
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_UP
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_DOWN
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_CEILING
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_FLOOR
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_EVEN
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NaN
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_ZERO
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_ZERO
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_FINITE
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_FINITE
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_INFINITE
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_INFINITE
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::INFINITY
    /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/bigdecimal-1.2.5/bigdecimal.bundle: warning: already initialized constant BigDecimal::NAN

**Comment by pioneerskies** [comment]
Ok guys, we could think to reopen and debug a little more around this, but we need some help; can you all reproducing the bug report:

* operative system
* ruby version
* wordmove version
* is ruby system installed or managed with version managers? If the latter are you using rbenv or RVM?

Thanks for helping us troubleshooting this

**Comment by pioneerskies** [comment]
@Chrisedmo could you try with ruby version at least 2.2.1?

**Comment by Chrisedmo** [comment]
hi @pioneerskies I tried switching to 2.2.2 with rvm and got different errors. So I reverted back to my regular ruby. I'll have another try. I really want to integrate wordmove into our workflow!

**Comment by pioneerskies** [comment]
Thanks for the effort. In the meantime I'll re-open the issue to try to do a second round of testing.

**Comment by charmcat** [comment]
OSX 10.10.3 Yosemite
Ruby: 2.2.2p95—installed using rbenv
Wordmove version: 1.2.0

have vagrant in the directory; not sure if that's relevant.

**Comment by delphaber** [comment]
@charmcat could you please run `gem list | grep bigdecimal``

I noticed the problem is between bigdecimal 1.2.7 and active_support

**Comment by charmcat** [comment]
````
bigdecimal (1.2.7, 1.2.6)
````

**Comment by delphaber** [comment]
`bigdecimal` is a default ruby gem. Maybe the problem is having two versions of it. If you do not need `bigdecimal`1.2.7 you could try to `gem uninstall bigdecimal`. It should remove 1.2.7 and leave 1.2.6 (which cannot be uninstalled)

Let us known :)

**Comment by charmcat** [comment]
Uninstalled and now the error is gone whenever I run the command.

Thanks!

**Comment by pioneerskies** [comment]
:8ball:

**Comment by ecurtis** [comment]
I just installed wordmove for the first time and got this error. This is what I have in the gem list:
bigdecimal (1.2.7, 1.2.6)

**Comment by pioneerskies** [comment]
@ecurtis haven't you tried to follow this advise https://github.com/welaika/wordmove/issues/129#issuecomment-121772089 ?

**Comment by ecurtis** [comment]
Thank you for the response, I did follow those directions and it did work. I wanted to let you know though that it was still an issue, and other packages are still installing a newer version of Big Decimal. Since this seemed like a workaround and not a fix I wanted to share my experience. Cheers.
