### ISSUE TITLE
wordmove pull -d fails

### ISSUE THREAD

**Issue by robertjw1** [welaika/wordmove#131]
I'm able to pull all the files from my server to my local dev environment, but the database pull fails.

wordmove pull -v -d

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=username--password=password usernamewp> /var/www/andrewhall/wp/wp-content/local-backup-1426197351.sql
   remote | mysqldump --host=localhost --user=username '--password=paswordremote' username_wp > /home/username/public_html/wp-content/dump.sql
/var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:50:in `rescue in block (2 levels) in negotiate!': connection closed by remote host (Net::SSH::Disconnect)
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:46:in `block (2 levels) in negotiate!'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:45:in `loop'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:45:in `block in negotiate!'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:43:in `loop'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:43:in `negotiate!'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:32:in `initialize'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/session.rb:85:in `new'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/session.rb:85:in `block in initialize'
        from /usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /usr/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/session.rb:85:in `initialize'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh.rb:207:in `new'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh.rb:207:in `start'
        from /var/lib/gems/2.1.0/gems/photocopier-0.0.10/lib/photocopier/ssh.rb:52:in `session'
        from /var/lib/gems/2.1.0/gems/photocopier-0.0.10/lib/photocopier/ssh.rb:60:in `exec!'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:54:in `remote_run'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:62:in `download_remote_db'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:34:in `pull_db'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:47:in `block in pull'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:46:in `pull'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
        from /usr/local/bin/wordmove:23:in `load'
        from /usr/local/bin/wordmove:23:in `<main>'

**Comment by pioneerskies** [comment]
Hi @robertjw1 ,

why have you closed the ticket? Was the problem already solved?

**Comment by robertjw1** [comment]
When I first pasted this I had some login information I didn't want in there.  I tried to edit it and accidently managed to make a duplicate, so I closed this one.  I apologize if that wasn't the right thing to do.

**Comment by sandrowuermli** [comment]
If anybody had a `connection closed by remote host` error, try to set a port in your `ssh` configuration in your `Movefile.yml`:

```
  ssh:
    host: "sl123.web.yourhoster.ch"
    user: "someusername"
    port: 22
```

my hoster want to set a strict port for ssh and this solved my problem.

**Comment by pioneerskies** [comment]
Thanks for reporting this @sandrowuermli ;)
