### ISSUE TITLE
wordmove pull -d fails

### ISSUE THREAD

**Issue by robertjw1** [welaika/wordmove#132]
I'm able to pull all the files from my server to my local dev environment, but the database pull fails.

```
wordmove pull -v -d

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=username --password=localpass usernamewp > /var/www/username/wp-content/local-backup-1426197351.sql
   remote | mysqldump --host=localhost --user=username' --password=password username_wp > /home/username/public_html/wp-content/dump.sql
/var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:50:in `rescue in block (2 levels) in negotiate!': connection closed by remote host (Net::SSH::Disconnect)
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:46:in `block (2 levels) in negotiate!'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:45:in `loop'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:45:in `block in negotiate!'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:43:in `loop'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:43:in `negotiate!'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/server_version.rb:32:in `initialize'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/session.rb:85:in `new'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/session.rb:85:in `block in initialize'
        from /usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /usr/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/transport/session.rb:85:in `initialize'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh.rb:207:in `new'
        from /var/lib/gems/2.1.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh.rb:207:in `start'
        from /var/lib/gems/2.1.0/gems/photocopier-0.0.10/lib/photocopier/ssh.rb:52:in `session'
        from /var/lib/gems/2.1.0/gems/photocopier-0.0.10/lib/photocopier/ssh.rb:60:in `exec!'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:54:in `remote_run'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:62:in `download_remote_db'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:34:in `pull_db'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:47:in `block in pull'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:46:in `pull'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/2.1.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
        from /usr/local/bin/wordmove:23:in `load'
        from /usr/local/bin/wordmove:23:in `<main>'
```

**Comment by pioneerskies** [comment]
Hi @robertjw1 ,

if you try to run this command (w/ your correct credentials), what does it return?

```
ssh user@example.com "mysql --user=dbuser --host=localhost --password=p4ssw0rd -e 'show databases;'"
```

**Comment by robertjw1** [comment]
Hi @pioneerskies!

Here is what I get

```
ssh foo@domainname.com "mysql --user=username --host=localhost --password=password -e 'show databases;'"
stdin: is not a tty
Database
information_schema
username_wp
```

For some reason my server drops the connections with this message
`ssh_exchange_identification: Connection closed by remote host`

I have to run that command about 3 times to get it to work, looks like that was my initial problem and probably something to do with the server.

Looks like I'm now having the same problem as in #78   

```
/var/lib/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/sql_adapter.rb:44:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)
```

Tried the fix there and it doesn't seem to work (If I did it right, I don't know much about ruby)

**Comment by paperrobots** [comment]
I'm also having the same issues as #78. I don't really know how to change the ruby file, pretty new at this. 

I changed all my tables to UTF-8 but still getting the error. 

    /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/sql_adapter.rb:44:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/sql_adapter.rb:44:in `serialized_replace!'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/sql_adapter.rb:36:in `replace_field!'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/sql_adapter.rb:25:in `replace_vhost!'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/sql_adapter.rb:17:in `adapt!'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:182:in `adapt_sql'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:21:in `push_db'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

**Comment by delphaber** [comment]
Hi @paperrobots. Changing default encoding for a table does not change encoding for single column. Could you please check if is there any column with charset != utf8?

Anyway, we think we should not force you all to convert your database. We are trying to fix this in 1.3 branch by setting the right encoding (chosen by you) in all the process

**Comment by paperrobots** [comment]
I found an article saying that Wordfence conflicts with Wordmove. Sure enough I uninstalled it and all the Wordfence tables from my database and it worked fine.

**Comment by pioneerskies** [comment]
Sorry to be silly, @paperrobots , but what Wordfence is? If there are some incompatibilities it should be a good choice to open an advertising in the wiki... :\

**Comment by silvioheinze** [comment]
Wordfence is a plugin (https://wordpress.org/plugins/wordfence/) which seems to be the problem. Had the same issue with it. After dropping the wordfence tables in the database everything is fine again.

**Comment by pioneerskies** [comment]
@silvioheinze your feedback is really appreciated.

I quote what @delphaber wrote in [previous comment](https://github.com/welaika/wordmove/issues/132#issuecomment-104562034). The encoding problem goes easily on steroids if plugins add mysql tables w/ different encoding. We noticed even some translated wordpress sources install tables w/ encoding other than UTF-8. The hell...

I'm going at least to open a little note in the wiki about problems w/ Wordfence...

**Comment by defaria** [comment]
Just wanted to add to this and say that I had the same issue once I installed wordfence.

**Comment by pioneerskies** [comment]
@defaria are you able to check what encoding have the plugin's tables and their column? With a query like

```sql
SELECT DISTINCT character_set_name, table_name, column_name FROM information_schema.`COLUMNS` WHERE `table_schema` = 'your_db_name' ORDER BY character_set_name;
```

[Here](http://stackoverflow.com/questions/1049728/how-do-i-see-what-character-set-a-database-table-column-is-in-mysql) are more SQL commands

**Comment by kathlynn** [comment]
Wordfence is using latin1_swedish_ci

**Comment by delphaber** [comment]
Please, read this wiki page https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db for more information.

Can you use UTF-8 for wordfence `varchar`/`text` columns?

**Comment by delphaber** [comment]
Closing this. Please read the wiki and reopen if necessary

**Comment by sandrowuermli** [comment]
If anybody had a `connection closed by remote host` error, try to set a port in your `ssh` configuration in your `Movefile.yml`:

```
  ssh:
    host: "sl123.web.yourhoster.ch"
    user: "someusername"
    port: 22
```

my hoster want to set a strict port for ssh and this solved my problem.
