### ISSUE TITLE
553 error Ftppermerror

### ISSUE THREAD

**Issue by Kinsi** [welaika/wordmove#134]
Hello. 
I don't make your gem work. 
I'm on windows (no rsync) and with a mutualised server (OVH => SSH hard to have)... what can i do ? Or what am i doing wrong...

I have this time always this kind of error: 

(pushing database part):

remote write /essai/wp-content/dump.php
c:/ruby21-x64/lib/ruby/2.1.0/net/ftp.rb:327:in 'getresp' : 553 can't opent that file: No such file or directory (Net::FTPPermError)

Can you help me please?

**Comment by delphaber** [comment]
Hi.

Wordmove has not been tested on windows and probably never will because we use *nix systems in our daily workflow.

Anyway, your error is a FTP error. Google says:

The 553 error code is coming directly from the remote FTP server.  The file name is not allowed.

Many FTP servers have restrictions on file names.  If your file name contains special characters, symbols, or spaces in the file name, it might be rejected by the remote FTP server.  In the example above, the file name was rejected because of a space.  The remote FTP site may also be rejecting a particular file based on the file type or extension.

I hope this could help :)

**Comment by Kinsi** [comment]
Thx!

**Comment by delphaber** [comment]
Can we close this issue then? ;)

**Comment by rotexhawk** [comment]
I am getting the same error on my mac. I am trying to push the database.

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write cyberser/public_html/test/wp-content/dump.php
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:326:in `getresp': 553 Can't open that file: No such file or directory (Net::FTPPermError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:351:in `block in sendcmd'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:349:in `sendcmd'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:428:in `transfercmd'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:543:in `block (2 levels) in storbinary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:199:in `with_binary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:542:in `block in storbinary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:541:in `storbinary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:690:in `putbinaryfile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:718:in `put'
	from /Library/Ruby/Gems/2.0.0/gems/photocopier-0.0.10/lib/photocopier/ftp.rb:21:in `put_file'
	from /Library/Ruby/Gems/2.0.0/gems/photocopier-0.0.10/lib/photocopier/adapter.rb:18:in `put'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:74:in `remote_put'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:103:in `download_remote_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:23:in `push_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

**Comment by pioneerskies** [comment]
@rotexhawk we assume the path `cyberser/public_html/test/wp-content/` doesn't exists.
Please ensure you correctly setup relative and absolute path in `Movefile`
