### ISSUE TITLE
wordmove push/pull error with mysql.sock

### ISSUE THREAD

**Issue by dsmy** [welaika/wordmove#141]
I get the following error whenever trying to do a push or pull. mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect (RuntimeError)

Any ideas?

**Comment by delphaber** [comment]
Did you try to define `host: 127.0.0.1` for loca database configuration in Movefile?

**Comment by dsmy** [comment]
Yes I did.

**Comment by pioneerskies** [comment]
@dsmy are you still interested in a troubleshooting? Eventually could you write down some details? OS, mysql version, how was mysql installed, try to launch the wormove's mysql command (it is on the stdout output) in a terminal, etc. etc.

Cheers

**Comment by dsmy** [comment]
@pioneerskies Sure, currently on Yosemite, don't quite how mysql was installed, but when I was trying out wordmove I was trying to use the mysql in Mamp. 

This was the command used for wordmove during my tests (wordmove pull -d -e staging). Let me know if there is anything else I can provide on the issue.

**Comment by pioneerskies** [comment]
I'll try...

In OSX the socket isn't in the usual unix path AFAIK. In my case, with MySQL server running, I have the socket in `/tmp/mysql.sock` let's check if this path is right for you.
If it is you'd have to find you `my.cnf` file, find this snippet

```
# These are commonly set, remove the # and set as required.
# basedir = .....
# datadir = .....
# port = .....
# server_id = .....
# socket = .....
```

and edit as following

```
# These are commonly set, remove the # and set as required.
# basedir = .....
# datadir = .....
# port = .....
# server_id = .....
socket = /tmp/mysql.sock
```

Let us know

**Comment by pioneerskies** [comment]
And just to be clearer: this happens because mysqldump try to connect to the unix socket, not to the port on the TCP socket
