### ISSUE TITLE
"Cannot load such file --dl/import (LoadError)"

### ISSUE THREAD

**Issue by rush4ratio** [welaika/wordmove#144]
Great Job!
Unfortunately, using Windows 8.1, with the pull command and I get this error. I'm using this version of rsync: https://www.itefix.net/content/cwrsync-free-edition
![capture](https://cloud.githubusercontent.com/assets/7237203/7215422/ccd38e2a-e5df-11e4-9fb9-b82d3582f2e9.JPG)

**Comment by stuzzo** [comment]
Hi @rush4ratio, have you tried this http://stackoverflow.com/questions/28896733/rhc-setup-gives-error-no-such-file-dl-import ?

**Comment by delphaber** [comment]
Hi @rush4ratio we are sorry but we do not support Windows platform. Did @stuzzo comment help you?

**Comment by bwaaaaaa** [comment]
try this>  gem install net-ssh -v 2.9.3.beta1

**Comment by pioneerskies** [comment]
Il close this due to inactivity. Thanks @bwaaaaaa for the suggestion :)

**Comment by stuarteske** [comment]
Worked on Windows, thanks.
