### ISSUE TITLE
RSpec deprecation warnings

### ISSUE THREAD

**Issue by spanndemic** [welaika/wordmove#149]
I'm just getting back into Wordpress, and love this tool you have created!

Minor issue, but when running both sql_adapater_spec.rb and base_spec.rb, there are deprecation warnings for the following commands: 'should', 'should_receive', and 'stub', which are deprecated as of RSpec 3.

I have a Pull Request in updating these scripts to the new syntax:
https://github.com/welaika/wordmove/pull/147

Thanks!

**Comment by delphaber** [comment]
Merged, thank you :)
