### ISSUE TITLE
Database push issue

### ISSUE THREAD

**Issue by jackmost** [welaika/wordmove#151]
```unix
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /public_html/wp-content/dump.php
    local | download http://website.com/wp-content/dump.php?shared_key=87f449a50b7a0b2607a968f1be23a0103dd79d8211048eea75ebc718ef1fd4224134d2b025072855 > /local_website_folder/wp-content/remote-backup-1429929723.sql
   remote | delete: /public_html/wp-content/dump.php
    local | mysqldump --host=localhost --user=user --password=pass dbtest > /local_website_folder/wp-content/dump.sql
    local | adapt dump
   remote | copying /local_website_folder/wp-content/dump.sql to /public_html/wp-content/dump.sql
   remote | write /public_html/wp-content/import.php
    local | download http://website.com/wp-content/import.php?shared_key=aff5fa10331a24488b0d79c435f74c3903c057972f7b417d7e6a4e7a33b5ac68a3e0fefae7840637&start=1&foffset=0&totalqueries=0&fn=dump.sql > /local_website_folder/wp-content/temp.txt
    local | rm /local_website_folder/wp-content/temp.txt
   remote | delete: /public_html/wp-content/import.php
   remote | delete: /public_html/wp-content/dump.sql
    local | rm /local_website_folder/wp-content/dump.sql
```

**This is the output, no errors, everything seems fine but database is still empty. ???**

**Comment by pioneerskies** [comment]
Hi!

If you invoke `mysqldump --host=localhost --user=user --password=pass dbtest`in your terminal you'll see your local DB content on STDOUT; what's in there? Can you see database contents or just the structure?

**Comment by jackmost** [comment]
Hi,
Thanks for your help.
I see all the contents.
I checked the dump.sql file that is created by wordmove push, and all is there, import.php seems ok, too. But it looks like import is not being executed.

**Comment by jackmost** [comment]
Problem solved.
It was MySQL version compatibility issue. Specifically tables collation.

**Comment by pioneerskies** [comment]
We've tried to write something about error reporting, but grab mysql errors when working via FTP would be a really big effort (probably extending the third party php library we use there) due to software design.

Thanks for sharing your troubleshooting w/ the rest of us! :+1:

**Comment by esad** [comment]
I also got bitten by this today. The issue is that wordmove says nothing even if import.php fails. As we already download the output of running import.php, we could do perhaps some basic error checking?
