### ISSUE TITLE
Add mysqldump options to Movefile? 

### ISSUE THREAD

**Issue by pjackson1972** [welaika/wordmove#152]
I'm new to WordMove, and hoping you can point me in the right direction.

I'm getting the following when dumping the remote database: Error 2020: Got packet bigger than 'max_allowed_packet' bytes

I have a case where my staging database includes records that exceed the default max_allowed_packet size.  Because of the host permissions, I can't edit the .ini file, and normally get around this by adding the mysqldump option --max_allowed_packet=1G.

Can I add an argument to my Movefile to add this option, or is there another workaround?

Thanks!

**Comment by delphaber** [comment]
Hi @pjackson1972 at the moment you cannot pass additional options to mysqldump. Anyway it sounds like a good idea; pull request is welcome :)

**Comment by delphaber** [comment]
Done. Please check the `README` of dev branch: https://github.com/welaika/wordmove/tree/dev to know how to configure your `Movefile`.

Install the latest wordmove prerelease version with `gem install wordmove --pre`

Please, since this is a pre release version, take extra caution.

Let us known!

**Comment by mukkoo** [comment]
@pjackson1972 it seems to work. I'll close this issue. Reopen it if you need.
