### ISSUE TITLE
Local path name with spaces causes mysqldump errors

### ISSUE THREAD

**Issue by WinkingFrog** [welaika/wordmove#155]
I've nearly got things up and running but I am having a problem with mysqldump and my local path structure...

My local dev setup is in a folder structure where I have spaces in the name of my folders. When I try and run a wordmove command I get errors relating to the incorrect parsing of the path, namely a mysqldump: Couldn't find table: "folder" - where folder would be the word after the first space in the path.

I understand why this is happening, but with the path being passed to mysqldump by wordmove I don't know how to escape things correctly so it reads the whole path including the spaces!?

Any pointers?

(I'm on OSX running in a MAMP environment, trying to connect to MediaTemple grid)

**Comment by jirsbek** [comment]
Exactly the same problem here. I also have spaces in my local wordpress path.

I've tried "local/path/with\ space" but not success.

Is there any other way how to escape space character in terminal?

**Comment by pioneerskies** [comment]
having spaces in paths on a Unix based OS is a really bad behaviour, IMHO.

Anyway I think wordmove should be able to do some level of escaping. We'll try to check something around it

**Comment by delphaber** [comment]
this will be fixed in the new version :)

**Comment by pioneerskies** [comment]
@WinkingFrog @jirsbek 
version 1.3.0 is now shipped as stable. Please, `gem install wordmove` and enjoy :)
