### ISSUE TITLE
adapt dump

### ISSUE THREAD

**Issue by alexisleblanc** [welaika/wordmove#158]
Hi !
No sure where my problem come from. Everything was working perfectly last week and now, it seems that when I push my DB, wordmove doesn't replace the url.
When I look at my wp_options in phpmyadmin, the siteurl and sitehome entered by wordmove avec my localhost adresse. If I change them manually to the right one via phpmyadmin and then push my DB again, it change back to localhost.
Other than that, all the other information seems to change.

Is there a way I could test if the adapt dump is working correctly ?

Thanks

**Comment by jontrujillo** [comment]
I've been having this issue too. Did you happen to figure it out?

**Comment by alexisleblanc** [comment]
Haven't been trying to fix it yet. I just bypassed it by defining the wordpress URL and HOME in my config file on my server so Even if the Database option are set to the localhost, I still can export my wordpress online and everything work.

**Comment by pioneerskies** [comment]
@jontrujillo are you also experiencing the problem only within the last week?
@alexisleblanc have you upgraded anything? Any gem? MAMP, MySql, you know what?

Cheers

**Comment by alexisleblanc** [comment]
I haven't updated anything like gem, Mamp, mysql or things like that.
I'm using a DigitalOcean server that I manage with serverpilot. Previously, I was using my server ip adresse to access my website but I changed it to use a domain name instead. This is the only change I've made.
I updated my Movefile so that my staging vhost use the new domain name.

This morning I pulled all my wordpress from my server to my local and then pushed back my local to server and It seems that the push was succesful and that the database have been correctly modified.

I'm not sure if its the pull that changed something or if it magicly worked, I'll try to make some other test to see what happen.

**Comment by pioneerskies** [comment]
Ok; update here when you'll have more results from tests.

Looking forward to read your news

**Comment by alexisleblanc** [comment]
Ok,
So I initialized a new project and the problem is there. When I push and visit my domain, the page cannot be loaded becaus it look for url.com:8888 and when I try to access the Wordpress admin, with wp-admin or wp-login.php, I get redirected to my localhost.
I really have no clue of what is happenning .....

**Comment by pioneerskies** [comment]
Is it a MultiSite enabled installation?

**Comment by alexisleblanc** [comment]
No, its a very simple straight foward installation made with wp-cli

**Comment by jontrujillo** [comment]
It was probably just an issue with my Movefile, I was able to get it working when i deleted it and re-initialized the file and reconfigured the settings.

**Comment by pioneerskies** [comment]
I've just re-red the whole discussion....but...I can't manage to get a clue on the problem. I'm so sorry, but still having few input to perform a sort of troubleshot :(

**Comment by alexisleblanc** [comment]
Unfortunatly, I had to switch on other projects so I can't help you with more information. I'll keep you inform as soon as I have so use wordmove again.
As I asked, is there a way to verify the work that the adapt dump do to the database ?

Thanks for the feedback !

**Comment by defaria** [comment]
I am using wordmove for the first time on a test wp setup. I am having the same issue. If I try to access the remote site, I get a 500 error. When I try to access the admin I get redirected to localhost. I checked the database and the options table has the localhost url.

When I run wordmove push -d I get the following:

▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /public_html/wp-content/dump.php
    local | download http://nsm.mysite.com/wp-content/dump.php?shared_key=241363cb4d439106e396d110e9f4af68f4fd85c0074f0b8713718b7ab9aaf71c7133c978b79c9b52 > /Users/developer/Sites/nsm/wp-content/remote-backup-1433437061.sql
   remote | delete: /public_html/wp-content/dump.php
    local | mysqldump --host=localhost --user=root --password=root nsm > /Users/developer/Sites/nsm/wp-content/dump.sql
    local | adapt dump
   remote | copying /Users/developer/Sites/nsm/wp-content/dump.sql to /public_html/wp-content/dump.sql
   remote | write /public_html/wp-content/import.php
    local | download http://nsm.mysite.com/wp-content/import.php?shared_key=f02271e7029610ac658dfcc9d0a9b6cd5761810af81e1e2606089b6bbf93fef9ec42430218c7148b&start=1&foffset=0&totalqueries=0&fn=dump.sql > /Users/developer/Sites/nsm/wp-content/temp.txt
    local | rm /Users/developer/Sites/nsm/wp-content/temp.txt
   remote | delete: /public_html/wp-content/import.php
   remote | delete: /public_html/wp-content/dump.sql
    local | rm /Users/developer/Sites/nsm/wp-content/dump.sql

Everything else works perfectly. What information do you need to debug it?

**Comment by defaria** [comment]
I had a ending "/" in my local url. Once I removed the "/" the urls updated correctly.

**Comment by pioneerskies** [comment]
great @defaria , thanks for the follow up

**Comment by felixfischer** [comment]
I had the same problem. It was caused by a wrong local vhost value in the Movefile. Make sure that it matches the WordPress adress as defined on the General Settings page.

**Comment by pioneerskies** [comment]
Could be a good idea to add a line of documentation in the readme or inline in the `Movefile`'s skeleton.

I'd like also to recommend the use of wp-cli, when available, to have a quick look at the siteurl in the db:

```bash
↳ $ wp option get siteurl
```

**Comment by Jeger** [comment]
I ran into the same problem, and it is hard to debug as the push / pull seems to go without a problem.
Would it be possible to throw an error if the url is not found? That would make it obvious where the fault is.

**Comment by alexisleblanc** [comment]
I was able to correct the problem by making a new movefile. I dont know why but my old movefile seemed to be wrong ... even if the new one look exactly the same, by making a new wordmove init, the problem was fixed.

**Comment by pioneerskies** [comment]
Labeling as a documentation improvement.

@Jeger generally I'm totally with you; specifically managing errors when using FTP protocol is a nice PITA :P

Anyway we're are stashing some similar requests, so it makes everyday more desirable get working in this direction.

Please, remember that PR are always welcome in order to keep up improving Wordmove!
