### ISSUE TITLE
Parse Error? How to set up Wordmove properley on a mac with vagrant. 

### ISSUE THREAD

**Issue by webbrouwer** [welaika/wordmove#159]
Hey!

Working on the setup for wordmove. Set it up with VVV tips from the wiki. The following comes up when given the `wordmove push --all`:

```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find expected '-' indicator while parsing a block collection at line 23 column 5 (Psych::SyntaxError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:245:in `load'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:58:in `fetch_movefile'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:20:in `deployer_for'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'
```

Hope you can help me out, really would like to get this thing going!

Have a good one.

Mickey

**Comment by joeguilmette** [comment]
Here you go! https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-(or-any-Vagrant)

Let me know if you have any questions

**Comment by webbrouwer** [comment]
Hey, thank you for the response. I've set it up by following the steps from the wiki. Unfortunately the error shown in the previous comment has shown up. 

From this point I go blank. 

Also tried to install in trough rvm, but the same error came up. Did I install it in the wrong location?

**Comment by pioneerskies** [comment]
I think this a problem w/ the `Movefile` YAML. Could you share it w/ us (thrown out sensible data)?

**Comment by webbrouwer** [comment]
Hi pioneerskies,

It was indeed the `Movefile`. Also I had to update rsync, after this it worked! Awesome feeling after days of trying!

Thank you for creating wordmove

**Comment by nailbrain** [comment]
I am having the exact same problem with the same error. How did you resolve it beyond running the update. My rsync is up to date.

I don't have vagrant or anything installed so I am just running wordpress on my local machine with MAMP.

I generate my movefile with wordmove init.

Here is my movefile:

`local:
  vhost: "http://vhost.local"
  wordpress_path: "/Users/brettgolding/Dropbox/htdocs/thelanguagepeople" # use an absolute path here

  database:
    name: "mydomain"
    user: "root"
    password: "root"
    host: "localhost"

staging:
  vhost: "http://www.mydomain.co.uk/thelanguagepeople"
  wordpress_path: "/home/155271/domains/mydomain.co.uk/html/thelanguagepeople/" # use an absolute path here

  database:
    name: "db155271_lang"
    user: "db155271_brett"
    password: "my_password"
    host: "s155271.gridserver.com" # Using media temple for a web host with SSH enabled
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  # ssh:
     host: "websouthend.co.uk"
     user: "websouthend.co.uk"
     password: "my_ftp_password" # password is optional, will use public keys if available.
     port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true

# production: # multiple environments can be specified
#   [...]`

**Comment by palicko** [comment]
@nailbrain you have to uncomment #ssh and check your text intending

**Comment by nailbrain** [comment]
@palicko ssh is not commented out and text indenting hasn't changed.

Sorry could you check out my other post if you have time? https://github.com/welaika/wordmove/issues/162

**Comment by pioneerskies** [comment]
@nailbrain, plz, you should post your `Movefile` as code here in the issue

```
just like this
```

or we won't be able to check the syntax: YAML is indentation sensitive language.

Moreover in this snippet

    # ssh:
    host: "websouthend.co.uk"
    user: "websouthend.co.uk"
    password: "my_ftp_password" # password is optional, will use public keys if available.
    port: 22 # Port is optional

the key `ssh` does not seem to be uncommented. Keep in mind that each indented word followed by a semicolon in YAML will be an array key in the reading language, so it's very important to respect the `Movefile`'s syntax and indentation.

Looking forward to read something back :)

**Comment by jmsilcom** [comment]
hi there. 
Can u tell me more about "gateway" under SSH part of Movefile?
Does it means we can add a SSH gateway for connecting Database ?
Thanks in advance.

**Comment by pioneerskies** [comment]
Hi @jmsilcom ,

I'd be glad to help but have to ask you to elaborate a bit your question (don't know what the "gateway under SSH" is) and to open a new topic in the effort of keep the issue tracker tidy.

Thanks in advance.

In the meantime I'll close this inactive issue; people involved have to feel free to reopen at their will.

Cheers
