### ISSUE TITLE
Avoid setting permissions 

### ISSUE THREAD

**Issue by silentlight** [welaika/wordmove#161]
Hi there!

I am trying to move my Wordpress theme to a staging server (using SSH), but I do not want to set permissions on moved files. How can I achieve this? I don't think that there is a way to pass -p option to rsync. 

Many thanks in advance.

**Comment by paperrobots** [comment]
I'm having a permissions issue as well. It pushes the files to the staging server fine, but all my permissions break.

**Comment by pioneerskies** [comment]
Said that permissions are a server-side system administration problem, I'm glad to remember that you can pass `-p` option to rsync through `Wordmove`

    #   rsync_options: "--verbose" # Additional rsync options, optional

check it out on the example file in the README, under the `Movefile`'s ssh section.

Hope it helps! ;)

**Comment by yuranikolaev** [comment]
Hi! 
Get the same thing.
Just pass the argument --chmod=ugo=rwX in Wordmove file

From rsync docs: 

>To give destination files (both old and new) the source permissions, use --perms. To give new files the destination-default permissions (while leaving existing files unchanged), make sure that the --perms option is off and use --chmod=ugo=rwX (which ensures that all non-masked bits get enabled).

**Comment by pioneerskies** [comment]
Tnx @yuranikolaev for pointing that out

**Comment by sulram** [comment]
hi all! @pioneerskies @yuranikolaev 

I had to add `--chmod=ugo=rwX` in the following line?

```
rsync_options: "--verbose --chmod=ugo=rwX" # Additional rsync options, optional
```

I'm having problem, but only with images. They are not getting the correct chmod after `wordmove push -t` command, and I have to access server via ssh and execute command:

```
find path/to/dir/ -type f -exec chmod 664 {} + -o -type d -exec chmod 775 {} +
```

**Comment by pioneerskies** [comment]
@sulram actually in order to pass multiple rsync options at once you should try the pre-release version

    gem uninstall wordmove && gem install wordmove --pre

or you should try to pass just the second option. Keep in mind that in order to use --chmod you should have right privileges on the remote machine (e.g.: the folder should be owned by your user)

**Comment by sulram** [comment]
thanks @pioneerskies, it worked! ;)

**Comment by pioneerskies** [comment]
:+1:
