### ISSUE TITLE
How to i move from staging to production env?

### ISSUE THREAD

**Issue by frangelli** [welaika/wordmove#164]
I saw that inside the Movefile we can define multiple environments. But i couldn't figure out how to move from staging to production.

Can anybody tell me if is it possible?

**Comment by frangelli** [comment]
Sorry, my bad! Just got how to do!

**Comment by pioneerskies** [comment]
Plz, @frangelli , if you feel something smtng's not user friendly in the readme, feel free to send us a pull request w/ improvements :)

Glad to see you're enjoying Wordmove.

Cheers
