### ISSUE TITLE
Disable database backup

### ISSUE THREAD

**Issue by jirsbek** [welaika/wordmove#165]
Hello!

First of all let me thank you for great tool.

I would like to know if there is any way how to disable database backups? I already backup database different ways so after every push/pull I have to delete exports.

**Comment by pioneerskies** [comment]
Hi @jirsbek 
We're happy you enjoy Wordmove :+1: 

Actually the tool can't disable db backups (but we are working on gzip-ing them). If I were in your shoes I'd write a small wrapper script such as

```bash
#!/bin/bash

wordmove push -t -e staging
find ./wp-content -name "*.sql" -exec rm -f {} +
```

I'm declining all sort of responsibility on the `rm -f` command :P ;)

Cheers
