### ISSUE TITLE
Help with db push (Error 1273 - collation related)

### ISSUE THREAD

**Issue by ckboyle** [welaika/wordmove#166]
Forgive me if I'm repeating someone else's issue.  I tried to find anything that matched up with my problem, but no luck.

I'm able to push all of my site files via rsync with no problem, but when I get to the database portion of the push, Wordmove returns an error:

```bash
   remote | mysqldump --host=mysql.digistory.boyleagio.com --user=****** --password=****** digistory_boyleagio_com > /home/ckboyle/digistory.boyleagio.com/wp-content/dump.sql
   remote | get: /home/ckboyle/digistory.boyleagio.com/wp-content/dump.sql /vagrant/www/digistory/htdocs/wp-content/staging-backup-1433947443.sql
   remote | delete: /home/ckboyle/digistory.boyleagio.com/wp-content/dump.sql
    local | mysqldump --host=localhost --user=****** --password=****** digistory > /vagrant/www/digistory/htdocs/wp-content/dump.sql
    local | adapt dump
   remote | put: /vagrant/www/digistory/htdocs/wp-content/dump.sql /home/ckboyle/digistory.boyleagio.com/wp-content/dump.sql
   remote | mysql --host=mysql.digistory.boyleagio.com --user=****** --password=****** --database=digistory_boyleagio_com < /home/ckboyle/digistory.boyleagio.com/wp-content/dump.sql
/usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:55:in `remote_run': Error code 1 returned by command "mysql --host=mysql.digistory.boyleagio.com --user=****** --password=****** --database=digistory_boyleagio_com < /home/ckboyle/digistory.boyleagio.com/wp-content/dump.sql": ERROR 1273 (HY000) at line 25: Unknown collation: 'utf8mb4_unicode_ci' (RuntimeError)
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:71:in `import_remote_dump'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:22:in `push_db'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'
```

(Usernames and passwords removed, of course.)

Doing some searching on "Error 1273" lets me know this is related to the database collation, but I'm not sure how to fix this.  I admit I'm still dipping my toes into the command line/vagrant/deployment pool, so if this is some dumb setting I need to fix, then I'm sorry for any trouble.

Thanks so much!

**Comment by pioneerskies** [comment]
Hi @ckboyle ,

this is not a dumb issue at all from my point of view; this is an issue with the encoding and that's on the bigger pain in development podium.

Actually `Wordmove` expects, as it should, databases and their tables to be UTF-8 encoded; in the real world we found that there is a list of cases where it is not as expected. We are trying to keep some work time to implement a db encoding choice through the Movefile. Anyway if you'll have multiple encodings spread within multiple tables...well...it will be always a problem.

My first recommendation  is to use always UTF-8 (I'm aware some WP translations ships altered encoding as well...the world is a terrible place); secondly I could point you to an help topic on how to change collation: http://stackoverflow.com/questions/1294117/how-to-change-collation-of-database-table-column.

Hope it was somewhat clarifying ...

**Comment by ckboyle** [comment]
Yes, thanks!  It turned out to be a combination of vvv using normal modern encoding formats and my hosting company still using a version of MySQL from 2011 that didn't support any of them.  An email to DreamHost and a day later and I'm now on their newer server which offers a much newer version of MySQL and the problems are gone.

**Comment by pioneerskies** [comment]
Really really cool!
Glad to hear that.

Cheers!

**Comment by paperrobots** [comment]
Is there any reason this happens when I setup wordpress? Is there a way to prevent this so I don't have to modify my tables every time I setup a new site?

**Comment by pioneerskies** [comment]
If it happens when you setup WP, probably is related to UTF8MB4 encoding which - I'm doing the shaman here - could be supported on your local MySQL but not on the remote...(?)

Another reason could be that you're using a translated version; I noticed encoding misbehaviour on some languages other than english; please, test using the default language first of all.
