### ISSUE TITLE
syntax error on line 40, col 3: ` ssh: '

### ISSUE THREAD

**Issue by dandycat** [welaika/wordmove#167]
So I am getting some kind of syntax error right above the ssh: line... any thoughts? I # out the passwords and such so disregard those as I have those filled out on my file.

local:
  vhost: "http://localhost/dandycatdesigns"
  wordpress_path: "C:/wamp/www/dandycatdesigns" # use an absolute path here

  database:
    name: "dandycatdesigns"
    user: "dandycat"
    password: "secretpassword"
    host: "localhost"

staging:
  vhost: "#"
  wordpress_path: "#" # use an absolute path here

  database:
    name: "dandycatdesigns_staging"
    user: "#"
    password: "#"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

   ssh:
     host: "45.55.155.156"
     user: "serverpilot"
     password: "#" # password is optional, will use public keys if available.
     port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "serverpilot"
  #   password: "DFriskyDingo870s123"
  #   host: "host"
  #   passive: true

# production: # multiple environments can be specified
#   [...]

**Comment by dandycat** [comment]
Duh! So I had an additional space in front of the SSH. So there ya go people haha

**Comment by pioneerskies** [comment]
Cool you've done it already ;)
Cheers
