### ISSUE TITLE
DL is deprecated please use Fiddle 

### ISSUE THREAD

**Issue by dandycat** [welaika/wordmove#168]
So I am using Windows 8.1 (unfortunately) and I installed Ruby for Windows 2.1.something. When I got the wordmove init file finally setup correct I tried to simulate a push and then it tells me "DL is deprecated, please use fiddle"

I go and look this problem up and people were saying to change the rbreadline file and I did that but it did nothing. Still got the same error. So then I thought I'd be clever and get an older version of Ruby so it wouldn't give me that error. 

Well now that version is too old for wordmove lol. So what am I supposed to do? Anyone know how I can use fiddle or get around this? Saving up for a Mac starts now! I can't stand how many f** work arounds there are for winblows.

**Comment by dandycat** [comment]
Fixed it... I ended up upgrading to 2.0.0 then followed this

 DL is deprecated, please use Fiddle ' is actually a warning. The warning message comes out when you require 'irb' ( because irb require 'readline' ) or anything else wants to require 'readline'. If you feel it's annoying, you can comment out it at C:\Ruby200\lib\ruby\2.0.0\dl.rb.

**Comment by pioneerskies** [comment]
Woooo...so you have Wordmove up and running on a Windows box?
It'd be beautiful to know how you done the setup! :D
