### ISSUE TITLE
push -d Issue

### ISSUE THREAD

**Issue by jmsilcom** [welaika/wordmove#171]
Hi, can you help me to understand these error messages ?

```bash
mysqldump --host=178.32.218.50 --port=3306 --user=XXX --password=XXXXX XXXX > /var/www/clients/client2/web37/web/wp-content/dump.sql
/Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:55:in `remote_run': Error code 2 returned by command "mysqldump --host=178.32.218.50 --port=3306 --user=XXX --password=XXXX XXXX > /var/www/clients/client2/web37/web/wp-content/dump.sql": mysqldump: Got error: 2003: Can't connect to MySQL server on '178.32.218.50' (111) when trying to connect (RuntimeError)
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:62:in `download_remote_db'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:18:in `push_db'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/bin/wordmove:23:in `load'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/bin/wordmove:23:in `<main>'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jeanmichelsilone/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

XXXX not real name, of course !

Thanks

**Comment by pioneerskies** [comment]
Hello @jmsilcom ! :)

I think your MySQL server is not on 178.32.218.50 or the port is not the default one (3306).

You can customize both oarams within the Movefile. Moreover they usually should match the WordPress' connections params inside wp-config.php file.

Keep in mind you can debug the command invoked by Wordmove connecting via SSH to your server and launching the very same command by hand:

    mysqldump --host=178.32.218.50 --port=3306 --user=XXX --password=XXXX dbname > /var/www/clients/client2/web37/web/wp-content/dump.sql

Lines from 3rd until last are a stack trace caused by the error itself and you can safely ignore them in this situation.

Good luck and give us news!

**Comment by jmsilcom** [comment]
Hi @pioneerskies, thaks for quick answer, i've made some changes in credential. Now, i've no connect error but... a "command not found", the local dump is empty and not sent to server...
See below : 
`remote | mysqldump --host=178.32.218.50 --port=3306 --user=c2savoirfaire '--password=9XNXR5tg!Ggho' c2savoirfaire > /var/www/clients/client2/web37/web/wp-content/dump.sql
   remote | get: /var/www/clients/client2/web37/web/wp-content/dump.sql /Users/jeanmichelsilone/Sites/vagrant-local/www/savoirfaire-gironde/htdocs/wp-content/staging-backup-1434728110.sql
   remote | delete: /var/www/clients/client2/web37/web/wp-content/dump.sql
    local | mysqldump --host=localhost --user=XXXXX --password=XXXXX savoirfaire-gironde > /Users/jeanmichelsilone/Sites/vagrant-local/www/savoirfaire-gironde/htdocs/wp-content/dump.sql
sh: mysqldump: command not found`

(I'm under vagrant on MacOS)
Thanks for help !

**Comment by jmsilcom** [comment]
Hi,

the answer was in this forum. I had to install wordmove inside the vagrant machine. It work's fine now.
(only a small issue with SSH password: no blocking.
Thank's a lot.

**Comment by pioneerskies** [comment]
Very well done!

Just as a reference for future readers:

[here is a related issue](https://github.com/welaika/wordmove/issues/110) and here is a [related wiki entry](https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-(or-any-Vagrant))

@jmsilcom as a general advice prefere pubkey ssh authentication over every time typing your password ;)

Cheers
