### ISSUE TITLE
rsync command not found

### ISSUE THREAD

**Issue by webbrouwer** [welaika/wordmove#172]
Hey!

I've installed all the necessary software to make WordMove work. Infact I had it working a couple weeks ago on other server. But now I encounter on the following error:
`▬▬ ✓ Pushing Themes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Users/Mac/Sites/projecten/katewood/wp-content/themes /home/webbrouw/public_html/projecten/katewood/wp-content/themes .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql .htaccess .DS_Store
I, [2015-06-24T12:38:20.422335 #27332]  INFO -- : rsync --progress -e 'ssh -p XXXX webbrouw@XX.XXX.XX.XXX' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude .htaccess --exclude .DS_Store /Users/Mac/Sites/projecten/katewood/wp-content/themes/ :/home/webbrouw/public_html/projecten/katewood/wp-content/themes`
`bash: rsync: command not found`
`rsync: connection unexpectedly closed (0 bytes received so far) [sender]`
`rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]`

I've installed rsync. Could you help me out here? 
Working trough ssh with a key pair.  

Would really appreciate it!

Have a good one!

Mickey

ps; The database moves correctly

**Comment by webbrouwer** [comment]
Hello There!

I've found out what the problem was. Rsync wasn't installed on the server. So that is why the command wasn't found. It works fine now. Awesome.

Thank you for making Wordmove!

Cheers,

Mickey

**Comment by pioneerskies** [comment]
Glad you solved. :8ball:
