### ISSUE TITLE
Virus detected message when using wordmove

### ISSUE THREAD

**Issue by gupta-ankit** [welaika/wordmove#173]
I started using wordmove and when pushing my website, I got the following message

mirror: Access failed: 550-Virus Detected and Removed: JCDEF.Obfus.CreateFunc.BackDoorEval-26.UNOFFICIAL default-option.php: Operation not permitted

Is my website infected or is it something with wordmove? Can you please help?

**Comment by pioneerskies** [comment]
Hi @gupta-ankit ,

Wordmove just transfers your files back and forth, so no, it is not a Wordmove issue.

You'd better to search for the `default-option.php` file and read its content. That said I don't know anything about the security scanning service in front of your site or your browser.

Cheers and good luck!
