### ISSUE TITLE
rsync: connection unexpectedly closed

### ISSUE THREAD

**Issue by paperrobots** [welaika/wordmove#177]
I'm trying to use Wordmove on a WPEngine server. They don't allow ssh but they do allow sftp. Here is the error message I'm getting: 

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.0]

Any thoughts?

**Comment by pioneerskies** [comment]
Please, refer to issue #133 for more info and news.

Thanks for your contribution.

Cheers
