### ISSUE TITLE
I really want to use wordmove, but I keep getting this error message.

### ISSUE THREAD

**Issue by MrLuisAmador** [welaika/wordmove#178]
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/home/tim/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find expected '-' indicator while parsing a block collection at line 23 column 5 (Psych::SyntaxError)
	from /home/tim/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	from /home/tim/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
	from /home/tim/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:58:in `fetch_movefile'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:20:in `deployer_for'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/tim/.rvm/gems/ruby-2.2.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /home/tim/.rvm/gems/ruby-2.2.1/bin/wordmove:23:in `load'
	from /home/tim/.rvm/gems/ruby-2.2.1/bin/wordmove:23:in `<main>'
	from /home/tim/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/tim/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by MrLuisAmador** [comment]
I was using the wrong indention. I'm not a Ruby guy...

**Comment by pioneerskies** [comment]
Yep! Glad to hear you solved before our support arrived :P

YAML is not really a Ruby thing (http://yaml.org/) and it is widely used in PHP world also, for example. But Ruby has built in YAML parser, so is very easy to use that standard format to write and read configuration files :)

Cheers
