### ISSUE TITLE
WordMove --pre: uninitialized constant Photocopier::Adapter (NameError)

### ISSUE THREAD

**Issue by joeguilmette** [welaika/wordmove#180]
I'm getting an `uninitialized constant` constant error when running the following commands:

```
$ gem uninstall wordmove
$ gem uninstall photocopier
$ gem install wordmove --pre
```

```
$ gem list | grep 'photo\|wordm'

photocopier (1.0.0.pre2)
wordmove (1.3.0.pre, 1.2.0)
```

```
$ wordmove push -t

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/photocopier-1.0.0.pre2/lib/photocopier/ssh.rb:2:in `<module:Photocopier>': uninitialized constant Photocopier::Adapter (NameError)
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/photocopier-1.0.0.pre2/lib/photocopier/ssh.rb:1:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:2:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:33:in `deployer_for'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/bin/wordmove:23:in `load'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/bin/wordmove:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

Note that I got the same error when manually installing photocopier (1.0.0.pre2) and modifying WordMove's dependencies: https://github.com/welaika/wordmove/issues/174

**Comment by pioneerskies** [comment]
`gem uninstall wordmove -v=1.2.0` does anything?

**Comment by Swingline0** [comment]
I seem to be getting this error as well. Versions below:

```
$ gem list | grep 'photo\|wordm'
photocopier (1.0.0.pre2)
wordmove (1.3.0.pre)
```

This seems to occur regardless of whether or not the scheme is declared as `ssh` or `ftp`. Remove the entire connection scheme block results in a more expected error:

```
/usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.0.pre/lib/wordmove/deployer/base.rb:36:in `deployer_for': No valid adapter found. (StandardError)
```

**Comment by pioneerskies** [comment]
Thanks for feedbacks guys. We are doing some investigations around the bug

**Comment by Swingline0** [comment]
You're my hero @pioneerskies!

**Comment by endorama** [comment]
Yep, it seems that I spotted the problem :) And I guess that also @delphaber got it, seeing it's last commit https://github.com/welaika/wordmove/commit/2915b04ac0746400ceb80ed54bbf90f667859789

Before that commit deployer/ssh and deployer/ftp require `photocopier/ssh` and `photocopier/ftp` respectively. Looking at the Photocopier gem code the dependency inclusion are at the `photocopier` level and not in single adapter. This lead to the above error.

@delphaber is possible to have a build with those last changes included? ( BTW, in my tests shellwords wasn't required in wordmove, as correctly required in photocopier )

**Comment by delphaber** [comment]
@endorama Yep, I'm working also on a new bug on photocopier. As soon as I am confident, I'll release a prerelease

**Comment by joeguilmette** [comment]
When we get this sorted I'm sending you guys a bottle of scotch or whatever
your drink is.

**Comment by delphaber** [comment]
@joeguilmette could you please try with the new prerelease version of wordmove?

`gem uninstall wordmove && gem install wordmove --pre``

*Please*, do a backup of local/remote files/db while using this beta version

**Comment by pioneerskies** [comment]
Hey @joeguilmette I'll drink my part of scotch as well as the @delphaber 's one! One of my favorites! :P

**Comment by joeguilmette** [comment]
You guys are just fantastic. Really. Works like a charm.

**Comment by pioneerskies** [comment]
Awwwww

So @delphaber 's fixes were good! :8ball: 

Figure out how to tell us if new features works, also! ;)

Cheers

**Comment by pioneerskies** [comment]
Oh, and I hope the update is working as well for @Swingline0 :)

**Comment by Swingline0** [comment]
Hey, @pioneerskies! Thanks for remembering me :)

I'm wondering if I'm doing something wrong here but my goal was to connect via SFTP however It seems that the connection is timing out.  Am I missing something in my Movefile?

```
  ftp:
    user: "mrbean"
    password: "mypassword"
    host: "blahblahblah.com"
    port: "22"
    scheme: "sftp" # default "ftp"
```

**Comment by pioneerskies** [comment]
Ouch... @Swingline0 I'm quite n00b about this issue. But I think sftp should be handled as an SSH connection, since the service is handled by sshd daemon. The scheme is in order to handle FTPS (FTP over SSL), not SFTP (SSH FTP).
I'd try to go with the `ssh` section, not the `ftp` one :)

**Comment by Swingline0** [comment]
Would a scheme property be acknowledged with SSH? It seems to fail when it attempts to execute `mysqldump` over the connection.

I don't see much mention of SFTP support over on Photocopier's readme which may point towards the protocol not really being supported?

**Comment by pioneerskies** [comment]
Hm, you're right: SFTP is an SSH's subsystem, but through it you haven't access to shell commands, but you're jailed in sort of fake shell someway emulating an FTP server. So it sounds like a third way between SSH and FTP(S) which could lead to these kind of problems.

But I should dig a bit more to be more exhaustive

**Comment by Swingline0** [comment]
Agreed, I'll try and do my due diligence in investigation as well. Thanks!
