### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by mlkayser** [welaika/wordmove#181]
I get the following error, regardless of what command I try (wordmove pull -w or wordmove pull -d):

```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): mapping values are not allowed in this context at line 2 column 8 (Psych::SyntaxError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:58:in `fetch_movefile'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:20:in `deployer_for'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:45:in `pull'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'
```

Any help would be great, thanks!

**Comment by pioneerskies** [comment]
HI @mlkayser , it seems you're just having a problem with your Movefile' sysntax :)

**Comment by mlkayser** [comment]
Grazie per la risposta Alessandro (io sono di Bergamo ma vivo in Maine :)), but I get the same error with wordmove pull --all. What I am doing wrong?

OWL-WebDev:wp mlorenzikayser$ wordmove pull --all

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): mapping values are not allowed in this context at line 2 column 8 (Psych::SyntaxError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:58:in `fetch_movefile'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:20:in `deployer_for'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:45:in `pull'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

**Comment by pioneerskies** [comment]
Hey let we take a look to your `Movefile`, please. All wordmove tasks depend the same way from the configuration. :) We'll try to understand something more.

Ciao!

**Comment by mlkayser** [comment]
Hi. I was able to pull the database after a few changes:

- commented out the password for ssh and entered it manually at the prompt
- adjusted the indentation of the Movefile (even one extra space on one line messes everything up)
- entered the command " sudo ln -s /Applications/MAMP/Library/bin/mysqldump /usr/local/bin/mysqldump" to make myqsldump (MAMP installation) available from the terminal

Maybe a list of common issues in the main wordmove page would help and save everybody time. Thanks for making the code available to the public and for the support!

**Comment by mlkayser** [comment]
Update: the command "wordmove pull -d" generates the following error:

/Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:55:in `remote_run': Error code 2 returned by command "mysqldump (. . . login details . . ) ": mysqldump: Got error: 1044: Access denied for user 'owl_wp'@'localhost' to database 'owl_wp_online' when using LOCK TABLES (RuntimeError)

An internet search brought up this solution to the 1044 error : 
mysqldump --opt --lock-tables=false -u USER -p DBNAME > dump.sql
mysqldump --opt --single-transaction -u USER -p DBNAME > dump.sql
http://alvinalexander.com/mysql/mysql-error-1044-access-denied-for-user-using-lock-tables

Do you have any insight? Thanks!

**Comment by pioneerskies** [comment]
hi @mlkayser :)

About https://github.com/welaika/wordmove/issues/181#issuecomment-120064102 I'm glad to hear about your progress. We usually stimulate users to write wiki pages and notice them to the stuff in order to contribute to the project. Please, if you think to have some time to spend on a task like that everyone would be grateful. E.g. in the wiki there's already a page about MAMP troubleshooting: https://github.com/welaika/wordmove/wiki/MAMP-tips

About the second comment https://github.com/welaika/wordmove/issues/181#issuecomment-120064102 ... ouch ... I've personally never encountered such an error :( :( :( Usually locking tables during an import is desirable...

**Comment by anhdq1801** [comment]
I have same problem with @mlkayser on both MAMP or Vagrant, any one have solution.

   ```
 /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:57:in `remote_run': Error code 2 returned by command "mysqldump --host=localhost --user=USER --password=PASSWORD --result-file="/home/JanStudio/helpdesk/wp-content/dump.sql" DBNAME": mysqldump: Got error: 1044: "Access denied for user 'USER'@'localhost' to database 'DBNAME'" when using LOCK TABLES (Wordmove::ShellCommandError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:67:in `download_remote_db'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:37:in `pull_db'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:69:in `block in pull'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:68:in `pull'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/wordmove:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/wordmove:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```
I try below code but it doesn't work
```
mysqldump --opt --lock-tables=false -u USER -p DBNAME > dump.sql
mysqldump --opt --single-transaction -u USER -p DBNAME > dump.sql
```

**Comment by pioneerskies** [comment]
Hi,

this issue is older than 1 year; firstly it should be better to open a new issue and fill it following the contribution guide found in the wiki.

On the specific subject: if neither calling directly `mysqldump` is working for you, why it should be a Wordmove's problem?
