### ISSUE TITLE
Pure-FTPd logout

### ISSUE THREAD

**Issue by mojenmojen** [welaika/wordmove#183]
I'm using wordmove on a host with Pure-FTPd. When I attempt to push my local site to this host, I get a 530 login authentication failed error at the first mkdir and then I get logged out. Apparently this is because the directory already exists. Here is what the pure-ftpd log reported:

Jul  8 14:02:00 host pure-ftpd: (?@2.219.151.17) [INFO] XXXXX is now logged in
Jul  8 14:02:11 host pure-ftpd: (XXXXX@2.219.151.17) [ERROR] Can't create directory: File exists
Jul  8 14:02:51 host pure-ftpd: (XXXXX@2.219.151.17) [INFO] Logout.

Is it possible to add a check to see if the directory exists before attempting to create it?

Edited to add: I believe I've ruled out any problem with the Movefile. The production environment host is the one with Pure-FTPd and that's the one that logs me out. The staging environment is on a different host (without Pure-FTPd) and there are no problems pushing there.

**Comment by delphaber** [comment]
Hi, I think we could remove the `mkdir -p PATH` command and use only the `cd PATH`. It's your responsibility to create PATH the first time (and probably your hosting server already did).

**Comment by delphaber** [comment]
@mojenmojen you can try the release version of wordmove (gem uninstall wordmove && gem install wordmove --pre)

In this version we check if folder exists with `find`. If not, we create the folder with `mkdir`.

*BE CAREFUL* : do a backup of your local and remote files / db while using a prelease (beta) version of wordmove

**Comment by mojenmojen** [comment]
Thank you very much, the new version is working perfectly now.

**Comment by pioneerskies** [comment]
This really rocks! :8ball: 

Thanks fro your feedback @mojenmojen, and thanks @delphaber for the really nice rework ;)
