### ISSUE TITLE
Rsync Permission denied (publickey) in VVV

### ISSUE THREAD

**Issue by yoren** [welaika/wordmove#184]
I stuck with this for days. So post here to see if anyone can help me with it.

Wordmove is great but since I use VVV, I'd like to use it my in Vagrant rather than in Mac OSX. The weird thing is, I can `wordmove push -p` from OSX, but when I do `wordmove push -p` in Vagrant (of course I remember to change the `wordpress_path`), I get **Rsync Permission denied error** like this:

<pre>
remote | put_directory: /srv/www/user/htdocs/wp-content/plugins /home/user/public/wp-content/plugins .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql
I, [2015-07-09T08:28:17.802534 #8597]  INFO -- : rsync --progress -e 'ssh user@remote' -rlpt --compress --omit-dir-times --delete --verbose --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' /srv/www/user/htdocs/wp-content/plugins/ :/home/user/public/wp-content/plugins
Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.0]
</pre>

The thing is:
I can run `rsync --progress -e 'ssh user@remote' -rlpt --compress --omit-dir-times --delete --verbose --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' /srv/www/user/htdocs/wp-content/plugins/ :/home/user/public/wp-content/plugins` fine and rsync files successfully from the command line in Vagrant, but not with wordmove.

Now I have to change the `wordpress_path` to the absolute path in OSX in my Movefile everytime I need to do `wordmove push -p`, because I need to do that from OSX. Then switch back to the absolute path in Vagrant when I need to do `wordmove push -d` because that can only work in Vagrant.

So far wordmove works great I just hope I can stick on one platform without switching back and forth.

Thanks for anyone who read this. The community of wordmove is amazing!

**Comment by pioneerskies** [comment]
hey @yoren thanks for your enquiry;

before proceeding with a troubleshoot I'd like to ask: have you already read this wiki entry: https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-(or-any-Vagrant) ?

**Comment by yoren** [comment]
Yep! I've read and set up wordmove with VVV based on it. Just have no idea why rsync doesn't work.

**Comment by joeguilmette** [comment]
Hi there, shoot me and email and I'll help you out. Joe.guilmette@gmail.com

**Comment by yoren** [comment]
My Gosh, this is miracle. After a few emails with @joeguilmette the problem goes away like it never happened before.

Now I can rsync with Wordmove without any error message. I wish I could remember what I've done, but to be honest I really don't know. There might be some issues with:

1. the ssh-agent
2. Vagrant doesn't halt properly or need to be provisioned again after some settings modified

Thanks you guys anyway. Wordmove rocks!

**Comment by pioneerskies** [comment]
:) Glad to hear that @yoren 

@joeguilmette is the community's VVV/Wordmove rockstar ^_^

Enjoy

**Comment by joeguilmette** [comment]
It probably helps having a actual vagrant troubleshoot Vagrant... Glad you
got it sorted!
