### ISSUE TITLE
How do you use environments?

### ISSUE THREAD

**Issue by ivandoric** [welaika/wordmove#188]
I want to have staging and production environments. And in the Movefile there is an option to set it up. But I couldn't find anything in the docs about using it. eg. How do I push database to production  environment? 

Thanks.

**Comment by adamraya** [comment]
Hi @ivandoric  I'm also trying to improve my workflow with wordmove, if you run `wordmove -h push` you'll find the answer, to push only database to production I think should be `wordmove push -d -e production`

**Comment by ivandoric** [comment]
Thanks @adamraya :) I think that's the only thing I haven't tried. Seems to be working.

**Comment by pioneerskies** [comment]
We'll add the specific information in the README. Thanks for your question :)
