### ISSUE TITLE
wordmove pull -d fails, but dump files are there.

### ISSUE THREAD

**Issue by defaria** [welaika/wordmove#189]
I am trying to pull content from testing server to local server. I get the following error.

    local | download mysite.com/wp-content/dump.php?shared_key=c93d8f437f76a12a2adba230f3680c9ae64e30c7f46c0d21806f49ed8372baf8fcbeedffb179f8b8 > /Users/developer/Sites/mysite/wp-content/dump.sql
    /Users/developer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `initialize': No such file or directory @ rb_sysopen - mysite.com/wp-content/dump.php?shared_key=c93d8f437f76a12a2adba230f3680c9ae64e30c7f46c0d21806f49ed8372baf8fcbeedffb179f8b8 (Errno::ENOENT)

The error says it can't find the file/directory, but the dump.php files are there, both local and testing server. The .sql files are also there.

So what's the issue?

**Comment by pioneerskies** [comment]
Seems to me `mysite.com` would need `http://` in front of it...?

Could you eventually paste here your `Movefile` (plz use markdown code formatting)?

**Comment by defaria** [comment]
You are correct. Missing http. Thank you!

**Comment by pioneerskies** [comment]
1 shot 1 kill! Cooool! :P :)

Cheers

**Comment by sigurdsvela** [comment]
Could we get a warning of some sort if this happens. "No such file or directory" is a pretty cryptic message
