### ISSUE TITLE
Unable use two environments in Movefile

### ISSUE THREAD

**Issue by DavidScanu** [welaika/wordmove#190]
I am unable to write 2 environments (1staging, 1 production) in the Movefile. Both environments works very well when alone in the Movefile. But only one of them works when the two are in the Movefile (one at the top). 
Example command : wordmove push -tdup -e=staging (works), wordmove push -tdup -e=production (doesn't work).

Détails : 
My local install is MAMP with subfolders in htdocs.
I managed to make the mysqldump command work in MAMP folder. 
My SSH connection is perfectly ok.

here is what I get :

    /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:36:in `deployer_for': No valid adapter found. (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:45:in `pull'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

**Comment by pioneerskies** [comment]
Hi @DavidScanu :)

Please, read this wiki page https://github.com/welaika/wordmove/wiki/Multiple-environments-explained and tell me if it helps solving your problem.

Spoiler: `wordmove push -tdup -e production` without the equal sign sounds better

**Comment by DavidScanu** [comment]
Thanks a lot for your answer. 

You did help me solve the problem. I was forgotting the ssh line under the staging environment. My two server (staging and production) are using the same server so they have the same ssh key and login. I was forgotting to repeat the ssh stuffs for each environment. As simple as that ! Sometimes, it is right under your nose !

**Comment by pioneerskies** [comment]
Just great to hear that!

Cheers
