### ISSUE TITLE
Pushing databases error

### ISSUE THREAD

**Issue by BobWassermann** [welaika/wordmove#192]
Hey all,

I have Wordpress setup with the actual wordpress as submodule (in a folder ``wordpress``) and all my content in a ``content`` folder (themes, plugins, etc).

I created a new FTP account where I can upload the files straight in (no ``www``, ``public_html``, etc). When I try to do so, I'll get the following error back:

    ▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
       remote | write /content/dump.php
    /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:327:in `getresp': 553 Can't open that file: No such file or directory (Net::FTPPermError)
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:352:in `block in sendcmd'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:350:in `sendcmd'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:430:in `transfercmd'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:547:in `block (2 levels) in storbinary'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:199:in `with_binary'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:546:in `block in storbinary'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:545:in `storbinary'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:694:in `putbinaryfile'
      from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/ftp.rb:722:in `put'
      from /usr/local/lib/ruby/gems/2.1.0/gems/photocopier-0.0.10/lib/photocopier/ftp.rb:21:in `put_file'
      from /usr/local/lib/ruby/gems/2.1.0/gems/photocopier-0.0.10/lib/photocopier/adapter.rb:18:in `put'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:74:in `remote_put'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:103:in `download_remote_db'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:23:in `push_db'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
      from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
      from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
      from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
      from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
      from /usr/local/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
      from /usr/local/bin/wordmove:23:in `load'
      from /usr/local/bin/wordmove:23:in `<main>'

I know about this topic: https://github.com/welaika/wordmove/issues/134, and mine might looks similar, but for some reason I can't figure it out.

Here's my ``Movefile`` (https://gist.github.com/BobWassermann/6e4d4c9b2394445aecd5), am I doing something wrong or is WP as submodule not supported?

**Comment by pioneerskies** [comment]
And have you already tried the more complex configuration suggested in [this paragraph](https://github.com/welaika/wordmove#ftp-support) of the readme?

**Comment by mukkoo** [comment]
No news. I'll close it. The documentation seems enough.
