### ISSUE TITLE
Wordpress already installed

### ISSUE THREAD

**Issue by manueljtejada** [welaika/wordmove#194]
After running `wordmove push --all` I visited my live site and completed the Wordpress setup, entering the database information. After completing the setup, I got an error message saying that Wordpress was already installed and that I had to clear my database tables in order to reinstall it. When I go to mysiteurl.com/admin I get a 404 error.

Any ideas on what's going on here?

**Comment by pioneerskies** [comment]
@manueljtejada have you closed because you solved?
