### ISSUE TITLE
Pushing database adds subdirectory to url

### ISSUE THREAD

**Issue by Jordan4jc** [welaika/wordmove#195]
My production environment setup looks like this in my Movefile

```
production:
  vhost: "http://gasfieldsvc.com"
  wordpress_path: "gasfieldsvc.com" # use an absolute path here
```

But when I push and attempt to go to wp-admin it forwards to `gasfieldsvc.com/gasfield` and in the options table of the database this is reflected there in `siteurl` and `home`.

Why is this subdirectory name getting added after all the URL's?

**Comment by pioneerskies** [comment]
Hello :)

    wordpress_path: "gasfieldsvc.com" # use an absolute path here

but that is not an absolute path afaik

**Comment by Jordan4jc** [comment]
When I ssh in that is the only folder I see, I have a staging environment that works the same way, when I ssh into the staging environment I see a folder called `dev.fotype.com` and in that folder there is another folder called `gasfield`. In the environment for the staging I have this listed

```
staging:
  vhost: "http://dev.fotype.com"
  wordpress_path: "dev.fotype.com/gasfield" # use an absolute path here
```

And that works just fine.

**Comment by pioneerskies** [comment]
Already given a try with

```
wordpress_path: "/gasfieldsvc.com"
```

?

Sorry for the delay, but we're jast back-to-school here in welaika :)

**Comment by mukkoo** [comment]
No news. I'll close this issue, seems resolved.
