### ISSUE TITLE
Doesn't move all WP files - ie: mu-plugins

### ISSUE THREAD

**Issue by mikeselander** [welaika/wordmove#200]
Hi there, I do a good amount of development in mu-plugins and the tool doesn't seem to move anything beyond the plugins/themes/uploads folders in wp-content, although it does catch extraneous folders in the root when using '--all'. I tried to assign an unused path (languages, in my case) to wp-content/mu-plugins but it won't properly move it when renamed either. Am I missing something or does it just not move anything but simple folders?

Thank you for your hard work on this!

**Comment by pioneerskies** [comment]
Hi @mikeselander ,

thanks for reporting the issue. That's already known and tracked here https://github.com/welaika/wordmove/issues/117; I'd like to grab all the relatives comment in that issue, so I'm going to close this one in order to keep the tracker tidy.

Cheers

**Comment by mimosafa** [comment]
し
