### ISSUE TITLE
Issue reading password with a semicolon character

### ISSUE THREAD

**Issue by defaria** [welaika/wordmove#202]
This might be an issue with lftp or wordmove, but I thought I would report it. I typically use generated passwords which often includes punctuation. Either wordmove or lftp had issues reading the password with a semicolon in it.

My password was : u::0.OCJf.;L@rnF

and the error I got:

Unknown command `L@rnF@mydomain.com'.
mkdir: Not connected
cd: Not connected
mirror: Not connected

I realized where the line was breaking, removed the semicolon and everything worked just fine. I'm not sure if using semicolons in a password is be a big "no no", but I never had issues elsewhere.

**Comment by Arkham** [comment]
Hey there, did you make sure to wrap the password with double quotes in the `Movefile`?

**Comment by defaria** [comment]
Yep. I will run another test and put the results here.

**Comment by pioneerskies** [comment]
@defaria we're back from holidays and will wait for results :)

Thanks for sharing the possible issue.

**Comment by delphaber** [comment]
@defaria could you please try with wordmove 1.3.0 ?

`gem install wordmove` to download the latest version from rubygems.org

**Comment by defaria** [comment]
I was having issues with passwords containing ; and &.  I was using double quotes and I also tried with single quotes.

Updating to version 1.3 worked.

**Comment by defaria** [comment]
is there a changelog to see what's new with version 1.3?

**Comment by delphaber** [comment]
Yup! https://github.com/welaika/wordmove/blob/master/CHANGELOG.md

**Comment by defaria** [comment]
Thanks!
