### ISSUE TITLE
Staging backup file not found

### ISSUE THREAD

**Issue by rgantree** [welaika/wordmove#203]
Hi there,

I'm using Wordmove with VCCW and all run fine, apart from "Pushing database" where I get an error:
remote | get: /var/www/vhosts/.../wp-content/dump.sql /Users/user/.../www/wordpress/wp-content/staging-backup-1439388114.sql
/usr/local/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp/download.rb:156:in `initialize': No such file or directory @ rb_sysopen - /Users/user/.../www/wordpress/wp-content/staging-backup-1439388114.sql (Errno::ENOENT)

Can someone help with this please.

**Comment by pioneerskies** [comment]
Hello @rgantree ; why you have closed this on your own? Have you solved?
It should be useful to share the solution w/ the community if it could help others.

Cheers :)

**Comment by rgantree** [comment]
Hello @pioneerskies 
thank you for picking up this issue.
No, I didn't solve it yet, I just had to move to some other work I have to do.
would still love to get it done as it is the last step for me to get moving with VCCW.
Any chance you would know?

cheers :)

**Comment by pioneerskies** [comment]
Ok, cool. We can try, but I'd like to take a look to your Movefile before starting any troubleshoot.
Remove sensitive data from it and use github syntax formatting tool in order to take it readable.

**Comment by thespotvin** [comment]
Hello - I'm having the same problem - the script appears to be looking for this file:

staging-backup-1445619031.sql

But the file in wp-content is:

staging-backup-1445618751.sql

Here's my Movefile:

https://gist.github.com/thespotvin/e6037aebab6e5cc7b43f

**Comment by mukkoo** [comment]
@rgantree can you retry with wordmove 2.0 ?
