### ISSUE TITLE
wordmove pull -d fails

### ISSUE THREAD

**Issue by connormckelvey** [welaika/wordmove#207]
Setting up a new site for a client, wordmove pull -e production --all works for everything and then fails when it gets to the database:

/Users/redacted/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `initialize': No such file or directory @ rb_sysopen - www.redacted.org/wp-content/dump.php?shared_key=redacted(Errno::ENOENT)

However when I FTP in myself, I can see the dump file. When I open www.redacted.org/wp-content/dump.php?shared_key=redacted in the web browser or wget it, i get the SQL file.

**Comment by pioneerskies** [comment]
You've done an already good troubleshooting; and what is the content of the SQL file? It has all the contents as expected or is somewhat incomplete?

**Comment by connormckelvey** [comment]
It was a complete SQL file though it was somewhat larger than the sites I use wordmove with usually have. 

My coworker figured it out. For the database host, he put redacted.org (and it works), where as I put localhost. To me since the database export was using the php script that is FTP'd up, localhost seems to make the most sense even though either could work. 

That being said, I think this is still a bug as 2 database hosts that resolve to the same IP should not affect Wordmove's ability to download a URL over HTTP.

**Comment by mukkoo** [comment]
@connormckelvey can you retry with wordmove 2.0 ?
