### ISSUE TITLE
Whats the default for push? can we set it?

### ISSUE THREAD

**Issue by rockethouse** [welaika/wordmove#208]
Hi,

I have wordmove setup and working perfectly (it's really really good).

My only question is what is the default argument for 'wordmove push'? does that do everything? uploads, db and theme?

Is there a way we can set the default to be theme only? My reasoning is once i've done my initial push, after that I only 90% of the time want to push the theme again... and since setting some 'live-only' WP settings like "Hide from search engines" I don't want to accidentally push my database again and change that on the live site...

Cheers

**Comment by pioneerskies** [comment]
Hi @rockethouse,

WordMove does absolutely nothing by default :)
So 1) you don't risk to push something by mistake 2) probably we should think to drop a "no args" error to make this more explicit.

Feel free to reopen if my answer is someway not satisfying

Cheers

**Comment by rockethouse** [comment]
Ah awesome! I was too scared to check and find out. That is great - thanks
