### ISSUE TITLE
Set default permissions for Movefile

### ISSUE THREAD

**Issue by rockethouse** [welaika/wordmove#209]
Hi, me again!

Another quick one... I noticed that the Movefile is readable by world, therefor if your dev environment is online like mine (I know it shouldn't but I have my reasons) - it is accessible at site.devurl.com/Movefile and that's definitely not something you want leaked or accessible to the public.

I've been able to fix it easily enough by changing the permissions of Movefile to 660 but i'm sure one day in the future I will forget again, so perhaps could this be added in?

Just an idea!

**Comment by pioneerskies** [comment]
Hello and thanks for sharing your needs and experience.

Could you elaborate more on the subject? Where do you think Wordmove should manage file permissions?
By default I think if you use SSH+rsync for the transfer it will try to keep the local octals on the remote server; I really don't know if lftp does support something like that honestly.

**Comment by rockethouse** [comment]
Oh, I mean when you run wordmove init and it creates the "Movefile" it sets the permissions as 664 (read to world) I think 660 would be better, that way it can't be viewed in a browser.

**Comment by pioneerskies** [comment]
Ok, clearer to me, thanks. A question: if you chmod the file to 660 1 time, then you push/pull your things, will permissions be kept?

**Comment by rockethouse** [comment]
Hi,

Yes I think it will as it is skipped over by default, but no need to worry, I have just realised I can hide the file in the nginx config on my dev server, that will fix it.

Thanks
