### ISSUE TITLE
Dump.php problem

### ISSUE THREAD

**Issue by oterox** [welaika/wordmove#210]
Hi,
I've just installed wordmove and i'm having problems with the dump script.
I get this error:
PHP Parse error:  syntax error, unexpected '{', expecting ')' in /home/website.eu/clients/plugin/wp-content/dump.php on line 41

And if i edit dump.php i can see the problem:
```
	public function __construct(mysqli $connection, $charset = 'utf8'
	{
		$this->connection = $connection;

		if ($connection->connect_errno) {
			throw new Exception($connection->connect_error);

		} elseif (!$connection->set_charset($charset)) { // was added in MySQL 5.0.7 and PHP 5.0.5, fixed in PHP 5.1.5)
			throw new Exception($connection->error);
		}
	}
```

There's a missing ")" on the function definition after $charset = 'utf8'

Is this a bug or am i doing something wrong?

I used wordmove some months ago and it worked fine.

Thank you, this is a GREAT tool !!!!

**Comment by oterox** [comment]
You have a little mistake in this file, line 40:
lib/wordmove/assets/dump.php.erb

;)

**Comment by delphaber** [comment]
You are right. I'm gonna fix it right now!

**Comment by delphaber** [comment]
Hi. It should be fixed in `1.3.1` now. Please update with `gem install wordmove`. Thank you!

**Comment by oterox** [comment]
the version i'm using is  wordmove-1.4.0.pre2

**Comment by delphaber** [comment]
This is pretty strange because `pre` versions get installed only if you pass `--pre` to `gem install`. Anyway I'm going to release also a new pre version.

Be careful: pre release versione are unstable

**Comment by delphaber** [comment]
pre3 version release.
