### ISSUE TITLE
How to install lftp on Windows 7?

### ISSUE THREAD

**Issue by creativezed** [welaika/wordmove#211]
How can I install lftp on Windows 7? I tried installing it using Cygwin but it didn't seem to work. Is there any other way of installing it globally on Windows 7?

I am using Git Bash to run Wordmove. I can access lftp via Cygwin Terminal but can't access it via Git Bash.

**Comment by iDuuck** [comment]
Although this is not the place to ask for support for lftp you just need to go through Google and search for `LFTP for Windows 7`.

First thing I found was http://nwgat.ninja/lftp-for-windows/
Hope this helps

**Comment by creativezed** [comment]
I have already tried this. It didn't work. I've spent almost the whole day searching for a solution but nothing has worked so far.

**Comment by iDuuck** [comment]
So, I just read that you are using Git Bash. Could you tell us what Git Bash is doing?

**Comment by creativezed** [comment]
When I push the site it starts the uploading process but it gets completed within a couple of seconds but nothing actually gets uploaded. When I try to check the version of lftp via Git Bash I get the "command not found" error. However if I check the version of lftp via Cygwin terminal it does show the version of lftp installed.

**Comment by iDuuck** [comment]
try uploading something without wordmove and only with help of lftp to check if it's an issue with lftp or your pc.

**Comment by creativezed** [comment]
I tried connecting directly through lftp using regular FTP via Cygwin terminal and I got the following error:
Fatal error: Certificate verification: subjectAltName does not match ‘domain.com’

But when I tried to connect using SFTP - lftp got connected and I was able to transfer files without any problem.

Is there a way I could use SFTP instead of regular FTP? Maybe that will work.

**Comment by iDuuck** [comment]
SFTP == SSH. So just switch to SSH

**Comment by creativezed** [comment]
I just tried SSH with wordmove. It did the exact same thing. Completed the uploading process within a couple of seconds but nothing got uploaded.

**Comment by iDuuck** [comment]
Strange. No error message?

**Comment by creativezed** [comment]
Not at all. It seems like it runs the complete uploading procedure but the files are not actually getting uploaded. I have tried it several times and it does exactly the same thing every time both with FTP and SSH.

Using Movefile:
Pushing wordpress code:
Pushing uploads:
Pushing Themes:
Pushing Plugins:
Pushing Languages:
Pushing Database:

**Comment by dzonivejin** [comment]
Totally same thing on Windows 8 and Windows 10 here.

I tried installing LFTP multiple ways on Windows and none works with Wordmove.

But now, I'm not sure if it's only LFTP issue after all, since Wordmove doesn't work with SSH too on Windows, at least for me (and I have everything set properly for it to work with SSH).
Wordmove finishes everything without outputting any errors (connects to site via SSH successfully, says it's pushing files...) in command prompt, but actually doesn't do anything (doesn't move files or db).

So pretty much the same issue Creativezed had.

I know Wordmove is not tested on Windows too much, so I'm wondering if it does work on Windows at all? Anyone using it on Windows?

**Comment by neocamel** [comment]
I'm having the exact same problem.  Connect via SSH.  Using wordmove push --all, and it looks like it's working, but nothing appears on the server.

**Comment by iDuuck** [comment]
Please test if it is working, if you push something over `lftp` manually.

**Comment by ChuckMac** [comment]
I'm a little late here... but I use WordMove on Windows successfully.  For those that are having issues do you have openssh installed as well?

**Comment by creativezed** [comment]
I have OpenSSH installed but still no success. Are you using Windows 7? Can you please share how you setup wordmove on your PC step by step. It will be very helpful for a lot of people. Thanks!

**Comment by creativezed** [comment]
By the way, I can only access SSH via Cygwin Terminal and not by the Command Prompt. Maybe that's what's causing the problem? Can you access SSH via Command Prompt after installing openSSH?

**Comment by ChuckMac** [comment]
@creativezed Unfortunately I set this up almost 2 years ago so I don't remember exactly what I did step by step.  Maybe I will see if I can setup a clean VM image and get it working in there.

As for the SSH, yes I can access it from the normal command prompt.  I have it pointing to the version that is bundled with GIT.

`C:\Users\chuckmac>ssh
usage: ssh [-1246AaCfgkMNnqsTtVvXxY] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-e escape_char] [-F configfile]
           [-i identity_file] [-L [bind_address:]port:host:hostport]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-R [bind_address:]port:host:hostport] [-S ctl_path]
           [-w local_tun[:remote_tun]] [user@]hostname [command]


C:\Users\chuckmac>where ssh
C:\Program Files (x86)\Git\bin\ssh.exe`

**Comment by creativezed** [comment]
@ChuckMac I think we've figured out what's causing this problem. Can you please guide me how I can setup SSH to work via Command Prompt. I'll give wordmove a try again after that and I have a strong feeling that this will work. Thanks again!

**Comment by ChuckMac** [comment]
@creativezed install [Git for Windows](https://git-scm.com/download/win).  Add <the directory you install it to>/bin to your system PATH.

**Comment by creativezed** [comment]
@ChuckMac I have already installed Git for Windows. How do I add /bin to system PATH?

**Comment by ChuckMac** [comment]
`setx path "%path%;C:\Program Files (x86)\Git\bin\"`

(or whatever directory you installed it)

**Comment by ChuckMac** [comment]
@creativezed strage.. you can try it the GUI way if that is not working for you:

http://www.computerhope.com/issues/ch000549.htm#windows7

**Comment by theelectroseed** [comment]
DItto with wordmove on windows just showing remote connection with no errors on upload but not actually uploading jack dittly.

**Comment by mukkoo** [comment]
We have just published a disclaimer about Windows Support https://github.com/welaika/wordmove/wiki/Windows-(un)support-disclaimer
GLHF

**Comment by pioneerskies** [comment]
@here Take a look at the dev branch and try to update to the latest pre-relase: we've merged 2 FTP-related PRs.

    gem update wordmove --pre

I'm closing here, because we're mixing issues: the OP requested help installing LFTP. There's another issue tracking the "does not upload anything on windows". Move there the appropriate discussion, please
