### ISSUE TITLE
mysqldump error on push

### ISSUE THREAD

**Issue by klangwiedergabe** [welaika/wordmove#212]
I'm using Mamp, and i did follow all of this instructions https://github.com/welaika/wordmove/wiki/MAMP-tips but I'm still getting this error:

mysqldump --host=localhost --user=b691feea4e50 --password=yolopass22 rwd_hello --result-file=/apps/rwdproject/public/wp-content/dump.sql
   remote | mysqldump --host=localhost --user=b691feea4e50 --password=yolopass22 rwd_hello --result-file=/apps/rwdproject/public/wp-content/dump.sql
/Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:51:in `remote_run': Error code 1 returned by command "mysqldump --host=localhost --user=b691feea4e50 --password=yolopass22 rwd_hello --result-file=/apps/rwdproject/public/wp-content/dump.sql": mysqldump: Can't create/write to file '/apps/rwdproject/public/wp-content/dump.sql' (Errcode: 2) (Wordmove::ShellCommandError)
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:58:in `download_remote_db'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:15:in `push_db'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2@global/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /Users/alexplaza/.rvm/rubies/ruby-2.1.2/bin/wordmove:23:in `load'
	from /Users/alexplaza/.rvm/rubies/ruby-2.1.2/bin/wordmove:23:in `<main>'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/alexplaza/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

what could it be?

**Comment by pioneerskies** [comment]
> Can't create/write to file '/apps/rwdproject/public/wp-content/dump.sql'

IMHO you simply have not write permission inside that directory. Check the directory permission with `ls -l /apps/rwdproject/public/wp-content` and/or the upper levels of the dir tree

**Comment by klangwiedergabe** [comment]
The command told me:

ls: cannot access /apps/rwdproject/public/wp-content: No such file or directory

I got inside public and i ls -l, and show me this

-rwxrwxrwx  1 serverpilot serverpilot   418 Sep 24  2013 index.php
-rwxrwxrwx  1 serverpilot serverpilot 19930 Jan  1  2015 license.txt
-rwxrwxrwx  1 serverpilot serverpilot  7358 Apr 23 14:00 readme.html
-rwxrwxrwx  1 serverpilot serverpilot  4951 Aug 20  2014 wp-activate.php
drwxrwxrwx  9 serverpilot serverpilot  4096 Aug 18 14:13 wp-admin
-rwxrwxrwx  1 serverpilot serverpilot   271 Jan  8  2012 wp-blog-header.php
-rwxrwxrwx  1 serverpilot serverpilot  5007 Jan  8  2015 wp-comments-post.php
-rwxrwxrwx  1 serverpilot serverpilot  1175 Sep  1 23:48 wp-config.php
drwxrwxrwx  4 serverpilot serverpilot  4096 Aug 18 14:13 wp-content
-rwxrwxrwx  1 serverpilot serverpilot  3286 May 24 13:26 wp-cron.php
drwxrwxrwx 12 serverpilot serverpilot  4096 Aug 18 14:13 wp-includes
-rwxrwxrwx  1 serverpilot serverpilot  2380 Oct 24  2013 wp-links-opml.php
-rwxrwxrwx  1 serverpilot serverpilot  3123 Apr 12 17:29 wp-load.php
-rwxrwxrwx  1 serverpilot serverpilot 34669 Jul 28 23:56 wp-login.php
-rwxrwxrwx  1 serverpilot serverpilot  8252 Jul 17  2014 wp-mail.php
-rwxrwxrwx  1 serverpilot serverpilot 11062 Jun 24 22:29 wp-settings.php
-rwxrwxrwx  1 serverpilot serverpilot 25124 Jun 26 21:03 wp-signup.php
-rwxrwxrwx  1 serverpilot serverpilot  4035 Nov 30  2014 wp-trackback.php
-rwxrwxrwx  1 serverpilot serverpilot  3055 Jul 28 08:17 xmlrpc.php

I'm lost :)

**Comment by pioneerskies** [comment]
what's the output of `pwd` inside the public dir?

As an aside: your permission are widely too open AFAIK :) It doesn't hurt Wordmove, but could be a security issue.

**Comment by klangwiedergabe** [comment]
never mind I'm done with wordpress.
