### ISSUE TITLE
First push mistake

### ISSUE THREAD

**Issue by kobrix** [welaika/wordmove#217]
And here's another comment from a newbie, which might hopefully mean someone else doesn't make the same mistake.

My first test of Wordmove push didn’t go very well. Most significantly, I was _not_ expecting this:

```
Removing old file `.bash_logout'
Removing old file `.bash_profile'
Removing old file `.bashrc'
Removing old file `.contactemail'
Removing old directory `.cpanel'
Removing old directory `.ftp_enforcer'
Removing old file `.ftpquota'       
Removing old directory `.htpasswds'
Removing old file `.lastlogin'     
Removing old directory `.softaculous'
Removing old file `.zshrc'     
Removing old file `access-logs'
Removing old file `cpbackup-exclude.conf'
Removing old directory `etc'
Removing old directory `logs'   
Removing old directory `mail'                             
Removing old directory `public_ftp'
Removing old directory `public_html'
Removing old directory `ssl'                           
Removing old file `www'       
```

Luckily this was a test account so nothing important lost (but unusual activity meant my IP was blocked temporarily!).

Other problems were that the upload repeated several times (it seemed to recurse), some directories could not be made, and some files which were explicitly excluded by Movefile were uploaded anyway.

This was definitely user error, but the fact that wordmove accesses the directory above `public_html` is a bit alarming, especially as `--simulate` seemed to show everything would work as expected.

My mistake was to not include directory `/wp` at the end of my local `wordpress_path:` and once this was added the push worked properly.

**Comment by pioneerskies** [comment]
Added documentation mirroring behavior in main README and about appending subdirectories into the wiki.
