### ISSUE TITLE
How do I tell Wordmove what my SSH keys are?

### ISSUE THREAD

**Issue by jovboz** [welaika/wordmove#218]
I know there might be a simple answer, but I lost about an hour...

How do I tell Wordmove what/where my SSH keys are if I use keys without password for connection? It says 'password is optional, will use public keys if available', so I leave it blank cause I have keys, but how can Wordmove know where my keys are located, how do I tell it?

Thanks,
Jovana

**Comment by pioneerskies** [comment]
Hi there!

Please, don't leave the password blank, but comment/delete the key in the Movefile YAML.
Let me know if it helps ;)

**Comment by momolog** [comment]
@pioneerskies Yes, that helps :-)
