### ISSUE TITLE
default Movefile

### ISSUE THREAD

**Issue by sebszocinski** [welaika/wordmove#220]
Hi,

Would it be possible to add a feature to setup a default Movefile template? most of my websites will have a very similar default configuration minus the site url and slug of the server user etc.. 

It would be great if we could define our own starting Movefiles

If that makes sense?

**Comment by pioneerskies** [comment]
We left this open, but the feature can't enter in the roadmap. Copy/paste has a too high expense/result ratio compared to a feature implementation.

So long and thanks for all the fish
