### ISSUE TITLE
Database pull using MAMP 'fails'

### ISSUE THREAD

**Issue by leanderrj** [welaika/wordmove#221]
I'm using MAMP (PRO) for local development and when i try to pull a database it doesn't change the local database. Wordmove doesn't give any errors though. An .SQL file appears in /wp-content, which stays there. I'm guessing the PHP script isn't running when i pull the database.

I'm pretty new at this and i've looked for a solution but i haven't found anything.

**Comment by pioneerskies** [comment]
Hello!

Already read this wiki entry? https://github.com/welaika/wordmove/wiki/MAMP-tips
Have you got the same db prefix on both environments?

**Comment by leanderrj** [comment]
Yes, the mysqldump command does work. The databases also have the same prefix.

The weird thing is that pushing the database works. Below i've included the return of the pull command. 

```
▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=root --password=root DBname --result-file=/Users/leanderrj/Sites/website1/wp-content/local-backup-1442923603.sql
    local | mysqldump --host=localhost --user=root --password=root DBname --result-file=/Users/leanderrj/Sites/website1/wp-content/local-backup-1442923603.sql
   remote | write /domains/mydomain.nl/public_html/staging/wp-content/dump.php
    local | download http://mydomain.nl/staging/wp-content/dump.php?shared_key=121c7a9fa7ba428d45470debd11a98a65a61e8df032a12844cd297af09db96a14bb3c0395962c477 > /Users/leanderrj/Sites/website1/wp-content/dump.sql
   remote | delete: /domains/mydomain.nl/public_html/staging/wp-content/dump.php
    local | adapt dump
mysql --host=localhost --user=root --password=root --database=DBname --execute=SOURCE\ /Users/leanderrj/Sites/website1/wp-content/dump.sql
    local | mysql --host=localhost --user=root --password=root --database=DBname --execute=SOURCE\ /Users/leanderrj/Sites/website1/wp-content/dump.sql
    local | rm /Users/leanderrj/Sites/website1/wp-content/dump.sql
```

**Comment by defaria** [comment]
I am having the same issue described by @leanderrj 

I had version 1.3.1. installed when I was having this issue.
So I downgraded to version 1.3.0 and still had the same issue.
Then I downgraded to version 1.2.0 and the issue went away.

As @leanderrj said, I am able to push the database, but not pull. Which means something is failing during the remote database dump. I noticed that the database .sql created had 0 bytes.

I am not sure issue is related to mamp though. Because it's does't fail to push and it doesn't fail to import, it's just trying to import an empty .sql file.

Right now, my solution is to downgrade to 1.2.0 - I am going to compare the version later on to see what could be causing it to fail.

Thanks

**Comment by leanderrj** [comment]
Thanks @defaria! Downgrading worked for me too!

The issue is about the same though i do want to mention that my database .sql did have contents. 

The .sql file is significally smaller than the remote database, 268kb from a 2mb database. (Probably just the db differences?)

I cant really read .sql but i thought me mentioning this might help.

**Comment by rickertl** [comment]
I am having this issue as well. Is the only solution to downgrade?

**Comment by leanderrj** [comment]
@rickertl. For now, yes. Downgrading to 1.2.0 fixed it though

**Comment by rickertl** [comment]
Are you guys using FTP instead of SSH? I ask because the DB pull works just fine with SSH, but not with FTP. Unfortunately the hosting for one client does not allow SSH or I would be all set. Thanks.

**Comment by leanderrj** [comment]
I only use FTP.

**Comment by kaizokou** [comment]
Same problem with FTP here (can't use SSH on remote host).

When pulling.
1 - Local dump is OK
2 - Remote dump.php is created dump.mysql is created.
3 - local download dump.sql ==> EMPTY FILE !
4 - Adap
5 - local database update
6 - rm remote file.

> first  problem is that the dump.mysql is not complete and contain a lot of data from other wordpress/joomla installed on the share DB. We need a way to tell the script to import only the prefix find in wp-config.

> second problem at steep 3 => dump.sql is empty.

@pioneerskies  any idea how to make the script work on shared host ?

**Comment by herbie4** [comment]
Had the same issue. 
Using ftp you should downgrade to Wordmove version 1.2.0. 
That made it work for me.
https://github.com/welaika/wordmove/issues/259

**Comment by mukkoo** [comment]
As write on https://github.com/welaika/wordmove/issues/280 this problem is resolved. We'll release soon the 1.4.0 stable version.
