### ISSUE TITLE
Pages in Wordpress not pushed

### ISSUE THREAD

**Issue by garybrowne** [welaika/wordmove#222]
Hi,
This is a fantastic gem, thank you.
Could you tell me if any of the following are moved with a push --all:
* posts/pages
* theme options
Thanks,
Gary

**Comment by defaria** [comment]
push --all pushes everything including -d, which is the database where your posts/pages/themes options are typically stored.

**Comment by garybrowne** [comment]
thanks - turns out my wp-configs were slightly different (different $table_prefix)
