### ISSUE TITLE
Excluding folders issue

### ISSUE THREAD

**Issue by defaria** [welaika/wordmove#223]
I told wordmove to exclude the folder images:

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/_"
    - "Gemfile_"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"
    - ".idea/"
    - "images/"

After adding the folder images to the exclude list, I pushed it to my dev server. The website loaded and told me that it could not find wp-includes/images

So it excluded the images folder in the root, but also excluded the wp-includes images folder.

So I removed "images/" from the exclude list, and pushed again, and now the images folder synced.

I am using Wordmove 1.2.0 (because I am having other issues with 1.3.1).

Do I need to specify the full path? Or am I entering the path wrong?

Update:
I just noticed that wordmove ended up excluding all folders named images (not only wp-includes/images).

**Comment by kobrix** [comment]
My understanding is that it follows the pattern used by rsync, so:

"images/" excludes any folder anywhere called "images"
"/images/" excludes the folder "images" in the root directory
"/images" excludes the file "images" in the root directory

In other words, a trailing slash means the preceding is a folder, and a leading slash means start at the root.

I hope a late answer isn’t too late!

**Comment by pioneerskies** [comment]
What @kobrix said here was exact. We does not actually follow the rsync pattern, but we just prox options to rsync. So how rsync works is exctly how we (would like to) work.

I'll close this.
