### ISSUE TITLE
Is there a way to pass options to mysqldump?

### ISSUE THREAD

**Issue by axyz** [welaika/wordmove#224]
specifically I had to use `--compatible=mysql40` to make the script work on older mysql hosts.

**Comment by pioneerskies** [comment]
The feature was introduced by (this commit)[https://github.com/welaika/wordmove/commit/a8d77c2ffe11650962d03f849989069cb5a42d91] and it's on the dev branch.

You can install the gem corresponding to the gem branch with `gem install wordmove --pre`.

Any feedback is really appreciated when using --pre gem ^_^ AFAIK it's stable, but more feedback means faster stable gem deploy.

Cheers. And reopen if you'll need help! :+1:
