### ISSUE TITLE
Installing problem on OSX 10.11

### ISSUE THREAD

**Issue by AndreaBarghigiani** [welaika/wordmove#226]
Hi there,

I have always used your gem with pleasure but this morning, after updating my OS, I am unable to launch it... It appears as the system has removed it and I don't understand why...

So I opened my terminal and launched: `sudo gem install wordmove`

but after it I receive this error message:
```
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/wordmove
```

I tried to look over Google but couldn't be able to find anything useful...

Do you have any idea?

Thanks for the future help!

**Comment by delphaber** [comment]
Hi, probably because of SIP. Anyway, I think it's a good practice to DO NOT install gems as sudo :)

Have you tried to install it without sudo?

**Comment by AndreaBarghigiani** [comment]
Hi @delphaber,

what do you mean by SIP?

Anyway I tried to run `gem install` without `sume` but it tells me that I do not have write permission on the `/Library/Ruby/Gems/2.0.0`

Do you think I have to make it writeable?

**Comment by pioneerskies** [comment]
https://en.wikipedia.org/wiki/System_Integrity_Protection

This is going to be a big pain, but os totally unrelated to Wordmove. The bigger advise I'd have is to use a ruby version manager such as rbenv or rvm.

**Comment by mukkoo** [comment]
No news. We consider this issue closed. @AndreaBarghigiani reopen the issue if needed
