### ISSUE TITLE
Multisite support?

### ISSUE THREAD

**Issue by JoshRiser** [welaika/wordmove#227]
I saw [this issue](https://github.com/welaika/wordmove/issues/45) that said multisite was not supported fully, however that was posted over two years ago.

I was just wondering what the implementation looks like right now? I am about to develop a multisite platform that will be the first since I started using Wordmove and wanted to see what my workflow will look like as far as pushing/pulling to staging/development environments etc.

**Comment by jmichaelward** [comment]
+1, as I'm working on a multisite project right now, and this would be great to have.

**Comment by dsgnr** [comment]
Just thought I'd ask if there was any progress with this? I am working on a multisite project at the moment and it pains me to have to do everything manually after using Wordmove for so long!

**Comment by dsgnr** [comment]
I managed to have a play today with a multisite install which uses subdirectories (eg. www.domain.com/site1, www.domain.com/site2 etc). Providing the root domain is the same, removing http:// from the Wordmove file and leaving the main domain seemed to work perfectly for me where as it missed parts before. 

I don't have a subdomin multisite but may look into this and see if I can edit the code.

**Comment by dezinerdudes** [comment]
Thanks for the update. Im also using a multisite install for clients. @dsgnr could you just explain what you needed to do to make it work with subdirectories?

**Comment by dsgnr** [comment]
@dezinerdudes All I did was remove http:// from the vhost and it seems to be able to change the blog and sites table when using subdirectory. 

I have no idea about subdomains though!

**Comment by pioneerskies** [comment]
Guys this is not going to be supported by the core team. PR are always welcome.
And moreover if you found a working method it would be great to open a wiki page and PR an update to the `README.md` if needed.

**Comment by dsgnr** [comment]
@pioneerskies that's completely understandable. It's really good that it works with subdirectory multisite though as it is. I keep meaning to have a go at getting it to work with subdomains but never get round to it.

I think a readme/wiki update would be beneficial as it works, just within a limit. I will work on this over the next few days and push a PR :)

**Comment by JoshRiser** [comment]
I've not been able to get it to work even with a subdirectory install. There are 2 tables that still have to be modified when moving a multisite directoy: wp_site and wp_blogs. They each have a "domain" column that needs to be changed to the new domain.

**Comment by dsgnr** [comment]
I haven't actually used sub domain multi site before. Could it work if you changed the vhost in Wordmove to just domain.co.uk? Just emitting http and www.

All I do for sub directory multisite is remove the http part of the vhost and it changed the wp_site and wp_blog tables

**Comment by JoshRiser** [comment]
@dsgnr I can see how that would work, the issue for me is I don't have my WordPress installations in the main directory of the domains. I.E. on my local server (MAMP) I have a WP installation at **localhost/mysite**. Then we have a staging server where we upload all of our development sites in subdirectories, so the site would be at **dev.mystaging.com/mysite**.

In both tables there is a _domain_ and _path_ column, in my example, the _domain_ column would have to be set to **localhost** or **dev.mystaging.com** and then the _path_ column would be **/mysite/blog1**, **/mysite/blog2**, etc.

From what I can tell, Wordmove just does a find and replace with the vhosts, but in my case the vhosts include the subdirectories, which would have to be split into domain/path parts and updated in those 2 tables.

Honestly it doesn't seem to be that hard of a thing to do... Wordmove just needs to know that it's a multisite installation, and would need to split the vhost paths correctly (if necessary) and update those tables, in addition to the find and replace.

But, I'm not a ruby developer so maybe it's not as simple as it seems.

**Comment by barkleigh** [comment]
wordmove 3.2.2 multisite wp_blogs table domain column after pull has production domain instead of localhost domain. Would excluding the wp_blogs table be an option?

**Comment by kauaicreative** [comment]
https://github.com/welaika/wordmove/issues/45#issuecomment-1964605141
