### ISSUE TITLE
Issue push and pull database

### ISSUE THREAD

**Issue by arnoudebben** [welaika/wordmove#228]
Hi, i'm new to Wordmove and have an error I can't fix. Also can't find older threads with the right answer. 

This is the error i get: 

C:\wamp\www\Stageverslag>wordmove push --db

▬▬ V Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ V Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /Files/stagedocument/wp-content/dump.php
    local | download siturl/wp-content/dump.php?shared_key=06f6f7
464547f0e5b84f121969351ebbd7cd82ac56bc1ce3490dd85eab45dbf567a083376500c8b2 > C:/
wamp/www/Stageverslag/wp-content/remote-backup-1444565262.sql
C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:358:in `open_http': 404 Not Found (Open
URI::HTTPError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop
'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
deployer/base.rb:144:in `block in download'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:36:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:36:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
deployer/base.rb:143:in `download'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
deployer/ftp.rb:101:in `download_remote_db'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
deployer/ftp.rb:18:in `push_db'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
cli.rb:60:in `block in push'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
cli.rb:36:in `block in handle_options'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
cli.rb:34:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
cli.rb:34:in `handle_options'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/
cli.rb:59:in `push'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command
.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocat
ion.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:
in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb
:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/exe/wordmove:
6:in `<top (required)>'
        from C:/Ruby22-x64/bin/wordmove:23:in `load'
        from C:/Ruby22-x64/bin/wordmove:23:in `<main>'

**Comment by Ikaring** [comment]
I had a similar situation pull -d using FTP.

Error was like:
▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=wordpress --password=wordpress wordpress > /mysite/wordpress/wp-content/local-backup-1450237529.sql
   remote | write /mysite.com/wordpress/wp-content/dump.php
    local | download http://mysite.com/wp-content/dump.php?shared_key=6a6383c2540c0b913f1d00bfa38a11b5f578f7f10b5cf6303065cde1e4a10450195e9e1ecbfa86da > /var/www/wordpress/wordpress/wp-content/dump.sql
/usr/local/rbenv/versions/2.1.2/lib/ruby/2.1.0/open-uri.rb:353:in `open_http': 404 Not Found (OpenURI::HTTPError)

In my case, that was because 'vhost' and 'wordpress_path' in Movefile points to different directory.

My setting was like:
  vhost: "http://mysite.com"
  wordpress_path: "mysite.com/wordpress"

Instead, set them:
  vhost: "http://mysite.com/wordpress"
  wordpress_path: "mysite.com/wordpress"

That worked for me.

Though this changes option value of wp_home, you can set them in wp-config.php. 
define( 'WP_HOME', 'http://mysite.com' );
define( 'WP_SITEURL', 'http://mysite.com/wordpress' );

**Comment by pioneerskies** [comment]
Closing this because we think it is fixed in the current pre-release version and it will be in the next major release also.
