### ISSUE TITLE
LFTP doesn't sync folders

### ISSUE THREAD

**Issue by goeko** [welaika/wordmove#231]
If I lftp sync wordmove with param

```
wordmove pull --all
```

The first sync of coredata is correct after that wordmove don't find other pathes.
I must set every call expectly to sync my external folders.

```
wordmove pull -u
wordmove pull -t
wordmove pull -l
```

What's wrong.
I cannot debug that.

**Comment by Drumsk8** [comment]
Hello I am sorry I didn't see this ticket open before, but I've opened SFTP issue #250 I've also tracked down the issue and has a fix.

**Comment by pioneerskies** [comment]
AFAIHope, we're on the way to track down the issue

**Comment by jwktje** [comment]
I still have this issue. I'm running wordmove 2.0.0. 
Is this fixed?

**Comment by pioneerskies** [comment]
Hello, I don't know if you could belive, but we are out with a new version of Photocpier gem, and a relative new version of Wordmove, which could fix this bug.

@jwktje @Drumsk8 @goeko are you still interested in testing it?

    gem install wordmove

should update wordmove and photocopier :) Let me know

**Comment by pioneerskies** [comment]
Overall I'd like to thank @Drumsk8 for his contribution with in deep inspection and advice in #250 .

We fixed differently, but your notes were really significant to the goal ;)

**Comment by jwktje** [comment]
I switched all my 20+ websites to another host to get SSH, basically just to start using Wordmove in my projects. I'm loving this workflow. My need for FTP syncing was removed by this change.

One of my sites still is on a non-ssh host so I'll test it and report back if anything weird happens. Thanks for all the effort everybody. You guys rule

**Comment by pioneerskies** [comment]
I'm sorry to be late for you @jwktje ...
We'd like to thank you for your effort in reporting back for that scenario; it is as important as our maintenance work, really...

Looking forward to hear back from you

**Comment by jwktje** [comment]
No problem at all @pioneerskies . 
It was a nice way to learn site migration and everything went smoothly, so no harm done.
And my new host is way better so I kinda don't mind I had to bite the bullet.

And again, Wordmove is making my job so much easier and fun so thanks for all the work you do on this project!

**Comment by pioneerskies** [comment]
All my team who works on the tool behind the scenes ( @ramensoup @mukkoo @delphaber @namuit @AleOnRails ) will be certainly glad to hear that. Thanks for your support

**Comment by Drumsk8** [comment]
@pioneerskies  Thank you for the kind words and glad to have been of some help :) 👍
