### ISSUE TITLE
Issue when pulling database

### ISSUE THREAD

**Issue by sanderdewijs** [welaika/wordmove#232]
I'm having an issue when pulling the database to my local dev environment (running on DesktopServer from serverpress) on a Windows machine. When I use wordmove pull -e="production" -d I get the following error:

ERROR 1044 (42000): Access denied for user 'DB8ehts'@'localhost' to database 'e:/sites/www.localwebsite.dev/wp-content/dump.sql'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:136:in `run': Return code reports an error (Wordmove::ShellCommandError)
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:45:in`pull_db'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:49:in `block in pull'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in`block in handle_options'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in`handle_options'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:48:in `pull'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in`<top (required)>'
        from c:/Ruby200-x64/bin/wordmove:23:in `load'
        from c:/Ruby200-x64/bin/wordmove:23:in`<main>'

It looks like the database dump cannot be accessed by the local database user. The database user DB8ehts has all priveliges to perform any action on the local database.

**Comment by mukkoo** [comment]
We have just published a disclaimer about Windows Support https://github.com/welaika/wordmove/wiki/Windows-(un)support-disclaimer
GLHF
