### ISSUE TITLE
How to Edit MoveFile

### ISSUE THREAD

**Issue by WesternWeb** [welaika/wordmove#233]
Where is the Movefile and how do I edit it?

**Comment by Jeger** [comment]
You can create one with the command `wordmove init` as described in the readme under Usage.
The file is then edited with the texteditor of your choice.

**Comment by WesternWeb** [comment]
Thank you.  I figured out how to edit it but I am continually receiving errors and haven't been able to get it to work.  I'm sure that I'm not understanding something somewhere

**Comment by iDuuck** [comment]
Feel free to put the errors here so that we are able to help you out!

**Comment by mukkoo** [comment]
I'll close this issue. Feel free to reopen it if needed.
