### ISSUE TITLE
Mirror two localhost folders?

### ISSUE THREAD

**Issue by marklatham** [welaika/wordmove#235]
Can wordmove mirror a localhost wordpress installation to another folder on the same localhost? If so, how to set up in the Movefile?

BTW I've been using wordmove AOK between local and remote sites -- handy -- thanks!

**Comment by pioneerskies** [comment]
Sorry for the never answered question :(

#tofuturememory Wordmove can't do this; or better said: it could do this through an SSH connection against localhost and thus you should setup SSH server locally. It smells a lot as strategy :/
