### ISSUE TITLE
 MySQL server has gone away (RuntimeError)

### ISSUE THREAD

**Issue by rotexhawk** [welaika/wordmove#236]
I am not sure why I am getting this error. Everything seemed fine previously until I updated some of the packages on my linux server.  I can upload the files but can't seem to upload the database. 

< /serverURL/dump.sql
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:55:in `remote_run': Error code 1 returned by command (mysql -host .....) hidden for security reasons. But double checked everything and the credentials are right.

ERROR 2006 (HY000) at line 304: MySQL server has gone away (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:71:in `import_remote_dump'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:22:in `push_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

Here is what I have done. 
1. Checked syntax with Yaml Syntax Validator
2. Changed the userGroup on both the server and local machine 
3. Changed folder permissions on both environments 
4. Login to mysql manually to make sure it is active and working properly.

**Comment by iDuuck** [comment]
Wordmove is just showing you the error that it got from the server. After googling it seems that there is a too big packet or the server timed out.

> - Server timed out and closed the connection. To fix, check that “wait_timeout” mysql variable in your my.cnf configuration file is large enough.
> - Server dropped an incorrect or too large packet. If mysqld gets a packet that is too large or incorrect, it assumes that something has gone wrong with the client and closes the connection. To fix, you can increase the maximal packet size limit “max_allowed_packet” in my.cnf file, eg. set max_allowed_packet = 128M, then sudo /etc/init.d/mysql restart.
> 
> -- http://piwik.org/faq/troubleshooting/faq_183/

**Comment by rotexhawk** [comment]
Got it.. Thank you.
