### ISSUE TITLE
Add permalink flush after mysql-import?

### ISSUE THREAD

**Issue by der-lukas** [welaika/wordmove#239]
Hey!

I don't know if it's just in my installation, but after I push my local database, my links won't work on the remote-server, but they do after saving my permalink-structure in the backend (which is because it flushes the rewrite rules).

What do you think about adding `flush_rewrite_rules()`-function after database-import process was successful?

Cheers Lukas

**Comment by g33kidd** [comment]
Yes, having the same issue. Anytime I push to the server I need to update the permalink settings in order for pages to work properly.

**Comment by der-lukas** [comment]
But meanwhile I noticed that this issue is only the case when you do "wordmove push --all". 
When I only push the DB by using "wordmove push --db", it's not necessary to flush!

**Comment by g33kidd** [comment]
Hmm, yeah... oddly enough, that does seem to work 😀 I was previously using the "push --all" command.

**Comment by matjack1** [comment]
@der-lukas @g33kidd I've tried to reproduce your issue but unfortunately I cannot. I'm running wordmove 1.4.0.pre5, can you tell me what version are you using please?

**Comment by annidavenport** [comment]
I'm using 2.1.3 and having the same issue, when I use wordmove push --all I have to log in to the site and save the permalinks setting again otherwise all subpages throw a 500 error.

The homepage is fine, it's only sub pages

**Comment by pioneerskies** [comment]
@annidavenport Are you pushing a different `.htaccess` from local to production? What web server do you use locally?

**Comment by annidavenport** [comment]
@pioneerskies you may be onto something there, I added .htaccess to the excludes list in the Movefile and did a `wordmove push --all` and problem seems to be resolved.  This may help the others too, @der-lukas @g33kidd let us know.

Thanks!
