### ISSUE TITLE
Tables Prefix

### ISSUE THREAD

**Issue by colin-marshall** [welaika/wordmove#243]
Does the table prefix need to match between the different environments (local, staging, production, etc.)?

The reason I ask is because my staging site has a custom prefix, while my local site just has the regular `wp_` as the `$table_prefix`. When I pull database changes from staging to local the table prefixes are not changed.

I can fix this easily by making the prefixes the same, but I wanted to know if wordmove is supposed to handle the prefix change and for whatever reason it isn't happening for me?

**Comment by duongancol** [comment]
I got the same problem with table prefix. So I think wodmove doesn't support it.

**Comment by Jeger** [comment]
It is not currently supported.
See this discussion: #219

**Comment by colin-marshall** [comment]
Thanks!
