### ISSUE TITLE
Provide gzip as fallback when gunzip is unavailable

### ISSUE THREAD

**Issue by kevinwhoffman** [welaika/wordmove#244]
Thanks for all the work you put into Wordmove. I've got it up and running but wanted to share some feedback on database decompression.

Updating to 1.4.0 introduced an error related to the `gunzip` command. I am deploying to a shared hosting environment where `gunzip` is not available and the host is unwilling to activate it. I receive this error when pushing the database:

`bash: gunzip: command not found`

However I was able to decompress using `gzip -d dump.sql.gz`.

Is it possible to provide `gzip -d` as a fallback when `gunzip` is unavailable?

**Comment by pioneerskies** [comment]
This is fixed in dev branch: https://github.com/welaika/wordmove/pull/278/commits

Not published the gem yet, but it will soon.

FYI `gzip -d` is not the fallback, but the default now :)
