### ISSUE TITLE
Clean error if no Movefile is found

### ISSUE THREAD

**Issue by iDuuck** [welaika/wordmove#245]
At the moment there is a big error with a looooong trace. Would be nice if this would be fixed.

**Comment by mukkoo** [comment]
@iDuuck good idea. I add this feature to milestone.

**Comment by pioneerskies** [comment]
@iDuuck it is fixed in branch dev tnx to @xrmx

Not published yet but will be soon

Thank you.

**Comment by xrmx** [comment]
@pioneerskies Thanks for merging and for the pairing ;)
