### ISSUE TITLE
pull --db : empty dump.sql

### ISSUE THREAD

**Issue by adrienlamotte** [welaika/wordmove#247]
Hi !

I'm a new user of wordmove. That project looks great ! 
I spent the afternoon trying to make it work, but i'm stuck with a strange behavior... Can't figured out the problem so i'm looking for help ! :)

Here is what I have in the console : 
```
E:\Dropbox\Project\site>wordmove pull -e staging --db

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=root moynat --result-file=E:/Dropbox/Project/site/wp-content/local-backup-1448648492.sql
    local | mysqldump --host=localhost --user=root moynat --result-file=E:/Dropbox/Project/site/wp-content/local-backup-1448648492.sql
   remote | write /preprod/wp-content/dump.php
    local | download http://preprod.project.com/wp-content/dump.php?shared_key=0b7bc324680a2a9d334305e479066a071804b5d2d456f5bdbf60e707b8a338f70af19a4e646c83c9 > E:/Dropbox/Project/site/wp-content/dump.sql
   remote | delete: /preprod/wp-content/dump.php
    local | adapt dump
mysql --host=localhost --user=root --database=moynat --execute=SOURCE\ E:/Dropbox/Project/site/wp-content/dump.sql
    local | mysql --host=localhost --user=root --database=moynat --execute=SOURCE\ E:/Dropbox/Project/site/wp-content/dump.sql
ERROR 1049 (42000): Unknown database 'e:/dropbox/project/site/wp-content/dump.sql'
C:/DevTools/Ruby22/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:136:in `run': Return code reports an error (Wordmove::ShellCommandError)
```

The thing is : the file "dump.mysql" is created on my staging server and looks complete. But locally, the file dump.sql is created but is always empty...

Do someone has any idea of the problem ?

Thanks !

**Comment by adrienlamotte** [comment]
Update. I found that :
```
mysql --host=127.0.0.1 --user=root --database=moynat --execute=SOURCE\ E:/Dropbox/Project/site/wp-content/dump.sql
```
Is not working, returns : ERROR 1049 (42000): Unknown database 'e:/dropbox/project/site/wp-content/dump.sql'

But :
```
mysql --host=127.0.0.1 --user=root --database=moynat < E:/Dropbox/Project/site/wp-content/dump.sql
```
Works fine...

Any idea on how I could make it work ?

**Comment by adrienlamotte** [comment]
Anybody ? :)

**Comment by almemedia** [comment]
Hi, I also have the same issue. The dump is OK on the remote server (200 mb) but is not downloaded. The dump.sql file on my computer is empty. Any idea why?

**Comment by adrienlamotte** [comment]
Too bad Wordmove doesn't seems to be maintained anymore... ;-(

**Comment by mukkoo** [comment]
We have just published a disclaimer about Windows Support https://github.com/welaika/wordmove/wiki/Windows-(un)support-disclaimer
GLHF

**Comment by herbie4** [comment]
Try downgrade of Wordmove to version 1.2.0. This fixed it for me when using ftp.
#259

**Comment by adrienlamotte** [comment]
@herbie4 : Indeed ! I just downgraded to version 1.2.0 and it works (on Windows) ! Thank you.

**Comment by pioneerskies** [comment]
@herbie4 are you on Windows as well?

**Comment by pioneerskies** [comment]
Just as resume:

* we are talking about windows
* we are talking about this commit 76350e10c28ba0651f075bae1de7cde2a056d50a
* we are also talking about the PR #253

**Comment by herbie4** [comment]
@pioneerskies : Not windows, I am on osx.

**Comment by mukkoo** [comment]
As write on https://github.com/welaika/wordmove/issues/280 this problem is resolved. We'll release soon the 1.4.0 stable version.
