### ISSUE TITLE
SFTP issue

### ISSUE THREAD

**Issue by Drumsk8** [welaika/wordmove#250]
Firstly I would like to say thank you for making this project, no doubt it's of tremendous value to many.

I've currently come across some odd behaviour whilst using lftp. 

Pushing wordpress core -

Works fine.

Pushing Uploads -

The host connection path is being added as a path strangely at the end.

e.g.

open sftp://user:password@host://user:password@host;

Pushing Themes - 
again adds another path to end:

open sftp://user:password@host://user:password@host://user:password@host;

Pushing Plugins - 

and another path:

open sftp://user:password@host://user:password@host://user:password@host://user:password@host;

If I remove the additional path's each of the commands appears to run successfully. 

I am very new to ruby and I've taken a look at the files, but couldn't see or understand how this is being generated. Please could you help me understand this behaviour so that I can resolve the issue.

Kind regards,

**Comment by Drumsk8** [comment]
I've found that it's caused when stacking more options for things to do, i.e. push uploads and themes will cause themes to fail with the issue noted above. 

I might add that this system is working fine with SSH and rsync, just not with ftp. Looking about the files I've found that the general lftp command is being generated from lines 43 in the ftp.rb file. 

Strangely what I see happening is when a second option is added it will appear to re-run through  remote_ftp_url but skip/blank on the first line. 

def remote_ftp_url
      url = options[:scheme].presence || "ftp"
      url << "://"
      if options[:user].present?
        url << CGI.escape(options[:user])
        url << ":#{CGI.escape(options[:password])}" if options[:password].present?
        url << "@"
      end
      url << options[:host]
      url 
   end

**Comment by Drumsk8** [comment]
I found a solution to the issue that's being generated above, please could you update your code in photocopier which wordmove is utilising with the following amendment:
this is the photocopier/ftp.rb file
def remote_ftp_url
 url = ""
 url << options[:scheme].presence || "ftp"
 url << "://"
 if options[:user].present?
 url << CGI.escape(options[:user])
 url << ":#{CGI.escape(options[:password])}" if options[:password].present?
 url << "@"
 end
 url << options[:host]
 url 
 end

This resets anything that might of been called previous and appears to be working fine.

**Comment by pioneerskies** [comment]
This should be fixed as per updates on #231 with this commit https://github.com/welaika/photocopier/commit/65a564c1756c04efed9e3fa46ed6e80820746547

I'll close this: let's discuss on #231
