### ISSUE TITLE
Is Wordmove still in active development?

### ISSUE THREAD

**Issue by iDuuck** [welaika/wordmove#255]
So, the [commit history](https://github.com/welaika/wordmove/commits/master) states, that the development of wordmove isn't very active in the last time. If this project isn't in active development anymore I am forced to switch to another solution or write my own. Would be sad, because I think there were many work into wordmove.

But the feature I am missing most is **`.env` support**.

**Comment by g33kidd** [comment]
Looks like @pioneerskies merged a pull request recently, maybe it still is maintained? Just not regularly I guess. Though, I have been working on an Elixir implementation of basically the same idea, just as a practice for learning the language.

**Comment by simonmacfadyen** [comment]
Surely iDuuck is referring to already available features? you can define different environment variables really easily.

**Comment by iDuuck** [comment]
It's not that I want to adjust the vhost and wordpress_path of the production/staging environment, but for the local environment. For example if I am working on an Wordpress installation from two people.

So I would assume something like 
```
local:
  local: enviroment_vars.local
  wordpress_path: environment.wordpress_path
[...]
```

**Comment by mukkoo** [comment]
Hi @iDuuck I'll try to aswer to questions.
WordMove is still maintained, not frequently but maintained. We hope that developers community contributes to WordMove growth.
If you want an additional feature to WordMove about .env vars support you must to open a specific issue and/or make a pull request.
Reopen the issue if needed.
