### ISSUE TITLE
wordmove push -a and/or -w no working / -d is fine

### ISSUE THREAD

**Issue by webitekt** [welaika/wordmove#258]
Hi,

I successfully installed wordmove and also the Movefile.
Pushing the db is working.

trying to push the whole installation ends up with an error.
command: wordmove push -e staging -all OR wordmove push -e staging -a
ERROR: "wordmove push" was called with arguments ["-a"]

command: wordmove push -e staging -w
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:110:in `push_wordpress': undefined method `push' for "...":String (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'

I already updated gem.

Any hint is appreciated.

**Comment by mukkoo** [comment]
Hi @webitekt the flag -a or -all doesn't exists. You must to use --all flag.

The problem with `"...":String (NoMethodError)` seems is related to some syntax error(s) in your Movefile.
Default Movefile (generated with `wordmove init`) contains 

`staging: # multiple environments can be specified`
`  [...]`

I suggest you to check this and reopen the issue if needed.
