### ISSUE TITLE
dump.mysql left on server using FTP

### ISSUE THREAD

**Issue by herbie4** [welaika/wordmove#265]
Using ftp (wordmove 1.2.0) after a db pull I can see /wp-content/dump.mysql on the remote server is left behind. 
Isn't Wordmove supposed to remove this?

**Comment by pioneerskies** [comment]
Hi,

yes, it is supposed to do a cleanup after the transfer, afaik.

Anyway we can't test anything related to old Wordmove version. Please, update to the latest stable version (1.3.1 as writing) and update this issue accordingly to your new test.

Cheers

**Comment by herbie4** [comment]
@pioneerskies I can not update Wordmove to 1.3.1 because on ftp (on osx) the remote db will not get pulled in. Therefore I downgraded to 1.2.0 and it worked just have this issue with the file being left behind. Not to important, just easier if it would work.

**Comment by mukkoo** [comment]
As write on https://github.com/welaika/wordmove/issues/280 this problem is resolved. We'll release soon the 1.4.0 stable version.
