### ISSUE TITLE
MU plugins support has disappeared with version 1.4.0.pre5

### ISSUE THREAD

**Issue by schlessera** [welaika/wordmove#269]
MU plugins support is gone with version 1.4.0.pre5. When I switch back to version 1.4.0.pre4, it is there again.

**Comment by pioneerskies** [comment]
I've found another functionality disappeared...I'm investigating with a colleague and probably I've a clue

**Comment by pioneerskies** [comment]
@schlessera 1.4.0.pre6 is available and should fix these kind of problems.
I'm really really sorry, but the last commits were on the master and someone of the dev team accidentally  tagged and pushed the master branch as a pre-release.

I hope to have solved the situation. Let me know something and please close the issue if it looks good to you.

Thanks again for reporting

**Comment by pioneerskies** [comment]
Hey @schlessera I'll close this one, but feel free to reopen and comment if you need.

Cheers

**Comment by schlessera** [comment]
@pioneerskies Thanks for the heads-up. Sorry I haven't responded yet, still haven't found the time to test the new version.
I'll let you know if I hit another issue.
Cheers!
