### ISSUE TITLE
"Object#timeout is deprecated, use Timeout.timeout" with Ruby 2.3.0

### ISSUE THREAD

**Issue by mojenmojen** [welaika/wordmove#270]
The message "Object#timeout is deprecated, use Timeout.timeout" is displayed during the remote mysqldump with Ruby 2.3.0, wordmove 1.3.1.

/Users/mojen/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.

/Users/mojen/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.

**Comment by pioneerskies** [comment]
I don't know how to label this one, since is "just" a deprecation warnign; so I'll go with the bug.

Thanks for filling the issue

**Comment by StefanoOrdine** [comment]
https://github.com/net-ssh/net-ssh/issues/305 the issue is currently opened in net-ssh repo.

**Comment by pioneerskies** [comment]
The comment in the linked thread was right: with net-ssh 3.0.2 the warning is fixed.
I've updated photocopier gem and wordmove--pre in order to use the new version.
