### ISSUE TITLE
Database Backup on push

### ISSUE THREAD

**Issue by namuit** [welaika/wordmove#28]
It can be a useful feature a new cli option that offer a copy of the dump of the database before the push of it.
The problem is pretty simple: the files are often in a repo or in a compressed file somewhere (email, dropbox, filesystem, etc.), so if you made an error, you can revert everything, but if there are errors on the database, you can't.

It can be nice a new option that doesn't delete the dump of the database (and set it a new name like YYYYMMDDHHMMSS.sql in a htaccess protected folder) or save it in a dump.

**Comment by morrislaptop** [comment]
Should this be re-opened?

**Comment by pioneerskies** [comment]
Why are you saying that @morrislaptop ? Both remote and local dump should be found in wp-content/ after every db push/pull operations

**Comment by morrislaptop** [comment]
Ah I was looking on the server for the backup when pushing.

**Comment by pioneerskies** [comment]
Oh no, they are all saved locally for security reasons :)
