### ISSUE TITLE
FTP problems with 1.3.1

### ISSUE THREAD

**Issue by mukkoo** [welaika/wordmove#280]
The differences between 1.2.0 and 1.3.1 that broken FTP db pull support are in dump.php.erb file.
https://github.com/welaika/wordmove/compare/v1.2.0...v1.3.1

Please check.

This is updated repo https://github.com/dg/MySQL-dump

Related issues  
https://github.com/welaika/wordmove/issues/265
https://github.com/welaika/wordmove/issues/221
https://github.com/welaika/wordmove/issues/247

**Comment by mukkoo** [comment]
This problem is fixed in 1.4.0 versione

**Comment by pioneerskies** [comment]
can't see any commit nor pr...

**Comment by mukkoo** [comment]
No PR because is already fixed in 1.4.0

**Comment by pioneerskies** [comment]
ok, tnx; so it's just a matter of releasing. Cool. Re-closing
