### ISSUE TITLE
only pull database not working

### ISSUE THREAD

**Issue by webitekt** [welaika/wordmove#288]
I have setup wordmove and pulling/pushing  the files works fine.
OS X: 10.11.3
Ruby version: 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
wordmove: 1.3.1

So the ssh connection is working, Movefile is ok.

Entering `wordmove pull -d`
ends up with:

```
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:183:in `start': invalid option(s): IdentityFile (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/photocopier-1.0.0/lib/photocopier/ssh.rb:70:in `session'
    from /Library/Ruby/Gems/2.0.0/gems/photocopier-1.0.0/lib/photocopier/ssh.rb:43:in `exec!'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:50:in `remote_run'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:58:in `download_remote_db'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:30:in `pull_db'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:49:in `block in pull'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:48:in `pull'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
    from /usr/local/bin/wordmove:23:in `load'
    from /usr/local/bin/wordmove:23:in `<main>'
```

The local dump was done and is stored in wp-content.
The remote dump isn't done. Executing the mysqldump manually on the remote comand line also works.
Any hint where to investigate?

Thanks.

**Comment by pioneerskies** [comment]
Hi @webitekt ,

thanks for enquire after the issue. Can I ask you to re-lift a bit your post following [these tips](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting)?

Thanks in advance

**Comment by pioneerskies** [comment]
Apart of that: have you got entries in `~/.ssh/config` about the host you're reaching?

**Comment by webitekt** [comment]
@pioneerskies thanks for your reply - lifted it up, pls let me know if something's missing
I have entries in the ~/.ssh/config for this host.

**Comment by pioneerskies** [comment]
1) I have no idea why there should be differences between ssh connections when pushing files and when pushing db...
2) Would you try to comment ssh/config's entries, adapt the `Movefile` accordingly and try again?
3) You said you have entrie**s** ... you have multiple entries for a single host? It sounds strange to me

**Comment by pioneerskies** [comment]
No follow up. Closing :)
