### ISSUE TITLE
MySQL 5.5/5.6 push pull

### ISSUE THREAD

**Issue by kLOsk** [welaika/wordmove#289]
So, one of my clients is running Siteground and they started moving all their databases to 5.6 which broke my push pull capabilities with Mamp as it's still running 5.5. I have other clients who also still run 5.5.

It's not really a question for WordMove but i believe it affects you equally. How do you handle these issues at the moment? I am thinking about upgrading my MAMP MySQL server to 5.6, hoping that the mysqldump 5.6 client tool is capable to import the data into 5.5 servers. From my understanding WordPress does not create any incompatible table structures, so the dump should work?

**Comment by pioneerskies** [comment]
In which way it broke pus/pull?

**Comment by kLOsk** [comment]
I tried to push it from 5.5 to a 5.6 server. The following error occured:

` mysqldump: Couldn't execute 'SET OPTION SQL_QUOTE_SHOW_CREATE=1': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OPTION SQL_QUOTE_SHOW_CREATE=1' at line 1 (1064) (Wordmove::ShellCommandError)
`

The good news now is that I updated my local dev environment to 5.6 and have successfully synced 5.5 databases. So, unless wordpress uses some special 5.6 table schema features it seems to be not a problem to run 5.6 and sync with 5.5 db's!

**Comment by pioneerskies** [comment]
No it should not be a problem AFAIK: with 5.6 I've never had troubles working with older versions (as I had with 5.7 instead).

If you'd need dev/prod perferct alignment something like Vagrant/VVV - in our wiki there are some info about it - or similar.

As you clearly stated, this is not a Wordmove issue, but we left the issue open and see if someone around has some tricks for you :)

Cheers

**Comment by kLOsk** [comment]
I think so far so good.

I also opened a ticket at serverfault (http://serverfault.com/questions/759916/import-mysql-5-6-database-into-5-5-using-mysql-5-6-client-tools/)  and someone made a recommendation to change some part of the mysqldump app so it would also work with clienttools 5.5, tho I haven't tried that. Just in case someone stumbles over this.

**Comment by jmichaelward** [comment]
Just an FYI, I've encountered this same issue when trying to execute a `wordmove pull -d` from a SiteGround host into MAMP Pro. Upgrading MySQL in MAMP to 5.6 didn't resolve it. I'm still getting the error "Couldn't execute 'SET OPTION SQL_QUOTE_SHOW_CREATE=1'".

**Comment by kLOsk** [comment]
Thats interesting, have you double checked and ensured that mysqldump (mysqltools) are indeed updated to 5.6? Note that in OSX you have to set the profile PATH to the MAMP provided MySQL Tools by hand!

Put in your .profile:
export PATH="$PATH:/Applications/MAMP/Library/bin"

**Comment by jmichaelward** [comment]
Hey @kLOsk, thanks for your reply. I do indeed have MAMP in my path, as I discovered early on when working with Wordmove that this was necessary to transfer any data on the occasion when I'm developing using MAMP.

In working with the tool yesterday, it looks like the failure happens when mysqldump is called against the remote server. Mysqldump throws "error code 2" when called from the remote_run of the Deployer module in Wordmove. I misspoke yesterday - logging into SiteGround now, it appears that SiteGround *IS* running MySQL 5.5.32, so I'm not sure where the discrepancy is. 

It's likely that this isn't a direct issue with Wordmove itself, but rather a configuration issue where certain requirements are not present. Of course, it's not clear from the Wordmove documentation exactly what those requirements are, and the error messages that are thrown when something arises can be difficult to decipher. Would it be possible to update the Wordmove documentation to indicate local and remote system requirements for using Wordmove? I'd be happy to help with this in any way that I can.

Thanks.

**Comment by kLOsk** [comment]
Mhm, I also had the issues with SiteGround and SiteGround confirmed to me that they are going to upgrade all customer databases to 5.6! Thus sooner or later it will be 5.6.

I have successfully synced WP MySQL 5.5 and 5.6 servers with my local environment (now MAMP with 5.6). 5.6 is only incompatible with 5.5 when the new features are used. However, WP as of now does not use any of these features, thus it should definitely be possible to have mixed versions of MySQL on staging, production and dev environment.

Since all the commands are initiated remotely (from your Mac), I believe your problem lies within the local mysqltools.

Can you issue this command from the Mac Command Line:

`mysqldump --help | grep Distrib`

Result should be:

`mysqldump  Ver 10.13 Distrib 5.6.25, for osx10.6 (x86_64)`

In order to check Sitegrounds MySQL version I think it's best to go into PHPMyAdmin. It will show the MySQL version after login.

**Comment by jmichaelward** [comment]
Hey Daniel,

Sorry for the late response. I ran the mysqldump command you provided in
the terminal, and the result was identical to what you indicated. I then
SSH'd into the SiteGround host, and ran the same command, and that version
is a lower version: `Ver 14.14 Distrib 5.5.32, for Linux (x86_64) using
readline 5.1`.

Trying to execute `wordmove pull -e staging -d` command returns the
mysqldump error on the remote call (where the server's database credentials
are passed), so I suspect it has something to do with SiteGrounds
installation of MySQL, and not my local machine.

Again, I'm not sure that this is an issue with Wordmove at all, unless the
script doesn't have a fallback for the case where the desired MySQL command
isn't available.

Jeremy Ward
(612) 465-9769
jmichaelward.com

**Comment by pioneerskies** [comment]
Aged. Closing until more help's needed. Sorry.
