### ISSUE TITLE
Link to sshpass's brew recipe should be updated

### ISSUE THREAD

**Issue by delphaber** [welaika/wordmove#290]
The recipe is outdated.

```
↳ $ brew install https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb
######################################################################## 100,0%
==> Downloading http://sourceforge.net/projects/sshpass/files/sshpass/1.05/sshpass-1.05.tar.gz
==> Downloading from http://netassist.dl.sourceforge.net/project/sshpass/sshpass/1.05/sshpass-1.05.tar.gz
######################################################################## 100,0%
Error: MD5 support has been dropped for security reasons.
Please switch this formula to SHA256.
```

**Comment by pioneerskies** [comment]
From the readme

> writing the password inside the move file was and is somewhat supported, but we discourage this practice in favor of password-less authentication with pub key. Read here for old informations.

I'm for an opinionated approach: insert the password at prompt or use pubkey auth. Using `sshpass` is somewhat considered a bad practice and overall it is a feature for laziness.
