### ISSUE TITLE
rsync: Failed to exec sshpass: No such file or directory (2)

### ISSUE THREAD

**Issue by wbuist** [welaika/wordmove#292]
I'm getting this error with either my remote production or remote staging sites. 

For the absolute URL's for both local and remote I've been onto Terminal/SSH navigated to the folder and used 'pwd' and then pasted that into the movefile, for both local and remote.

Just can't seem to get a valid connection and, of course, every stage of the move fails with the same error.

**Comment by wbuist** [comment]
This was fixed - It took a bit of fiddling with wordmove configuration, but caused by my lack of knowledge. ;-)

**Comment by pioneerskies** [comment]
Hi @wbuist . We have a lot of new documentation in the wiki.
Feel free to improve it if you think it's needed. :)

**Comment by multiplier** [comment]
How exactly did you resolve this?

**Comment by eivindml** [comment]
I had this and solved it by commenting out the password for my ssh configutation in the Movefile. After I did this, when I ran my command it asked for my password, and everything worked.

**Comment by s-matzd** [comment]
I had the same error and solved it by installing sshpass.

**Comment by 2leafchris** [comment]
I had the same error. Here is the output:
```
▬▬ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pushing wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: [secret] [secret] /wp-content/* .git/ .gitignore .gitmodules .env node_modules/ bin/ tmp/* Gemfile* Movefile movefile movefile.yml movefile.yaml wp-config.php wp-content/*.sql.gz *.orig wp-content/uploads/backwpup*/* .htaccess .idea/ wp-content/* /* /wp-content/uploads/ /wp-content/

    ℹ️  info | rsync --progress -e 'sshpass -p [secret] ssh -p 2200 chris@[secret]' -rlpt --compress --omit-dir-times --delete --verbose --inclu
de /wp-content/uploads/ --include /wp-content/ --exclude /wp-content/\* --exclude .git/ --exclude .gitignore --exclude .gitmodules --exclude .env --exclude node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude movefile --exclude movefile.yml --exclude movefile.yaml --exclude wp-config.php --exclude wp-content/\*.sql.gz --exclude \*.orig --exclude wp-content/uploads/backwpup\*/\* --exclude .htaccess --exclude .idea/ --exclude wp-content/\* --exclude /\* [secret] :[secret]
rsync: [sender] Failed to exec sshpass: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.2.3]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at io.c(228) [sender=3.2.3]
```

I am able to solve it by doing what @eivindml suggested, but then the password needs to be entered manually 7 times between commands. Not the best solution.

I was able to fix also by what @s-matzd suggested and installed sshpass on the container:

`docker exec -it wordmove_container /bin/bash`

Then:
`apt update && apt install sshpass`

Commenting these additional details here so hopefully it helps save others some time (I got here from Google multiple times in my quest to solve; think we all probably followed the same incomplete guide on getting this working in Docker).

**Comment by alessandro-fazzi** [comment]
@2leafchris I know I'm arriving 2 months later, but I'd like to underline: I discourage using `sshpass`. Everyone should use ssh keys instead to authenticate against remote servers.

Here https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained#ssh is documented that the `password` key is deprecated.

Removing the `ssh.password` key from `movefile.ym` should automatically stop Wordmove from trying using it.

From there on, the Wordmove's docker image will help you use your ssh keys mounting theme as described in https://github.com/welaika/docker-wordmove#ssh-permission-caveat.

More over in https://github.com/welaika/docker-wordmove#notable-changes you'll find

> - `sshpass` has been removed. It's use is discouraged and deprecated by Wordmove, so it is in this container. We warmly recommend to use safer approaches

Regards
