### ISSUE TITLE
Request the ability to change the mysql prefix between the dev and production sites

### ISSUE THREAD

**Issue by dierkp** [welaika/wordmove#295]
Can we have a feature that would allow for the MySQL prefix  "wp_" on the developer site be changed to "wp_34tu_" on the live site for increased security.

Where would you add fork the code and fix that..

**Comment by pioneerskies** [comment]
We already have a branch with partial work on this feature. But it never reached the master branch and it does not cover all the specs. Please, refer to the original issue and to the branch if you'd like to continue discussion or try to go for a PR: https://github.com/welaika/wordmove/issues/219
