### ISSUE TITLE
Request the ability to have the DB migration turn off all the production plugin with a boolean flag.

### ISSUE THREAD

**Issue by dierkp** [welaika/wordmove#296]
I would like to be able to migrate the DB back from production to local development but have stuff like BackWPup, JetPack, YoastSEO all get turned off.

So we might as well turn off all the Plugins with a boolean flag during DB migration.

**Comment by pioneerskies** [comment]
Hey @dierkp would you like to elaborate a bit more in the specs, please? I can't get the whole scenario and moreover what you'd like to do when re-pushing to prod after dev work.

Thanks in advance

**Comment by kevinwhoffman** [comment]
Might be some crossover here with #302.

**Comment by pioneerskies** [comment]
Aged. Closing.
