### ISSUE TITLE
Path is not replaced

### ISSUE THREAD

**Issue by flegfleg** [welaika/wordmove#297]
Hello, thanks for this great script. 
Pushing of the DB works fine, however, the wordpress paths in the Database are not replaced (e.g. http://localhost/ -> http://www.online). Am i missing something? 

I am using: 
`wordmove push -d`

**Comment by pioneerskies** [comment]
Try removing the trailing slash from `http://localhost/` from the `Movefile`

**Comment by flegfleg** [comment]
Thanks @pioneerskies !

**Comment by pioneerskies** [comment]
You're welcome :)
