### ISSUE TITLE
**** SSL_connect: dh key too small

### ISSUE THREAD

**Issue by Malamutt** [welaika/wordmove#298]
Anyone see this issue with using lftp ftps to box.com?

**Comment by narookak** [comment]
You will need to compile lftp with GnuTLS. 
To verify run "lftp -v" and it should list GnuTLS in output like below..

Libraries used: Readline 6.3, GnuTLS 3.3.17, libiconv 1.14, zlib 1.2.8

**Comment by bwithem** [comment]
On OSX/homebrew:

`brew edit lftp`
Replace openssl dependancy with `depends_on "gnutls"`
Replace --with-openssl with `"--with-libgnutls-prefix=#{Formula["gnutls"].opt_prefix}"`
`brew install lftp`
