### ISSUE TITLE
Ability to ignore database options during migration

### ISSUE THREAD

**Issue by kevinwhoffman** [welaika/wordmove#302]
The ability to ignore certain options when migrating the database would solve a couple of headaches that I currently have to deal with manually after each migration. Specifically I'm looking for the ability to ignore:
- wp_options > active_plugins (controls which plugins are currently active)
- wp_options > blog_public (controls whether search engines can see your site)

The WP Migrate DB Pro plugin has a feature where you can choose to ignore these options when migrating the database, which means your dev plugins are not activated in production and production plugins are not activated in dev. Similarly you can have search engines blocked in your staging environment but not in production.

Since Wordmove does not currently have this ability, I am constantly toggling plugin activations and site visibility after database migrations.

A boolean flag in the Movefile would be sufficient to turn this option on or off. Looking forward to hearing your thoughts.

**Comment by istiu** [comment]
I have the same problem. Is there any way to solve that?

**Comment by pioneerskies** [comment]
Wordmove has no idea at all about the database structure ^_^'''
So the community here would need some specs about the feasible implementation.

Would it be enough to ignore the `options` table during the dump? You can try to afford this by configuring

    local.database.mysqldump_options: --ignore-table=prefix_options
    staging.database.mysqldump_options: --ignore-table=prefix_options 

in the Movefile. But i really don't know if this is desirable.

**Comment by kevinwhoffman** [comment]
@pioneerskies Completely ignoring the `options` table would not be a good idea as that table houses other data that should be kept in sync between environments. I was hoping to leave specific rows within the `options` table untouched while syncing the rest of the database.

This would require retrieving the `option_value`, storing it, overwriting the database, and then adding the `option_value` back in at the end of the process.

**Comment by phidodido** [comment]
Maybe we could have some options?

`mysqldump_options: --blog_public=0 --disable_plugins=jetpack,wordfence`

To disable plugins see https://wordpress.stackexchange.com/questions/45109/how-to-make-sense-of-the-active-plugins-option-value-to-enable-and-disable-certa

**Comment by pioneerskies** [comment]
@phidodido @kevinwhoffman , just to make a bit of conversation...

I think I'd accomplish your tasks doing something like this with `wp-cli`:

```bash
⟩ wp @staging plugin status                                                 [ruby 2.4.1]
14 installed plugins:
  A advanced-custom-fields-component_field 1.0.10
 UA advanced-custom-fields-pro             5.5.11
  A duplicate-post                         3.2
  A flow-flow                              2.10.15
  A formidable                             2.03.07
  A formidable-wpml                        1.04
  A iubenda-cookie-law-solution            1.14.2
 UA wordless                               2.0.0beta4
  A wordless-extender                      1.2.0
  A wpml-media-translation                 2.2.0
  A sitepress-multilingual-cms             3.7.0
  A wpml-string-translation                2.5.3
  A wpml-translation-management            2.3.0
  A wordpress-seo-premium                  4.7.1

Legend: A = Active, U = Update Available
```

and so

```bash
⟩ wp @staging option get blog_public                                        [ruby 2.4.1]
1
```

and so

```bash
⟩ wp @staging plugin activate wordless                                      [ruby 2.4.1]
Warning: Plugin 'wordless' is already active.
Success: Plugin already activated.
```

Obviously `@stagin` is an alias configured inside `wp-cli.yml` in project's root as per [wp-cli docs](https://make.wordpress.org/cli/handbook/config/#config-files)

And obviously you need to have wp-cli on the remote host - if you do not, go fix it!

Reactions? Thoughts? Nuggets? :)

**Comment by phidodido** [comment]
It's good to know there is another solution besides using the WordPress GUI.

The only thing is that I tend to forget to turn plugins on/off after pushing so it would be nice if WordMove could do it.

**Comment by pioneerskies** [comment]
#142

**Comment by pioneerskies** [comment]
@phidodido @kevinwhoffman you should take a look to the new hooks feature. If you have an hosting with `wp-cli` installed, you will be able to update (not ignoring though) remote wp_options easily.

Open new issue if you need help or found a bug.

Cheers
