### ISSUE TITLE
Sync down of remote db fails

### ISSUE THREAD

**Issue by zuzust** [welaika/wordmove#304]
Sync'ing down the remote db via `ftp` fails. Below the contents of downloaded `wp-content/dump.sql`:

```
<br />
<b>Warning</b>:  fopen(dump.mysql): failed to open stream: Permission denied in <b>/home/vhosts/users/confavc.cat/webdocs/home/carles/Projectes/wp/confavc.cat/web/wp-content/dump.php</b> on line <b>60</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'ERROR: Cannot write file 'dump.mysql'.' in /home/vhosts/users/confavc.cat/webdocs/home/carles/Projectes/wp/confavc.cat/web/wp-content/dump.php:62
Stack trace:
#0 /home/vhosts/users/confavc.cat/webdocs/home/carles/Projectes/wp/confavc.cat/web/wp-content/dump.php(229): MySQLDump-&gt;save('dump.mysql')
#1 {main}
  thrown in <b>/home/vhosts/users/confavc.cat/webdocs/home/carles/Projectes/wp/confavc.cat/web/wp-content/dump.php</b> on line <b>62</b><br />

```

where

```
local:
  vhost: "http://local.confavc.cat"
  wordpress_path: "/home/carles/Projectes/wp/confavc.cat/web" # use an absolute path here

```

**Comment by mukkoo** [comment]
@zuzust which version of WordMove are you using? It seems a write permission (on your local env) error.

**Comment by zuzust** [comment]
I use `wordmove 2.0.0`, but I think it is related to a bad path issue. That path does not exist in my local env. It seems a concat of remote and local absolute wordpress paths.

**Comment by three60five** [comment]
I am also having this issue where the remote path and local path are combined when using ftp to pull down the db. I am using wordmove 2.0.0.

**Comment by pioneerskies** [comment]
Please try to follow these instructions https://github.com/welaika/wordmove#ftp and report if they someway helped.
