### ISSUE TITLE
Slack/Gitter Channel

### ISSUE THREAD

**Issue by kLOsk** [welaika/wordmove#306]
Hi,
I was wondering if there is a Slack or Gitter channel available to discuss wordmove and other wordpress stack tools? I'm maintaining a script called WPStager which makes use of WordMove. I thinks there quite a few tidbits that could be discussed to improve deployment and management of a WP stack which isn't VVV...

**Comment by dsgnr** [comment]
i'd like to do this too. my username is @danielhand

**Comment by eivindml** [comment]
Would like this too! :)

**Comment by pioneerskies** [comment]
Hey, my incredibly big fault here to have never noticed this proposal.
Well... @kLOsk if it is really better late than never, your idea sounds good.

Would you still like to set it up? I'd probably prefer a Slack channel

**Comment by kLOsk** [comment]
Sure, why not! I'll set one up in the next days! Will let you guys know!

**Comment by kLOsk** [comment]
Had 5 minutes. Feel free to join here: https://wp-hub.slack.com

**Comment by pioneerskies** [comment]
@kLOsk mailed you. I'll setup the auto invite as soon as I'll be in the slack channel - need api token.

**Comment by kLOsk** [comment]
Thanks @pioneerskies. Just sent out the invite! Once you in I'll set you up as an admin!

**Comment by kLOsk** [comment]
by the way, there are other implementations for an invite script out there as well. http://bfy.tw/8BNK

**Comment by pioneerskies** [comment]
Good. We have just to test the invitation: too much automagic here...I can't trust it blindly! :P

@dsgnr @eivindml @delphaber would you like to test it? :)

**Comment by pioneerskies** [comment]
Oh wait...I'm sure it isn't working as expected. I'll do a bit of debug

**Comment by pioneerskies** [comment]
Ok, tests can be done from now on 👍

**Comment by eivindml** [comment]
@pioneerskies Works perfectly! 🍻

**Comment by pioneerskies** [comment]
Updated the readme with a badge to the slack community.

Cheers
