### ISSUE TITLE
Not syncing all Uploads

### ISSUE THREAD

**Issue by minthemiddle** [welaika/wordmove#308]
When I try to pull all changed uploads from my production env using `wordmove pull -u` I do not get all files that are in the production's upload folder. Neither of the files are in the exclude section in the `Movefile`. Also I did not get any output that would include the filenames in question. I added `rsync_options: "--verbose"` but that did give any further information about the skipped files either.

Any ideas about causes and solutions?

**Comment by pioneerskies** [comment]
What is the folder structure of your wp-content/uploads? Has it anything unusual? Can you also paste the exclude section of the Movefile?

**Comment by minthemiddle** [comment]
I solved it. I was looking at the wrong end. Local permissions were the problem, there was a missing writing right in parts of the folder.
