### ISSUE TITLE
add support for mulidimensional serialised arrays in database

### ISSUE THREAD

**Issue by herbie4** [welaika/wordmove#309]
Most plug-ins use single serialised arrays in the database. Now ran into an issue where a plug-in is using multidimensional serialised array. After push_db or pull_db now the plug-in is not working because the count on the main array has not been updated. 

Is there a way to get Wordmove to play nice with mulidimensional serialised arrays in the database?

**Comment by pioneerskies** [comment]
Got the goal implementing the new `sql_adapter: 'wpcli'` :) Closing
