### ISSUE TITLE
Can't customize ssh key location

### ISSUE THREAD

**Issue by intergrip** [welaika/wordmove#311]
Hello,

It seems that I'm not able to add the location of my SSH key in the Movefile.
As I have multiple webservers, and multiple SSH key's for these servers at my computer, I need to be able to specify the correct one.
Anyone any thoughts?

**Comment by intergrip** [comment]
Nevermind, I hacked it in by doing:
host: "example.com -i /path/to/ssh/file"

**Comment by intergrip** [comment]
In the end this actually didn't work. It failed when the database was being synced.
Anyone thoughts?

**Comment by pioneerskies** [comment]
Yep! You should use you `~/.ssh/config` to configure specific keys associated w/ specific hosts :)
