### ISSUE TITLE
Pulling or pushing all files not working properly

### ISSUE THREAD

**Issue by dsgnr** [welaika/wordmove#315]
I've been getting a strange issue where not all files are being transferred when pulling/pushing all. This is mainly with theme and plugin files. I find a manual theme/plugin push or pull does the trick but strange it doesn't do It all the time with -all. 

Could this be a setting in the ssh options of the Wordmove file?

**Comment by pioneerskies** [comment]
Pls @dsgnr drop us some more info as per https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting wiki entry.

Also an example of what is not being transferred by `--all` would be helpful.

Thanks in advance
