### ISSUE TITLE
first push

### ISSUE THREAD

**Issue by qiem** [welaika/wordmove#318]
Hello 

i was looking for developement tool and found wordmove. 
after succeeding in installing etc in de terminal i have the following error and do not know whatwent wrong. I reinstalled everything but it did not solve this error. Please help, because i would really like to use Wordmove. Thx

``` bash
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/Users/albertinosilva1/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 24 column 3 (Psych::SyntaxError)
    from /Users/albertinosilva1/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
    from /Users/albertinosilva1/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:325:in `parse'
    from /Users/albertinosilva1/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:252:in `load'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:42:in `fetch_movefile'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:10:in `deployer_for'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:80:in `push'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/bin/wordmove:23:in `load'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/bin/wordmove:23:in `<main>'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/albertinosilva1/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pioneerskies** [comment]
Please help us understand your problem following these [recommendations about bug reporting](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting)

**Comment by ertay** [comment]
I am getting the same error:

vagrant@vvv:/srv/www/mysite/htdocs$ wordmove push -t -e staging

▬▬ ✓ Using Movefile: ./Movefile~ ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:22:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:80:in `push'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/wordmove:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/wordmove:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

I installed wordmove in my vagrant vvv box. I'm using Wordmove 2.0.0, ruby 2.3.0p0, gem 2.5.1. I double checked my Movefile but didn't see any errors, can the above be because of errors in the Movefile?
