### ISSUE TITLE
Wordmove symlinks

### ISSUE THREAD

**Issue by chrilleferna** [welaika/wordmove#319]
On my development machine I use symbolic links from the plugin directory to several plugins I have developed (plugins under development that are shared across several WP sites also under development). When using Wordmove, these symbolic links are copied as links to the staging/production sites, where they all become dangling. When using FTP eg with Filezilla the symlinks are dereferenced and the linked directories and files are copied over. It would be really nice if you would add an option for Wordmove to do the same.

**Comment by pioneerskies** [comment]
Are you deploying over FTP?

**Comment by pioneerskies** [comment]
If that's the scenario try configuring `lftp` this way

    echo 'set mirror:dereference true' >> ~/.lftprc

and re-test launching `wordmove`'s command

**Comment by chrilleferna** [comment]
Hi Alessandro,
I'm using ssh, but your answer put me on the right track also for ssh. I set the rsync option in the Movefile:
`rsync_options: "-L"`
Works perfectly. Thanks!

**Comment by pioneerskies** [comment]
Lovely.

We are really lucky to have great tools like `rsync` and `lftp` under the cover, because they have almost all the desired features 👯 

Bye :)
