### ISSUE TITLE
rsync write error

### ISSUE THREAD

**Issue by ertay** [welaika/wordmove#321]
I'm getting the following errors when I try to push to my server:

rsync: [sender] write error: Broken pipe (32)
rsync error: error in file IO (code 11) at io.c(837) [sender=3.1.0]

On the server, my hosting provider have installed rsync 3.0.9. I have installed wordmove in my vagrant vvv box. The versions are, wordmove 2.0.0, ruby 2.3.0p0.

For reference here is the full output after pushing:

vagrant@vvv:/srv/www/mysite/htdocs$ wordmove push -t -e production

▬▬ ✓ Using Movefile: ./Movefile~ ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing Themes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /srv/www/mysite/htdocs/wp-content/themes /public_html/wp/wp-content/themes .git/ .gitignore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql
I, [2016-06-15T20:01:46.351119 #10416]  INFO -- : rsync --progress -e 'ssh user@myhost.com' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --exclude wp-content/\*.sql /srv/www/mysite/htdocs/wp-content/themes/ :/public_html/wp/wp-content/themes
/usr/local/rvm/gems/ruby-2.3.0/gems/photocopier-1.1.1/lib/photocopier/adapter.rb:31: warning: Insecure world writable dir /usr/local/rvm/gems/ruby-2.3.0/bin in PATH, mode 042777
stdin: is not a tty
sending incremental file list
rsync: [sender] write error: Broken pipe (32)
rsync error: error in file IO (code 11) at io.c(837) [sender=3.1.0]

**Comment by ertay** [comment]
Apparently the issues were caused by the shared host.

**Comment by ryanfurtner** [comment]
I am getting this error trying to push to my VPS with new wordpress install I just set up. I can push from another wordpress site to the same VPS, but not this one. Any ideas?

**Comment by pioneerskies** [comment]
Can't understand what "I can push from another wordpress site to the same VPS, but not this one" means...perhaps could be better to start a new issue explaining a bit more a round the scenario?
