### ISSUE TITLE
pushing database on php7 (without mySQL extension)

### ISSUE THREAD

**Issue by flurinduerst** [welaika/wordmove#324]
I can push/pull databases no problem when running php 5.6.22. 
When I switch to php 7 the `mysql` extension is disabled. `mysqli` and `mysqlnd` is enabled on both version. When trying to push/pull a database on this setting, it doesn't work, altough I do not receive an error in the console. The logfile says "There is no mySQL extension availible in your PHP installation.

phpinfo() @ php 5.6.22
![image](https://cloud.githubusercontent.com/assets/9006167/16295375/d5900886-3926-11e6-8232-68dc41a322e8.png)

logilfe after trying to push db @ php7
![image](https://cloud.githubusercontent.com/assets/9006167/16295432/3244f776-3927-11e6-9770-6bf73c4fa9f7.png)

console output after trying to push db @ php7

```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /www/domain.com/wp-content/dump.php
    local | download http://domain.com/wp-content/dump.php?shared_key=61825138578c71529_XXXXX_fc0cdc2604b00f6c5e3ba0133f > public/wp-content/remote-backup-1466667374.sql
   remote | delete: /www/domain.com/wp-content/dump.php
    local | mysqldump --host=localhost --user=root --password=root --result-file="public/wp-content/dump.sql" scotchbox
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:131: warning: Insecure world writable dir /var/www in PATH, mode 040777
    local | adapt dump
   remote | copying public/wp-content/dump.sql to /www/domain.com/wp-content/dump.sql
   remote | write /www/domain.com/wp-content/import.php
    local | download http://domain.com/wp-content/import.php?shared_key=24f42eae8a27146a7_XXXXX_60501c185b78805debd262c1e416bd&start=1&foffset=0&totalqueries=0&fn=dump.sql > public/wp-content/log.html
    debug | Operation log located at: public/wp-content/log.html
   remote | delete: /www/domain.com/wp-content/import.php
   remote | delete: /www/domain.com/wp-content/dump.sql
    local | delete: 'public/wp-content/dump.sql'
```

Sorry if this is a problem on our host. I'm not sure how wordmove uses the mySQL extension and why it can't handle it on php7.

**Comment by pioneerskies** [comment]
FTP here, right?

**Comment by pioneerskies** [comment]
I think this is due to http://php.net/manual/en/function.mysql-connect.php
As far as I can see we should update the embedded bigdump library from 0.35b to 0.36b in order to switch to the "new" (lol) `mysqli` extension.

PR welcome. Anyway we'll take this one seriously in account.

Thanks for reporting the issue.

**Comment by flurinduerst** [comment]
Yes, using FTP in this case. Thanks for the info.

**Comment by pioneerskies** [comment]
This is fixed in a branch and quite ready to be released
