### ISSUE TITLE
Document in wiki that different DB prefixes are still unsupported

### ISSUE THREAD

**Issue by pioneerskies** [welaika/wordmove#327]
That's what the subject said

**Comment by kevinmamaqi** [comment]
Is this solved or still not possible to use different database prefixes

**Comment by pioneerskies** [comment]
Nope. There is a branch somewhere with a first implementation try, but never finished to get it to work properly.

**Comment by pioneerskies** [comment]
https://github.com/welaika/wordmove/wiki/Disclaimer:-different-tables-prefixes-are-*not*-supported
