### ISSUE TITLE
Pull from db seems to pull only some of the db. After pull: Missing widgets.

### ISSUE THREAD

**Issue by fheinrich** [welaika/wordmove#328]
Hi,

So i did "wordmove pull -d" and it pulled the db from my production server to my local environment but when I view it, there are a lots of widgets missing. At least thats the only thin I saw right now. I dont know if anythign else is missing, I will have a look.

But yeah, did anyone come across some kind of problem? It makes wordmove useless as I get an incomplete db backup.

**Comment by veganista** [comment]
This used to happen to me all the time before i started using wp search-replace to do my domain name replacements.

This tends to happen if you don't update the URL's in your database completely.

Just chiming in to give a bit of perspective.

**Comment by fheinrich** [comment]
So you change it before or after using wordmove to pull the db?

**Comment by veganista** [comment]
wordmove does seem to do be doing the correct checking for the serialized fields, see [here](http://wordpress.stackexchange.com/questions/9076/why-is-my-database-import-losing-text-widget-data) if your not 100% sure what is going wrong.

Id i were you you i'd take a look at your options table to see if you can work out what ma have gone wrong.

In terms of what you can do to fix it i'm not sure, before i started playing with wordmove, i used wp-cli to do my database updates but it's more work as you need to import them yourself.

**Comment by pioneerskies** [comment]
Hi there!

Wordmove is capable of handling serialized data during url replacing. So...there might be a bug there...? We'd need a snippet of your mysql dump where widgets get created in order to to some testing.

We, Wordmove developers, never use widgets, so it's possible that we never encountered the problem.

If @fheinrich could drop some data, I'd like to help reproduce the possible bug.

**Comment by pioneerskies** [comment]
Now `wp search-replace` is integrated in Wordmove. YAY!
