### ISSUE TITLE
Update --simulate to do a dry-run when using rsync

### ISSUE THREAD

**Issue by veganista** [welaika/wordmove#329]
As discussed in #271 it would be beneficial for the `--simulate` flag to perform a dry run when using `rsync`.

The output from running `rsync` with the `--verbose --itemize-changes --dry-run`  flags displays a list of files that would be deleted when running the command.

When the flags are passed to Photocopier the flags could be merged into the user supplied flags to provide a summary of changes that will be made.

**Comment by pioneerskies** [comment]
I'm totally ok with the suggested feature :)

**Comment by pioneerskies** [comment]
Fixed/implemented in 13af387. Ready for next release :)
