### ISSUE TITLE
Certificate verification error

### ISSUE THREAD

**Issue by Mehdiway** [welaika/wordmove#331]
lftp throws this error when trying to pull from server

```
find: Fatal error: Certificate verification: subjectAltName does not match ‘ftp.website.com’
mkdir: Fatal error: Certificate verification: subjectAltName does not match ‘ftp.website.com’
```

How do you ignore certificate validation ?

**Comment by pioneerskies** [comment]
Does this help?

https://github.com/welaika/wordmove/wiki/Install-lftp-on-OSX-yosemite#configuration-and-tips
