### ISSUE TITLE
Emojis replaced by question marks when pushing DB

### ISSUE THREAD

**Issue by danielpitulia** [welaika/wordmove#334]
Hello everyone! 

I'm having an issue with emojis not being transferred correctly to my staging site. Some emojis are replaced by a question mark, some don't. It's mainly affecting the blog posts. I'm not sure what is causing this and was hoping someone could point me in the right direction to solving this problem! Could it be something with the character encoding in the database? I don't think this is a wordpress issue because the emojis work on my site if I retype them and update the post. 

For example: 
These work: ☀️ ☔️❤️✨
These get replaced by a question mark: 🇸🇪💛🎉😍😘🌸😎

**OS**: OS X Yosemite 10.10.5
**Ruby version**: ruby 2.0.0p481 (system ruby as far as I know!)
**Wordmove version**: 2.0.0
**Description** : Pushing database via wordmove push -d. I'm using ssh access to access my site on Siteground.com. 
Movefile (edited out some sensitive info)

> local:
>   vhost: "http://www.choiceofscandinavia.dev"
>   wordpress_path: "/Users/daniel/DesktopServer/www.choiceofscandinavia.dev" # use an absolute path here
> 
>   database:
>     name: "choiceofscandinavia"
>     user: "root"
>     password: ""
>     host: "localhost"
> 
> production:
>   vhost: "-"
>   wordpress_path: "-" # use an absolute path here
> 
>   database:
>     name: "database_name"
>     user: "database_user"
>     password: "password"
>     host: "localhost"
>     # port: "3308" # Use just in case you have exotic server config
>     # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH
> 
>   exclude:
>     - ".git/"
>     - ".gitignore"
>     - ".sass-cache/"
>     - "node_modules/"
>     - "bin/"
>     - "tmp/_"
>     - "Gemfile_"
>     - "Movefile"
>     - "wp-config.php"
>     - "wp-content/*.sql"
> 
>   # paths: # you can customize wordpress internal paths
>   #   wp_content: "wp-content"
>   #   uploads: "wp-content/uploads"
>   #   plugins: "wp-content/plugins"
>   #   mu_plugins: "wp-content/mu-plugins"
>   #   themes: "wp-content/themes"
>   #   languages: "wp-content/languages"
> 
>   ssh:
>     host: "-"
>     user: "-"
>   # password: "-" # password is optional, will use public  # keys if available.
>     port: - # Port is optional
>   #   rsync_options: "--verbose" # Additional rsync options, optional
>   #   gateway: # Gateway is optional
>   #     host: "host"
>   #     user: "user"
>   #     password: "password" # password is optional, will use public keys if available.
> 
>   # ftp:
>   #   user: "user"
>   #   password: "password"
>   #   host: "host"
>   #   passive: true
>   #   scheme: "ftps" # default "ftp"

I would really appreciate any tips for solving this problem!

Best regards,
Daniel

**Comment by pioneerskies** [comment]
Ok...I do not wish myself to have the same problems...but: http://stackoverflow.com/a/38363567/1275834

Please, keep in mind that we have problems with UTF8mb4 table charset.

Probably I can't help you further :(
