### ISSUE TITLE
Non WordPress version?

### ISSUE THREAD

**Issue by rockethouse** [welaika/wordmove#335]
Feature Request or alternative.

Hi, 

Is there a way to use this without WordPress (ie just a static html/css site?) or is there a similar tool? I love Wordmove and use it every day with my WP sites, but miss it when I have to work on a static holding page or something else thats not WP.

Cheers

**Comment by mojenmojen** [comment]
Dandelion: http://www.chrisdpeters.com/using-dandelion-for-simple-website-deployments/

And there links to other options in the article as well.

**Comment by pioneerskies** [comment]
@rockethouse , just to make it more clear: what should you need more than a glorious `rsync` together with `--exclude-from` option and relative file, in order to deploy a static site?

**Comment by rockethouse** [comment]
Thanks guys, yeah I should have done some more googling first and i've realised thats all I need and there are a fair few examples online for a rsync scripts.

For anyone else interested here are some:

https://coderwall.com/p/moabdw/using-rsync-to-deploy-a-website-easy-one-liner-command
https://sookocheff.com/post/linux/deploying-a-static-site-with-rsync/
https://gist.github.com/Hypercubed/5804999

**Comment by pioneerskies** [comment]
Oh well, really cool. Thanks for sharing links. 👍
