### ISSUE TITLE
Pulling database doesn't work for one site

### ISSUE THREAD

**Issue by dsgnr** [welaika/wordmove#336]
I am migrating my installations over to a new development server. The databases don't seem to want to pull down. I can successfully ssh in using keys as normal, I can pull all of the files down, but the database doesn't seem to want to pull down.

I am getting the following error:
```
▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=wordpressuser --password=jarrenet --result-file="/var/www/wordpress/lib/local-backup-1471076476.sql" wordpress
gzip --best --force "/var/www/wordpress/lib/local-backup-1471076476.sql"
    local | gzip --best --force "/var/www/wordpress/lib/local-backup-1471076476.sql"
   remote | mysqldump --host=localhost --user=ommited --password=ommited --result-file="/home/ommited/public_html/lib/dump.sql" ommited
/var/lib/gems/2.1.0/gems/net-ssh-3.2.1.beta1/lib/net/ssh.rb:249:in `start': Authentication failed for user user@IP (Net::SSH::AuthenticationFailed)
       	from /var/lib/gems/2.1.0/gems/photocopier-1.1.1/lib/photocopier/ssh.rb:70:in `session'
       	from /var/lib/gems/2.1.0/gems/photocopier-1.1.1/lib/photocopier/ssh.rb:43:in `exec!'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:56:in `remote_run'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:67:in `download_remote_db'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:37:in `pull_db'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:69:in `block in pull'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:68:in `pull'
       	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
       	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
       	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
       	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
       	from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
       	from /usr/local/bin/wordmove:23:in `load'
       	from /usr/local/bin/wordmove:23:in `<main>'
```

I am using a custom port; 69 for SSH'ing in. This is specified in the MoveFile and as said above, this is the same for all sites on this Debian box

I've double checked all the details for remote and local databases but it doesn't seem to want to know! Any ideas?

**Comment by dsgnr** [comment]
Ok, done a bit more digging. When allowing passwords in the remote sshd_config and removing the ssh key from my host, this works.

The strange thing is that it works without SSH keys, despite being able to download the rest of the files. It also works when testing from my Vagrant box, but not from my new development box with Debian 8 installed.

**Comment by dsgnr** [comment]
I have now tried to mimic the system settings from Vagrant, which had Ruby 2.3 installed and Gem 2.5.1. My Debian system now matches this, however still no good. Im wondering whether the MYSQL dump isn't using the right SSH port?

**Comment by dsgnr** [comment]
An update. I have installed a clean VM running Ubuntu, just like my Vagrant VVV box. Same issue. Manually running mysql dump on the remote server works fine.

Anyone able to chime in?

**Comment by pioneerskies** [comment]
Could you paste a formatted `Movefile`, please? remember to wipe out sensitive data :)

**Comment by dsgnr** [comment]
@pioneerskies I managed to solve this. For some reason, my computer made a particularly small ssh-key. Somehow, this managed to cause the mysqldump to not work via SSH.

**Comment by pioneerskies** [comment]
Oh...well...strange, but good!
So let's close this one :)

Cheers
