### ISSUE TITLE
Please describe what exactly happens with each command.

### ISSUE THREAD

**Issue by COLABORATI** [welaika/wordmove#337]
It is not clear to understand what actually happens when commands are executed. Please add a description of what exactly happens, e.g. like this:

```
wordmove push does this:
* export database via mysqldump to a file called xzy in directory abc
* rsync all files from source/directory to destination/directory
* on remote server execute mysql command to overwrite old database
* maybe something else happens, I want to read about it before using it
```

Hopefully you get the idea. There is just too much magic happening and not enough explanation. 
Some questions to help: 
- which transport mechanism is used?
- what exactly happens with the old database?
- is there any kind of rollback?
- where are files stored?
- is this a transactional process, e.g. what happens when transfer is disrupted?
- what else are you doing on my wordpress server?

Thank you very much!

**Comment by pioneerskies** [comment]
Hi @COLABORATI !

Thanks for enquiring us; where should be intended to be kept those informations? In the documentation? README? Wiki?

And what should be the intended final goal? Reaching more users? Simplify debugging processes?

About the magic happening, sorry, but as far as I am concerned, software is not magic when you can read the code :)

I'm really interested in contributing more on this topic. Thanks in advance for you insights.

Cheers

**Comment by pioneerskies** [comment]
Just added a FAQ in the wiki https://github.com/welaika/wordmove/wiki/FAQ

I hope it could be a good start point
