### ISSUE TITLE
Multiple Movefiles in the repo

### ISSUE THREAD

**Issue by matthewnw** [welaika/wordmove#338]
I have a repo that we use that includes an example 'Movefile.example' file with some options and settings added relevant to us that aren't included in the `wordmove init` generated file.

We gitignore our 'Movefile` so that the repo isn't environment specific and to avoid passwords in the repo. The problem is that when the dev copies the 'Movefile.example' and makes a new 'Movefile' with their details, when we run wordmove it uses the example one:

 `▬▬ ✓ Using Movefile: ./Movefile.example`

This appears to be built into wordmove under /lib/wordmove/deployer/base.rb with a '*' after name.
Is this done intentionally? If so what for and how would you suggest naming a template file that won't be used by wordmove over the standard 'Movefile'?

Thanks

**Comment by pioneerskies** [comment]
From my point of view this should not happen and I can't imagine the use case this behaviour was designed for.

I'll call someone else in the discussion such as @delphaber @mukkoo @ramensoup @AleOnRails in order to confirm that this is something to be fixed.

Thanks for opening the issue

**Comment by pioneerskies** [comment]
Better later than never: this was recently fixed @matthewnw 🎉
