### ISSUE TITLE
mysqldump: Permission denied

### ISSUE THREAD

**Issue by brunoDegaspare** [welaika/wordmove#344]
Hi, when I run `wordmove push --all` the files are pushed successfully but it breaks when it tries to interact with my local database.

I get this error:

```
local | mysqldump --host=localhost --user=root --password=root --result-file="/path/to/my/project/wp-content/dump.sql" bruno
sh: /Users/bruno/bin/mysqldump: Permission denied
```

If I run `mysqldump` I get this:
```
-bash: /Users/bruno/bin/mysqldump: Permission denied
```

I don't know how to solve this. =(

**Comment by pioneerskies** [comment]
Oh well @brunoDegaspare ,

if `mysqldump` is not working properly it won't neither through Wordmove. Personally i have installed mysql using brew and my binary relies here:

```bash
⟩ which mysqldump                                                   [ruby 2.3.0]
/usr/local/opt/mysql55/bin/mysqldump
```

I have no clue about your environment and the way you configured it.

**Comment by brunoDegaspare** [comment]
Yeah installaing mysql through brew helped. But my mysql relies on `/usr/local/bin/mysqldump` while I think it should rely on `/Users/bruno/bin/mysqldump`  How I can change that?

**Comment by brunoDegaspare** [comment]
Ok, "auto-fixed". This solution worked for me:

[http://stackoverflow.com/questions/3268789/add-mysqldump-to-mamp-mysql-w-apache-php-on-macos-x](url)

Now wordmove works like a charm. Finally bye FTP and manual deployments.

**Comment by pioneerskies** [comment]
Glad to hear that! Welcome on board
