### ISSUE TITLE
Peer Dependencies

### ISSUE THREAD

**Issue by joefraley** [welaika/wordmove#345]
I know it's outside the scope of this repo, but it would be awesome to have a canonical environment description for running the tool. It kind of sucks to piece everything together as a Wordpress first-timer.

For example, the package assumes that you've already installed mysql, and that it's been configured correctly. It assumes you have a local wordpress installation. It might assume lots of other things I haven't encountered yet.

Even just a statement of peer dependencies: "You can't use this tool without..." would be useful.

**Comment by pioneerskies** [comment]
I love to write wiki pages and then link them into the main readme in a dedicated paragraph.

Would it be ok from your pow?

**Comment by joefraley** [comment]
Sure I think it could definitely help!

**Comment by pioneerskies** [comment]
Fixed in branch and quite ready to be released
