### ISSUE TITLE
After pushing to prod, 500 Internal Server Error when trying to load any .php files in folder/sub-folders

### ISSUE THREAD

**Issue by ryanfurtner** [welaika/wordmove#349]
After pushing to prod I now get 500 Internal Server Errors when trying to load any .php files in folder/sub-folders.

I made a standard plain old php file with a echo hello world type thing here
http://staging.furtzdesigns.com/luke.php
This worked fine until I pushed from local using wordmove to http://staging.furtzdesigns.com

I even updated apache and php to see if it helped. It actually made luke.php start working again, then after trying another push using wordmove, 500 error again.

I seriously cannot get my head around this!!

Apache log shows: 

`175.35.22.200 - - [08/Nov/2016:15:25:51 +1100] "GET /luke.php HTTP/1.1" 404 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"`

**Comment by ryanfurtner** [comment]
http://puu.sh/sanPt/1673872ca7.png

I changed the PHP handler to cgi and it seemed to fix it (was suPHP)... Any ideas?

**Comment by simonmacfadyen** [comment]
Sounds like `.htaccess`, why not ignore that file and manage it manually on the production environment?

e.g.

```
  exclude:
    - ".htaccess/"
``

**Comment by pioneerskies** [comment]
Not really sure, but I'd consider also that suPHP runs PHP interpreter as a specific user. I don't know which user and exactly how it works, but possibly it could be related with file permissions on the remote server.

**Comment by ryanfurtner** [comment]
Okay so I've tried without .htaccess and the issue still occurs with suPHP. Looks like @pioneerskies is onto something. Anyone want me to try anything to get this working? Thanks.

**Comment by pioneerskies** [comment]
@ryanfurtner I'm having an idea after reading other issues: can you try to push your file, go into the server and report us file permissions?

**Comment by pioneerskies** [comment]
Aged.
