### ISSUE TITLE
Pulling database from docker environment

### ISSUE THREAD

**Issue by inertum** [welaika/wordmove#350]
I have a problem where I have access to the docker host and have read/write permisson to everywhere, but the mysql is only allowed from inside the container.

(without knowing what the end result is ;) Is there a way (or reason) to manually give the remote sql dump file with same parameters or use different connection for the mysqldump?

**Comment by pioneerskies** [comment]
Hi @inertum ,

I really can't get the point, because Wordmove runs mysql exactly from inside the remote host if you are using SSH connection as I think.

Could you elaborate a bit more on your scenario?

**Comment by inertum** [comment]
Sorry I was bit confused myself when I wrote the message ;) (we just changed the whole setup  of our servers)

So my problem got reduced down to this - I connect with my own user, but If I want to write files to the WP folder I need to sudo another user which doesn't have login rights. After which I would need to chown www-data:www-data all the files/directories aswell. Same applies for mysqldump i need to sudo it

And now realising ever more that maybe this use case is bit more specific than wordmove is intented for :)

**Comment by pioneerskies** [comment]
We had not replied to you anymore, sorry.

The point here is that if you cannot connect with at lest some privileges, almost nothing will work.

The only inherent matter we encountered is the use of `--chown` and related flags on `rsync`. Il close this because it's too aged. Sorry.
