### ISSUE TITLE
Support for WP Multisite installations

### ISSUE THREAD

**Issue by NazarkinRoman** [welaika/wordmove#351]
Hello!

I haven't found anything in the product description about that point, but it is really important feature as I think. I'm talking about the ability to push local WP single-site installation into WP multi-site one.

Thanks.

**Comment by pioneerskies** [comment]
Hi,

unfortunately Wordmove does not support such flow. Moreover we have no use cases to try to study the complexity and needs of such feature :(

Somewhat related to #227
