### ISSUE TITLE
When pushing to siteground I get 500 - Internal Server Error 

### ISSUE THREAD

**Issue by miguelangeltorresfp** [welaika/wordmove#352]
Hi,
I've installed wordmove ( 2.0.0 ) on vagrant.
My pc has
virtual box 5.1.6
vagrant 1.8.7
vvv 1.4.0
vv 1.12
ruby 2.3.0p0

I'm trying to set up a workflow on a GoGeek Siteground host.

I can pull the site from production to local and then access the local site without problems.
wordmove pull -e production --all 

When I try to push the local site to production, everything seems to work perfectly but then I get a 500 internal server error on the browser.

I hope you can guide me on this issue.

Thanks in advance.

**Comment by miguelangeltorresfp** [comment]
Doing tests it seems that all options works well except 
wordmove push -e staging -w

**Comment by miguelangeltorresfp** [comment]
As @yuranikolaev commented on another [issue](https://github.com/welaika/wordmove/issues/161), I added additional options to rsync command in wordmove file and it seems to work perfectly.

When is it suppossed that I would have to use << wordmove push -e staging -w >> ????

Could I simply update wordpress on the server ???

Thanks in advance.

**Comment by hal0gen** [comment]
It would be useful if you could provide some server logs, a 500 error should be traced somewhere. On a SiteGround website I administer, I can see them from cPanel (Visitor Stats -> Error Logs). Anyway, you should be able to update WordPress yourself on the server and just transfer the parts you need using WordMove (database, themes, plugins, uploads).

**Comment by simonmacfadyen** [comment]
You're probably pushing your `.htaccess` file and the production server does not like it. 

Try ignoring/excluding your `.htaccess` file in your `Movefile`.

**Comment by phidomo** [comment]
I'm having the same problem with Siteground. I am pushing to the "dev" folder with rsync_options: "--chmod=ugo=rwX" as described in https://github.com/welaika/wordmove/issues/161.

But I still get a 500 error. I checked the Error Logs in Visitor Stats and the problems are
error: file is writable by others: (/home/site/public_html/dev/index.php)
error: directory is writable by others: (/home/site/public_html/dev)
error: directory is writable by others: (/home/site/public_html/dev/wp-admin)

**Comment by pioneerskies** [comment]
@phidomo thankfully your hosting company is doing some strict checks on your site. Probably using a stricter chmod could make it work?

    rsync_options: "--chmod=644"

@miguelangeltorresfp about using `-w` flag...well, that's all about your workflow. Once a site is in production, my opinion is that updates of the core are managed on production. So I personally use `-w` in order to **pull** updates from production before to proceed on new implementations and I save those updates in GiT as a first step. Sometimes critical updates require you to manage theme locally...in this case `-w` should also be useful in order to push your work on staging/production.

**Comment by phidomo** [comment]
When I push with rsync_options: "--chmod=644" then I get:

rsync: recv_generator: failed to stat "/home/site/public_html/dev/index.php": Permission denied (13)

**Comment by pioneerskies** [comment]
Aw wtf!

Well....I really don't know anything about your remote environment....you should experiment a bit, knowing that rsync's flags are not that easy, but they are cool.

I'd try, blindly, `--chmod=ug=rwX`

**Comment by phidomo** [comment]
I'm using VVV for local development. I checked the file and folder permissions in the VVV box and it is all rwxrwxrwx. So it looks like I have to fix the permissions in the local machine before pushing.

**Comment by pioneerskies** [comment]
I'm so sorry, but I can't help you specifically about VVV :(

**Comment by hal0gen** [comment]
Siteground knowledge base addresses the error message you receive: 
[HTTP Error 500 – Internal server error](https://www.siteground.com/kb/internal_server_error_500/)
I have no experience with VVV but 777 for all folders doesn't seem right, wouldn't 755 be more appropriate (with 777 for the uploads folder)?

**Comment by phidomo** [comment]
I just looked at all the permissions in the default WordPress folder of Siteground and all folders are 755, all files are 644, except wp-config.php is 600.

To keep the permissions of the all the files and folder that are already on the server, maybe you could use rsync_options: -avz --no-perms --no-owner --no-group

Then manually set the file permissions after pushing as in https://codex.wordpress.org/Hardening_WordPress#File_permissions
find /path/to/your/wordpress/install/ -type d -exec chmod 755 {} \;
find /path/to/your/wordpress/install/ -type d -exec chmod 755 {} \;
chmod 600 wp-config.php

**Comment by pioneerskies** [comment]
find /path/to/your/wordpress/install/ -type d -exec chmod 755 {} ;
    find /path/to/your/wordpress/install/ -type f -exec chmod 644 {} ;

Sounds really good permissions if you (ssh user) and the webserver are sharing the same user with the ownership of your folders. From my point of view is unusual, but as far as it is suggested by your hosting provider we will take it as The truth :)

But you should be able to directly push with those permissions without having to set them after each push - yeah, you can script that and automate it, but...Wordmove should already solve the problem.

@hal0gen 777 is not good even for uploads folder. Upload folder has really nothing special

**Comment by phidomo** [comment]
@pioneerskies Well I don't really know if the ssh user and the web server share the same user. It doesn't really say it on this page https://www.siteground.com/tutorials/cpanel/file_permissions.htm. Also I can't find the right Linux commands to figure it out.

How can I directly push with those permissions?

**Comment by pioneerskies** [comment]
Really by default you should adopt those permissions locally, check the files permissions in GiT, and just® push them. Default `-avz --delete` flags should hold file permissions across transfer.

**Comment by pioneerskies** [comment]
I've done some tests on Siteground...well...not really that mess.

1st of all:

> Check your WordPress files for permissions above 755. Our servers run in SuExec mode so the maximum allowed permissions are 755, all permissions above 755 will result in Internal Server Error. You can find which files exactly give the error from your cPanel > Error log.

via https://www.siteground.com/kb/i_am_receiving_500_internal_server_error_when_i_try_to_acces/

So what I have done?

* Checked file permissions. Mine was ok, but

    find . -type f | xargs chmod 644
    find . -type d | xargs chmod 755

from my project root.

* Configured Wordmove:

```yaml
siteground:
  vhost: "http://example.com"
  wordpress_path: "/home/myuser/public_html"
  exclude:
    - "*.mp3"
    - "*.m4a"
    - "tmp/*"
    - "*.pdf"
    - "Movefile"
    - ".git*"
    - "newsletter"
    - "wp-config.php"
    - ".htaccess"
    - ".sass-cache"
    - "Wordfile"
    - "*.sql.gz"
  database:
    name: "dbuser"
    user: "dbuser"
    password: "dbpasswd"
    host: "localhost"
  ssh:
    host: "myhost.siteground.eu"
    user: "myuser"
    port: "18765"
    rsync_options: "--itemize-changes"
```

* push it

    wordmove push -wtpdu -e siteground

And boom. The site is there, up and running. Permissions were brought from my local env to siteground as expected. SSH user and php web server user are the same (`myuser` in my example) as expected, thanks to the use of suPHP, so that ownership perfectly fits our needs without have to --chown, --no-owner, --you-say-what with `rsync`.

As an additional note:

```bash
myuser@myhost [~/public_html]# rsync --version
rsync  version 3.0.6  protocol version 30
Copyright (C) 1996-2009 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, no symtimes
```

rsync version prior to 3.1.0 **does not** support ownership manipulation:

>     - Added the --usermap/--groupmap/--chown options for manipulating file ownership during the copy.

via https://rsync.samba.org/ftp/rsync/src/rsync-3.1.0-NEWS

So we can't use such magic on SiteGround unless we ask them to update their software (changelog dated 28 Sep 2013).

I rly rly hope you'll find something useful here.

**Comment by phidomo** [comment]
@pioneerskies Thank you for all the information.

I checked the file permissions of all the projects inside of the Vagrant VM and the permissions are all 777. So it is a Vagrant problem.

**Comment by pioneerskies** [comment]
I'd be happy to receive a little feedback from @miguelangeltorresfp also :)
