### ISSUE TITLE
Database pull/push error - undefined method / Mac Yosemite MAMP PRO

### ISSUE THREAD

**Issue by andreaske** [welaika/wordmove#353]
Hy,
i really was and still am excited about wordmove.
But i spend now a full day in configuring several things to get it working.
I would be very gratefull to get some help.

i now still have my hardest time for pushing/pulling the database and still get the same error:

    $ wordmove pull -d
    
    ▬▬ ✓ Using Movefile: ./Movefile     ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    
    ▬▬ ✓ Pulling Database     ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬    ▬▬▬
    /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:174:in     `mysql_dump_command': undefined method `[]' for nil:NilClass (NoMethodError)
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:232:in     `save_local_db'
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:34:in     `pull_db'
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:69:in `block in pull'
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in     handle_options'
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in     `handle_options'
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:68:in `pull'
    	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in     `invoke_command'
    	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
    	from /usr/local/bin/wordmove:23:in `load'
    	from /usr/local/bin/wordmove:23:in `<main>'`

When **pushing** the Database i got the same error after succesfull remote actions of creating and deleting dump files.

    /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:174:in     `mysql_dump_command': undefined method `[]' for nil:NilClass (NoMethodError)

**Here are some details regarding my environment:**

**OS:** MacOSX Yosemite 10.10.5
**Wordmove:** 2.0.0
**MAMP PRO 3.4**

**This is my Movefile:**

    local:
      vhost: "http://localhost/test"
      wordpress_path: "/Users/andreaske/Webseiten/test" # use an absolute path here
    
      database:
      name: "test"
      user: "root"
      password: "root"
      host: "127.0.0.1"
      port: "3306"
      charset: "utf8"
    
    production:
      vhost: "http://test2.xyz.de"
      wordpress_path: "/www/htdocs/xyz" # use an absolute path here
    
      database:
        name: "xyz"
        user: "xyz"
        password: "password"
        host: "localhost"
        #port: "3308" # Use just in case you have exotic server config
        mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH
    
      exclude:
        - ".git/"
        - ".gitignore"
        - ".sass-cache/"
        - "bin/"
        - "tmp/"
        - "Gemfile"
        - "Movefile"
        - "wp-config.php"
        - "wp-content/*.sql"
        - "DS_Store"
        - ".htaccess"
    
      # paths: # you can customize wordpress internal paths
        # wp_content: "wp-content"
        # uploads: "wp-content/uploads"
        # plugins: "wp-content/plugins"
        # themes: "wp-content/themes"
        # languages: "wp-content/languages"
        # themes: "wp-content/themes"
    
      ssh:
        host: "xyz.kasserver.com"
        user: "ssh-xyz"
        password: "password"
        port: 22 # Port is optional
        # rsync_options: "--verbose" # Additional rsync options, optional
        # gateway: # Gateway is optional
        # host: "host"
        # user: "user"
        # password: "password" # password is optional, will use public keys if available.
    
      # ftp:
        # user: ""
        # password: ""
        # host: ""
        # passive: true
    
    # production: # multiple environments can be specified
    # [...]

**Output from terminal when firing mysqldump:**

    $ mysqldump
    Usage: mysqldump [OPTIONS] database [tables]
    OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
    OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
    For more options, use mysqldump --help

**Output for Variables:**

    $ cat ~/.bash_profile
    export PATH=/usr/local/git/bin:$PATH
    source $HOME/.bashrc`
    
    $ cat ~/.profile
    cat: /Users/Username/.profile: No such file or directory`
    
    tail -n 5 ~/.bashrc
    # Add MAMP bin directory into $PATH
    PATH="/Applications/MAMP/Library/bin:$PATH"

**Comment by pioneerskies** [comment]
Hey sorry for the delay but you have just an indentation problem in your `Movefile`... db options must be indented under the `database` key:

```yaml
database:
  name: "test"
  user: "root"
  password: "root"
  host: "127.0.0.1"
  port: "3306"
  charset: "utf8"
```

**Comment by pioneerskies** [comment]
Oh...tnx for your detailed report...loved all the environment's information you reported <3

**Comment by pioneerskies** [comment]
Considering as resolved
