### ISSUE TITLE
Enter passphrase for ... id_rsa

### ISSUE THREAD

**Issue by sebszocinski** [welaika/wordmove#357]
Hi, 

I've had this issue before and managed to fix it but now it's come back to haunt me and find the fix... every time I deploy it asks me to enter my passphrase... what's the trick to avoid this again? On a mac running Sierra.

Cheers

**Comment by pioneerskies** [comment]
Probably something like this https://help.github.com/articles/working-with-ssh-key-passphrases/ ?
