### ISSUE TITLE
Can't pull database

### ISSUE THREAD

**Issue by rustyblue100** [welaika/wordmove#361]
Here is the error message, the files download are all fine, somebody have an idea? Thank you

> mysqldump: Can't create/write to file '/home/xxxxxx/public_html/wp-content/dump.sql' (Errcode: 13 - Permission denied)

**Comment by pioneerskies** [comment]
What print commands `ls -l /home/xxxxxx/public_html/wp-content` and `id` on your remote host?
It seems like you really have no write permission on the folder using your ssh user.

**Comment by rustyblue100** [comment]
Actually prints out my files and folders. My wp-content as a 755 permission

**Comment by pioneerskies** [comment]
Well...yes, I'd liked to lurk your files and folder permissions 👯 
And with the command `id` what your user and group settings are.

With 5 on group the group has not write permission for example.

**Comment by pioneerskies** [comment]
Aged.

**Comment by MarkErik** [comment]
Hi, was this resolved?
I am also running into the same problem: /wp_files/wp-content/dump.sql' (Errcode: 13 "Permission denied")

From ls -la:
drwxr-xr-x  7 www-data www-data  4096 Sep  7 16:25 wp-content

As mentioned, it looks like no one except root has write access.

What is the secure way to address this?

Thank you for your help!
