### ISSUE TITLE
Push theme CSS or JS only

### ISSUE THREAD

**Issue by rockethouse** [welaika/wordmove#364]
Hey, I'm wondering if there is a way to only push CSS or JS for times when you are working with another front-end dev who is only doing either js or css.

One person could be working on CSS and the other on JS and you could both push and pull each others changes.

**Comment by pioneerskies** [comment]
hey is ti possible I'm just running on a unicorn, but:

```yaml
exclude:
    - [default excludes here]
    - "! *.css"
```

Never tried playing around with these rsync tricks, but it could worth a try...

Then you'll have the problem to have a different Movefile per dev and so it can't be checked in git; but it is another chapter of the story.

Let me know about my unicorns! :P

**Comment by rockethouse** [comment]
Ah of course that would work! Thanks for pointing it out!

**Comment by pioneerskies** [comment]
Oh well you are welcome. If it will really work remember to close the issue ;)
