### ISSUE TITLE
charset problem between ubuntu mysql version to CentOS mySQL version

### ISSUE THREAD

**Issue by Richzendy** [welaika/wordmove#365]
I'm using vccw[1] vagrant machine with ubuntu and wordmove to make push to a external webhosting with CentOS 7 (ispconfig 3), all files are pushed fine, but the DB is not created in to production environment, searching the problem (i don't have any error message on wordmove ) and trying make the db export manually i get a problem with the charset / collation, this problem was fixed making an export with mysqldump with this option:

     --compatible=mysql4

For example: 

    mysqldump --compatible=mysql4 --host=localhost --user=wordpress --password=wordpress --result-file="/var/www/html/wp-content/dump.sql" wordpress

Wordmove can have  --compatible=mysql4 option by default? or make a test by mysql versions and if compatibility is needed use that option? thank you

[1] http://vccw.cc/

**Comment by pioneerskies** [comment]
MuSQL4? Oh my my! :D No it cannot have it by default, but you can have it in your Movefile's per environment settings as per [documentation](https://github.com/welaika/wordmove/wiki/Movefile-configurations-explained#per-environment-options-local).

Tell me if it worked and close the issue if you're ok with that :)

Cheers

**Comment by pioneerskies** [comment]
Considering as a positive response :)

**Comment by Richzendy** [comment]
yes, the mysqldump_options will work for this case, thank you.

FYI, the mySQL version on centOS is 5.x not 4.X, the option --compatible=mysql4 was to fix the charset/collation problem (are different by default between centOS and ubuntu)

This ticket can be closed now, sorry because was open again by this comment
