### ISSUE TITLE
exclude rule applied to theme only?

### ISSUE THREAD

**Issue by rockethouse** [welaika/wordmove#366]
Hey I just ran into a weird and annoying issue.

I had `/assets` in my exclude rules, so that only the /dist files of my theme would be pushed live.

However this rule runs in any directory on the whole of wordpress.... so if any plugin (ie Advanced Custom Fields)  use an /assets folder, then that won't be included.

Is there any way to limit an exclude to a directory but also with a wildcard? ie...

exclude:
 - "wp-content/themes/*/assets/"

So that I don't need to put the theme name in every Movefile. The above doesn't seem to work.

**Comment by pioneerskies** [comment]
Hi there,

first of all: keep always in mind we are directly passing those excludes to `rsync`, so how they work depends totally on how `rsync` works.

Some notes:

* if you want to exclude a folder in `rsync` you should append the trailing slash such as `assets/`; that way `rsync` wont exclude files named "assets".
* if you express a simple string such as `assets`, it will be matched for each path ignoring what it is, if it is a partial match or anything else: string found? Well, skip this.
* in your case my exclude rule would be `/wp-content/themes/*/assets/`; but also your previous one was expected to work afaik

Let me know

**Comment by rockethouse** [comment]
Ok great thanks i'll try that.

**Comment by pioneerskies** [comment]
Pls, reopen if other help's needed
