### ISSUE TITLE
Can't make it work in Windows.

### ISSUE THREAD

**Issue by shahroznawaz** [welaika/wordmove#368]
I have installed everything but when i run command **wordmove pull --all** it gives an error like this

`
          C:\xampp\htdocs\csv>wordmove pull --all

          ▬▬ √ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

          ▬▬ √ Pulling wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
            remote | get_directory: /home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html C:/xampp/htdocs/csv .git/ .gitig
          nore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
          I, [2017-02-23T19:49:51.908378 #7696]  INFO -- : rsync --progress -e 'sshpass -p f6qBxsh6 ssh master_xjhzsqsekh@46.101
          .5.233' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclu
          de node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --excl
          ude wp-content/\*.sql --exclude wp-content/\* :/home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/ C:/xampp/ht
          docs/csv

          ▬▬ √ Pulling Uploads ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
            remote | get_directory: /home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/uploads C:/xampp/htdo
          cs/csv/wp-content/uploads .git/ .gitignore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-co
          ntent/*.sql wp-content/*
          I, [2017-02-23T19:49:51.918378 #7696]  INFO -- : rsync --progress -e 'sshpass -p f6qBxsh6 ssh master_xjhzsqsekh@46.101
          .5.233' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclu
          de node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --excl
          ude wp-content/\*.sql --exclude wp-content/\* :/home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/u
          ploads/ C:/xampp/htdocs/csv/wp-content/uploads

          ▬▬ √ Pulling Themes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
            remote | get_directory: /home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/themes C:/xampp/htdoc
          s/csv/wp-content/themes .git/ .gitignore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-cont
          ent/*.sql wp-content/*
          I, [2017-02-23T19:49:51.918378 #7696]  INFO -- : rsync --progress -e 'sshpass -p f6qBxsh6 ssh master_xjhzsqsekh@46.101
          .5.233' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclu
          de node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --excl
          ude wp-content/\*.sql --exclude wp-content/\* :/home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/t
          hemes/ C:/xampp/htdocs/csv/wp-content/themes

          ▬▬ √ Pulling Plugins ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
            remote | get_directory: /home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/plugins C:/xampp/htdo
          cs/csv/wp-content/plugins .git/ .gitignore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-co
          ntent/*.sql wp-content/*
          I, [2017-02-23T19:49:51.928377 #7696]  INFO -- : rsync --progress -e 'sshpass -p f6qBxsh6 ssh master_xjhzsqsekh@46.101
          .5.233' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclu
          de node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --excl
          ude wp-content/\*.sql --exclude wp-content/\* :/home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/p
          lugins/ C:/xampp/htdocs/csv/wp-content/plugins

          ▬▬ √ Pulling Mu Plugins ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
            remote | get_directory: /home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/mu-plugins C:/xampp/h
          tdocs/csv/wp-content/mu-plugins .git/ .gitignore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php
          wp-content/*.sql wp-content/*
          I, [2017-02-23T19:49:51.938377 #7696]  INFO -- : rsync --progress -e 'sshpass -p f6qBxsh6 ssh master_xjhzsqsekh@46.101
          .5.233' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclu
          de node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --excl
          ude wp-content/\*.sql --exclude wp-content/\* :/home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/m
          u-plugins/ C:/xampp/htdocs/csv/wp-content/mu-plugins

          ▬▬ √ Pulling Languages ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
            remote | get_directory: /home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/languages C:/xampp/ht
          docs/csv/wp-content/languages .git/ .gitignore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php w
          p-content/*.sql wp-content/*
          I, [2017-02-23T19:49:51.948376 #7696]  INFO -- : rsync --progress -e 'sshpass -p f6qBxsh6 ssh master_xjhzsqsekh@46.101
          .5.233' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclu
          de node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --excl
          ude wp-content/\*.sql --exclude wp-content/\* :/home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html/wp-content/l
          anguages/ C:/xampp/htdocs/csv/wp-content/languages

          ▬▬ √ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
              local | mysqldump --host=127.0.0.1 --user=root --result-file="C:/xampp/htdocs/csv/wp-content/local-backup-14878613
          91.sql" wordmov
          gzip --best --force "C:/xampp/htdocs/csv/wp-content/local-backup-1487861391.sql"
              local | gzip --best --force "C:/xampp/htdocs/csv/wp-content/local-backup-1487861391.sql"
          C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:132:in `run': Return code reports
          an error (Wordmove::ShellCommandError)
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:35:in `pull_db'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:69:in `block in pull'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'

                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:68:in `pull'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
                  from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
                  from C:/Ruby23-x64/bin/wordmove:22:in `load'
                  from C:/Ruby23-x64/bin/wordmove:22:in `<main>'

          C:\xampp\htdocs\csv>`

my movfile looks like this

local:
          vhost: "http://vhost.local"
          wordpress_path: "C:/xampp/htdocs/csv" # use an absolute path here

          database:
            name: "wordmov"
            user: "root"
            password: ""
            host: "127.0.0.1"

        production:
          vhost: "https://symfonyfeed.com"
          wordpress_path: "/home/56883-71265.cloudwaysapps.com/pwurmkmezy/public_html" # use an absolute path here

          database:
            name: "pxxxxxxxxxezy"
            user: "pwxxxxxxxxxezy"
            password: "aSxxxxxxx9aX"
            host: "46.101.5.233"
            # port: "3308" # Use just in case you have exotic server config
            # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

          exclude:
            - ".git/"
            - ".gitignore"
            - ".sass-cache/"
            - "node_modules/"
            - "bin/"
            - "tmp/*"
            - "Gemfile*"
            - "Movefile"
            - "wp-config.php"
            - "wp-content/*.sql"

          # paths: # you can customize wordpress internal paths
          #   wp_content: "wp-content"
          #   uploads: "wp-content/uploads"
          #   plugins: "wp-content/plugins"
          #   mu_plugins: "wp-content/mu-plugins"
          #   themes: "wp-content/themes"
          #   languages: "wp-content/languages"

          ssh:
            host: "46.101.5.233"
            user: "master_xxxxxxxxsekh"
            password: "fxxxxxxsh6" # password is optional, will use public keys if available.
          #   port: 22 # Port is optional
          #   rsync_options: "--verbose" # Additional rsync options, optional
          #   gateway: # Gateway is optional
          #     host: "host"
          #     user: "user"
          #     password: "password" # password is optional, will use public keys if available.

          # ftp:
          #   user: "user"
          #   password: "password"
          #   host: "host"
          #   passive: true
          #   scheme: "ftps" # default "ftp"

        # staging: # multiple environments can be specified
        #   [...]
      somebody please tell me what I am doing  wrong here?

**Comment by phidodido** [comment]
ShellCommandError means it probably can't find MySQL. Did you start the MySQL server?

If you have Windows 10 then you can follow my guide 
https://github.com/welaika/wordmove/wiki/How-to-install-Wordmove-on-Windows-10-with-Bash
