### ISSUE TITLE
Unknown collation: 'utf8mb4_unicode_520_ci' (Wordmove::ShellCommandError)

### ISSUE THREAD

**Issue by mrky007** [welaika/wordmove#369]
Operating System: Ubuntu 16.04.
Vagrant Version: Vagrant 1.9.1
Virtual Box Version: 5.1.14 r112924 (Qt5.5.1)

I've setup my development environment and everything works great, but when I try to push all to production server I always get: Unknown collation: 'utf8mb4_unicode_520_ci' (Wordmove::ShellCommandError) for Database Pushig.

I've read somwhere that this might be a problem with mysql version, development server uses: 5.7.16 and live server has 5.5.54 installed.

Has anyone encountered / fixed this issue?

**Comment by pioneerskies** [comment]
I wrote something about that [here](https://dev.welaika.com/blog/2016/10/12/it-wordpress-db-fix.html). Spoiler: yes, that's a problem with mysql version on production and newer WP versions. I'm almost secure it is not a Wordmove issue.

**Comment by mrky007** [comment]
@pioneerskies you sir are a genius :-) I just tested this out and it works perfectly. Thanks for helping me out. I will use it on new installs only of course.
