### ISSUE TITLE
Vagrant Installation issues

### ISSUE THREAD

**Issue by rootion** [welaika/wordmove#373]
I am following the installation guide described here: https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-(or-any-Vagrant) but I am stuck in some steps that are not clear.

- [x] Find the provision folder in your VVV root folder.
- [x] Create a file called provision-pre.sh and fill it with (...)
- [x] Provision your vagrant with $ vagrant provision, $ vagrant up --provision, or $ vagrant reload --provision
- [x] Once Vagrant is up, run $ vagrant ssh. 
- [ ] Now, navigate to your site folder $ cd /srv/www/myproject and run your Wordmove magic. 

Here is where I got stuck. When running `vagrant ssh` I don't have access to my www/folder project. When running `ls` I only see a bin folder. And if I cd my working folder directly I don't have access to wordmove, as I get a `command not found`

Could you please clarify these steps?

**Comment by dustinpaluch** [comment]
I'm betting they just mean /vagrant.

**Comment by AndreaBarghigiani** [comment]
I use WordMove on VVV and before run the `wordmove` command you have to _cd_ in this directory: `/srv/www/<your-folder>`

This is all you have to do if you want to run wordmove.

Hope this had help ;)

**Comment by pioneerskies** [comment]
Closing this because lack of reactions.
