### ISSUE TITLE
Wordmove not pushing anything on Windows

### ISSUE THREAD

**Issue by phidodido** [welaika/wordmove#374]
I got wordmove installed on Windows and when I push to the server everything seems to be OK. No error messages but in reality nothing is getting pushed at all.
![image](https://cloud.githubusercontent.com/assets/20196554/23781721/935495b6-0592-11e7-82e1-725c3548cb40.png)

How can I debug this? I can't find any log files with --debug option.

**Comment by phidodido** [comment]
rsync is not installed on Windows so it doesn't do anything when using SSH.

I have tried several ways to install rsync on Windows 10 but couldn't get it working.

**Comment by pioneerskies** [comment]
Just as ref.: https://github.com/welaika/wordmove/wiki/How-to-install-Wordmove-on-Windows-10-with-Bash
