### ISSUE TITLE
Duplicate Posts/ Can't edit pages/posts

### ISSUE THREAD

**Issue by michaelHeimes** [welaika/wordmove#376]
I had used wordmove push --all a few days ago. There was some sort of local error in WP core so I pushed only the database, themes and plugins. Then I ran wordmove pull --all. Somehow both databases have duplicates of every post and when I click edit on a page it just refreshes the all pages window. 

Did I do something wrong?

**Comment by michaelHeimes** [comment]
I figured this out. It was an error on my end. Something I had in my functions.php that blocked edits. This can be closed. Thanks!

**Comment by pioneerskies** [comment]
Ha! Fortunately we can stop to be afraid of such a terrible bug! :D Tnx for reporting back 😨
