### ISSUE TITLE
Error when pushing database over FTP

### ISSUE THREAD

**Issue by chrilleferna** [welaika/wordmove#377]
I'm using this excellent tool for several sites, but I have run into an issue with a recent site, where I do not have SSH access. Themes, Plugins and Uploads pushes fine, but I get an error when pushing the database, which surprisingly comes from FTP:

` remote | write /web/wp-content/dump.php`

`/Users/christer/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/ftp.rb:243:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)`

The database server, as configured in wp-config.php on the server is localhost

**Comment by pioneerskies** [comment]
Hi there,

and sorry for this late reply. Would you like to add some [info](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting) to your issue, please?

I'd like to give it a spin
