### ISSUE TITLE
Push -d leaves dump.mysql on the server

### ISSUE THREAD

**Issue by jwktje** [welaika/wordmove#378]
After performing a push of the database it leaves a dump.mysql file in the wp-content directory.
The actual sync works fine.

I'm using ftp sync from local to a shared hosting that doesn't allow SSH sadly.
Any help would be greatly appreciated

**Comment by jwktje** [comment]
Bump with bug bounty.

Does anybody wanna fix this issue and #231 for a code bounty of 40 USD?

**Comment by pioneerskies** [comment]
#231 recently had a follow up by maintainers.

**Comment by pioneerskies** [comment]
Dear @jwktje maintainers just published v2.1.1 with this fix.

I'd be glad if you could have the time to give us some feedback :)

**Comment by jwktje** [comment]
I'd love to help but I've currently moved all my active sites over to SSH already! So I don't really have this issue anymore.

**Comment by pioneerskies** [comment]
Thank you anyway for taking the time to give your feedback :)

I'll consider this one fixed since my tests were "green".

Cheers
