### ISSUE TITLE
Static Front Page

### ISSUE THREAD

**Issue by chris-smearing** [welaika/wordmove#379]
I'm trying to clone a production site which has a static front page. When I open my admin, the front page is set to latest posts. Is this the correct behavior, or am I missing something? 

The site also uses WooCommerce and a plug-in for it called WOOF - WooCommerce Products Filter. The settings for this plug-in are not synced with the production site. Is this correct?

**Comment by pioneerskies** [comment]
No: generally it is not correct, but I can't check anything about it.

Could you attach all the info requested [here](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting) plus custom tables structures/dump id any?

That way someone could try to give some help
