### ISSUE TITLE
Keep permission on rsync

### ISSUE THREAD

**Issue by Mte90** [welaika/wordmove#381]
We are using wordmove with an our VPS but we see that the file change permission with `ssh_user:users` but locally is this different and also the file on the vps have ``www-data:www-data` permission.
I am not sure if it is wrong something for my side for VPS or on rsync used from wordmove is missing a parameter.

**Comment by pioneerskies** [comment]
It's a completely natural behaviour: you write on the server as `ssh_user` user and with its own `umask`. You can control that behaviour.

You can find a lot of discussion on project's issues such as https://github.com/welaika/wordmove/issues/341 and generally searching [--chamod](https://github.com/welaika/wordmove/search?o=desc&q=--chmod&s=updated&type=Issues&utf8=%E2%9C%93) in the repo.

Reopen if you need ;)
