### ISSUE TITLE
Public key not working

### ISSUE THREAD

**Issue by marcversluis** [welaika/wordmove#382]
Wordmove keeps asking for a password while it should use my public key. It used to work without any problems before. When ssh-ing into my server now, my public key is still being used without a problem.

**Comment by pioneerskies** [comment]
Hi there,

we have no symptoms about bugs affecting that behaviour; overall that behaviour is totally delegated to your system with no intervention by Wordmove itself.

If you'd run the `rsync` command by hand - it is emitted on STDOUT - you'd certainly get same result. Be sure that you are testing from the same environment: e.g. vvv uses a different one and rsa keys are not shared between your local machine and vvv.

Please, re-open if you'll get more info
