### ISSUE TITLE
DB and Files require different paths

### ISSUE THREAD

**Issue by paulmist** [welaika/wordmove#383]
I was using the following paths to pull files (plugins) with no problem:

```
production:
  vhost: "http://••••••••••••••.co.uk"
  wordpress_path: "/" # use an absolute path here
```
But I couldn't pull the DB until I changed the wp path to:
```
wordpress_path: "/home/•••••••••••••/public_html/"
```
However, after I did that I could no longer pull files!

Is there something I'm missing?

**Comment by pioneerskies** [comment]
FTP?

**Comment by paulmist** [comment]
I am using FTP - yes.

Is that what you wanted to know?

**Comment by pioneerskies** [comment]
Sorry for the humongous lag.

Already tried to follow [these](https://github.com/welaika/wordmove#ftp) instructions?
