### ISSUE TITLE
Set WordPress path in push command?

### ISSUE THREAD

**Issue by diple** [welaika/wordmove#385]
Possible setting the Wordpress local path in push command?
=> wordmove push /my/path --all

**Comment by pioneerskies** [comment]
Please, could you elaborate a bit about your needs?
Changing path is already supported, so I can't figure out what would you like to accomplish

**Comment by diple** [comment]
I want to check if I can change my script:
`os.system("cd " + local_path + " && wordmove push --all")`

For something like this:
`os.system(wordmove push --all --path="/foo/bar")`

In fact it is not a problem just a curiosity.
You can close the issue.
Thanks.

**Comment by pioneerskies** [comment]
Oooookkk, got it!

ATM in not possible to configure on the command line an execution folder other than the one when you are. The only feature Wordmove has, is upward traversing to find `Movefile` (so if you are in theme's folder, you can invoke Wordmove and it will read `Movefile` in project's root).

Thanks for your explanation.

Cheers
