### ISSUE TITLE
Windows 7. Problem with pushing wordpress files and database.

### ISSUE THREAD

**Issue by ithrasil** [welaika/wordmove#386]
I can't push wordpress files and database to remote server.

Wordmove makes just:
- dump.sql.gz, on production server
![image](https://cloud.githubusercontent.com/assets/11476062/24837061/d9b16ace-1d2b-11e7-9f76-f7aa50115e06.png)

and 

- backup files, on my local server
![image](https://cloud.githubusercontent.com/assets/11476062/24837065/0c928964-1d2c-11e7-8cc5-1259b5b9ccea.png)

This is my screen from cmd:

![image](https://cloud.githubusercontent.com/assets/11476062/24837051/5f956196-1d2b-11e7-9480-f2a393f54549.png)

my movefile

```
local:
  host: "https://osterreich.dev"
  wordpress_path: "g:/vhosts/osterreich" 
  
  database:
    name: "osterreich"
    user: "root"
    password: ""
    host: "localhost"

production:
  vhost: "http://my.host.com/"
  wordpress_path: "/home/Ithrasil/domains/my.host.com/public_html" 
  
  database:
    name: "####"
    user: "####"
    password: "####"
    host: "####"

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - ".htaccess"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"
   
  ssh:
    host: "####"
    user: "Ithrasil"
    rsync_options: "--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r"

**Comment by pioneerskies** [comment]
I really don't know how to debug windows problems...and it's a pity that no one else from the community could help.

Hey there! I know someone managed to get Wordmove working on Windows! Make a step forward!

**Comment by pioneerskies** [comment]
Aged :(
