### ISSUE TITLE
no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by mufaddalmw** [welaika/wordmove#387]
I'm keep getting this error, can someone help me here-
<img width="900" alt="screenshot 2017-04-13 17 24 25" src="https://cloud.githubusercontent.com/assets/1768671/25006478/11fa2dea-206e-11e7-9b6f-1684c719416a.png">

**Comment by pioneerskies** [comment]
Sorry @mufaddalmw ,

unfortunately we have not enough information about the error. I'll be glad to take a deeper look, but you should follow our [bug reporting guidelines](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting) if you can.

If you have time and need to follow up, pls, reopen the issue.

Cheers
