### ISSUE TITLE
mysqldump_options --ignore-table doesn't work

### ISSUE THREAD

**Issue by byron222** [welaika/wordmove#391]
i try this

mysqldump_options: "--ignore-table=dbname.wp_popularpostsdata"

but doesn't work.....

**Comment by pioneerskies** [comment]
Hi there.

Is the option appended to the `mysqldump` shown on STDOUT?
Are you using SSH connection method?

I've just tried it out and I can't reproduce any error (and anyway: what's your actual error if any)

**Comment by byron222** [comment]
I got the great results!
I was using this not in the loca setting
