### ISSUE TITLE
i get error  when i pull -d

### ISSUE THREAD

**Issue by byron222** [welaika/wordmove#394]
i get this error 
`/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wordmove-2.0.2/lib/wordmove/sql_adapter.rb:45:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)`

what can i do?

**Comment by pioneerskies** [comment]
Just polished relative wiki page

https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db

We have some plans (https://github.com/welaika/wordmove/issues/367) but at the moment we cannot fix those situations. I'm sorry.

P.S.: if you have time remember you have #391 pending ;)
