### ISSUE TITLE
i got the error of undefined method '[]' for nil:NilClass in new version (2.1.2)

### ISSUE THREAD

**Issue by byron222** [welaika/wordmove#396]
wordmove pull -d

/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wordmove-2.1.2/lib/wordmove/deployer/base.rb:24:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wordmove-2.1.2/lib/wordmove/cli.rb:80:in `push'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wordmove-2.1.2/exe/wordmove:6:in `<top (required)>'
        from /root/.rbenv/versions/2.4.1/bin/wordmove:22:in `load'
        from /root/.rbenv/versions/2.4.1/bin/wordmove:22:in `<main>'

**Comment by byron222** [comment]
i delete my old Movefile file and do wordmove init and well done!
thank you!

**Comment by dreamsinmotion** [comment]
add this

global:
  sql_adapter: "default"
