### ISSUE TITLE
Automatically deactivate the specific plugin

### ISSUE THREAD

**Issue by byron222** [welaika/wordmove#400]
Is there any system when push to production, automatically deactivate the specific plugin?

**Comment by pioneerskies** [comment]
We have a really old feature request which could fit your needs here #142 , but I'm thinking about a scenario where wp-cli is installed remotely.
Directly implementing this sort of things from outside wordpress/wpcli is unaffordable. But a hooks system would be great for many situations.

Another good discussion reference is here https://github.com/welaika/wordmove/issues/302#issuecomment-302009679

I'd like to discuss ideas inside those 2 issues, so I'm gonna closing this one :)

**Comment by pioneerskies** [comment]
@byron222 FYI the new hooks feature should fit your scenario, said you have `wp-cli` installed on your hosting :)
