### ISSUE TITLE
wp db export for database dumps

### ISSUE THREAD

**Issue by strarsis** [welaika/wordmove#405]
wp cli can also be installed/used on shared hosting - and it offers dumping and restoring from database.
Wouldn't it be an improvement if existing wp cli functionality could be used?

**Comment by pioneerskies** [comment]
Do you mean when you use SqlAdapter::Wpcli (https://github.com/welaika/wordmove/wiki/Movefile-configurations-explained#per-environment-options-global)?

It would be a good point: we use wp-cli  just for `search-replace`...but what could be the difference/advantage over `mysqldump`? Moreover current approach does not depend on having wp-cli installed remotely.
