### ISSUE TITLE
wp-cli SQL adapter should specify WordPress path

### ISSUE THREAD

**Issue by sebastianopilla** [welaika/wordmove#407]
The ```wp search-replace``` command can only work if the current directory, in the ```pwd``` sense, is the WordPress path. Starting wordmove from another directory, with a ```wordpress_path``` correctly configured in the Movefile, gives:

```
    local | adapt dump for vhost
    local | wp search-replace https://www.association-sauve.com http://www.sauve.lan --quiet --skip-columns=guid --all-tables
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
/usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:141:in `run': Return code reports an error (Wordmove::ShellCommandError)
        from /usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:37:in `adapt_remote_db!'
        from /usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh.rb:35:in `pull_db'
        from /usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/cli.rb:69:in `block in pull'
        from /usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/cli.rb:37:in `block in handle_options'
        from /usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/cli.rb:36:in `each'
        from /usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/cli.rb:36:in `handle_options'
        from /usr/local/gems/gems/wordmove-2.1.3/lib/wordmove/cli.rb:68:in `pull'
        from /usr/local/gems/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/gems/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/gems/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /usr/local/gems/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /usr/local/gems/gems/wordmove-2.1.3/exe/wordmove:6:in `<top (required)>'
        from /usr/local/gems/bin/wordmove:22:in `load'
        from /usr/local/gems/bin/wordmove:22:in `<main>'
```

The fix should be simple: always invoke wp-cli with the ```--path=``` option pointing to the ```wordpress_path``` configuration from the Movefile.

**Comment by pioneerskies** [comment]
Hello there!

Hmmm...interesting point. So you have a scenario where you have command line outside WP!? Would you like to write down an example, so that i could figure it out?

The problem is clear, but since we never work in such a scenario, I'd like to be more aware of it :)

And the solution you suggested should just work® because `wodpress_path` option is mandatory.

**Comment by sebastianopilla** [comment]
My use case is synchronizing multiple remote WordPress installations with their corresponding development environments on my laptop. I have a bash script which does the following:

```
for WPDIR in ${WPDIRS}; do
  echo "**** Synchronizing directory ${WPDIR}"
  cd ${WPDIR}
  git pull --rebase
  cd ${WPDIR}/..
  GEM_PATH="${GEM_PATH}" GEM_HOME="${GEM_HOME}" "${WORDMOVE}" pull --uploads --db --verbose --environment=production
done
```

The Movefile(s) are one directory above each of the $WPDIRS directories. For example:

```
$ ll /data/dev/sebastianopilla.com/
total 4.0K
drwxr-xr-x 1 admin admin  34 Apr  4  2015 graphics/
-rw-rw-r-- 1 admin admin 854 Jul  8 11:53 Movefile
drwxrwxr-x 1 admin admin   0 Oct  4  2015 scripts/
drwxrwxr-x 1 admin admin 584 Jun 10 21:50 sebastianopilla/
```

So I'm invoking wordmove with the current working directory set to ```/data/dev/sebastianopilla.com```, and the WordPress installation pointed to by the Movefile is in the ```/data/dev/sebastianopilla.com/sebastianopilla``` directory.

Since, as you said, the ```wordpress_path``` option is mandatory in the Movefile, adding a ```--path``` option to the wp-cli invocation shouldn't break anything.

**Comment by pioneerskies** [comment]
@sebastianopilla hi have just done a trip inside the code and I have a not-so-good news: the adapter itself at the moment is an isolated class which doesn't have knowledge about all `Movefile`'s options.

Doing something to make it more context aware would be a re-design task I have not enough time for these days.

I'd like to suggest you to try this alternative approach:

```bash
for WPDIR in ${WPDIRS}; do
  echo "**** Synchronizing directory ${WPDIR}"
  cd ${WPDIR}
  git pull --rebase
  GEM_PATH="${GEM_PATH}" GEM_HOME="${GEM_HOME}" "${WORDMOVE}" pull --uploads --db --verbose --environment=production --config=../Movefile
  cd ${WPDIR}/..
done
```

Could this trick work in your scenario?

**Comment by sebastianopilla** [comment]
@pioneerskies I've tested your alternative approach and it worked fine for me, I'm ok with closing the issue if that works for you.
