### ISSUE TITLE
change default dump.sql path

### ISSUE THREAD

**Issue by herbie4** [welaika/wordmove#408]
HI, 
Not really an issue, but a question.
Is it possible to change the default mysql dump path from wp-content to a specified location?
Best regards, hrbrt

**Comment by pioneerskies** [comment]
Hi @herbie4 ,

actually that is not possible; I'm planning about introducing hooks in Wordmove, but it will be a quite long run. At the moment you should wrap wordmove in a shell script and manage the move there.
