### ISSUE TITLE
URLs still pointing to localhost

### ISSUE THREAD

**Issue by adekunlemumuni** [welaika/wordmove#411]
After running a wordmove push --all command, the links on the remote server are still pointing to localhost on my local server. Please, what am I doing wrong here? Thanks!

**Comment by nghh** [comment]
Same here

**Comment by nghh** [comment]
Ahh, that was easy. Look at your Movefile. 
local > vhost must match exactly what you entered in your wordpress backend. 
So watch out for a trailing slash at the end of your URL

Cheers

**Comment by adekunlemumuni** [comment]
@nghh Thanks a lot! That worked but now I'm getting a 500 internal server error :( on other pages that aren't the home page.

**Comment by adekunlemumuni** [comment]
@nghh Never mind. Fixed it. Thanks buddy :)
