### ISSUE TITLE
Permission denied when pull request

### ISSUE THREAD

**Issue by giantleif** [welaika/wordmove#413]
When I run:

`wordmove pull --all`

I get the following error:

`▬▬ ✓ Pulling wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: /var/www/vhosts/hostsite.com/mysite /home/leif/vagrant-local/www/mysite/htdocs .git/ .gitignore .sass-cache/ node_modules/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql.gz .htaccess wp-content/*
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:229:in 'mkdir': Permission denied @ dir_s_mkdir - /home/leif (Errno::EACCES)`

**Comment by giantleif** [comment]
I found my issue. In my Movefile I had previously been setting the local wordpress_path to my local dev machine. I needed to update this to the vagrant path that is used when I ssh into the vm.

previous:

`wordpress_path: "/home/leif/vagrant-local/www/vcc/htdocs" # use an absolute path here`


new:

`wordpress_path: "/vagrant/www/sitename/htdocs" # use an absolute path here`

I also needed to install sshpass in the VM.

**Comment by pioneerskies** [comment]
Dear @giantleif ,

I'm thankful you posted your solution together with the issue :D This will be really helpful for other users.

I hope to have done a good thing updating the issue title with the intention to have it more *speaking* for a the search engine :)

Hope you'll enjoy using `wordmove` working on your project
