### ISSUE TITLE
After wordmove pull --all everything is deleted locally

### ISSUE THREAD

**Issue by Brun0AFK** [welaika/wordmove#414]
Hello 

im using FTP connection bc ssh is terrible at my hosting provider. So i setup this:

global:
  sql_adapter: "default"

local:
  vhost: "http://localhost:8888/esc/esc/"
  wordpress_path: "/Applications/MAMP/htdocs/esc/esc" # use an absolute path here

  database:
    name: "real_name"
    user: "real_user"
    password: "real_password"
    host: "localhost"

dev:
  vhost: "http://sub.domain.me/esc/"
  wordpress_path: "/home/user/public_html/sub/esc" # use an absolute path here

  database:
    name: "real_name"
    user: "real_user"
    password: "real_password"
    host: "localhost"

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql.gz"

  ftp:
      user: "real_ftp"
      password: "real_Password"
      host: "ftp.domain.me"

So after i run command i get this

https://pastebin.com/bfKE1Zcc

So now can u help me litlebit?

i have install that ftp thing i have add set ssl:verify-certificate no i have ruby 2.2.2 and wordmove 2.1.3. Im using macos

This is what is left
![image](https://user-images.githubusercontent.com/2721915/30733738-95f45eb6-9f78-11e7-9166-df333129275a.png)

**Comment by pioneerskies** [comment]
Sorry @Brun0AFK ... I wasn't active on the project and in the meantime the pastebin was deleted so I can't figure out what the problem was...

**Comment by Brun0AFK** [comment]
Hey @pioneerskies sorry i didnt see this before. I will try again this weekend, and i will give you more information. I hope i dont bother you too much :)

**Comment by pioneerskies** [comment]
Hey @Brun0AFK you are welcome. Still waiting for some updated info :)

**Comment by pioneerskies** [comment]
Closing. Follow-up always welcome anyway
