### ISSUE TITLE
Is there a way to concatenate flags, or omit some from --all ?

### ISSUE THREAD

**Issue by frontenddevguy** [welaika/wordmove#430]
Since I have been unable to get the db to push, I was wondering if it's possible to say:
push all (but not db)
push plugins, themes, uploads

The wiki made it seem as though this may be possible by adding a comma between flags but it appears not to work this way.

Is one of the above scenarios possible?

Also what is the command to update wordmove?
I would like to try wordmove doctor and see if I can learn something about my local environment, to fix the db push

**Comment by pioneerskies** [comment]
Hi @frontenddevguy ,

`wordmove pull --all --no-wordpress` should do the work.

Issuing `wordmove help pull` will give you all the options

```
> wordmove help pull
Usage:
  wordmove pull

Options:
  -w, [--wordpress], [--no-wordpress]
  -u, [--uploads], [--no-uploads]
  -t, [--themes], [--no-themes]
  -p, [--plugins], [--no-plugins]
  -m, [--mu-plugins], [--no-mu-plugins]
  -l, [--languages], [--no-languages]
  -d, [--db], [--no-db]
  -v, [--verbose], [--no-verbose]
  -s, [--simulate], [--no-simulate]
  -e, [--environment=ENVIRONMENT]
  -c, [--config=CONFIG]
      [--debug], [--no-debug]
      [--no-adapt], [--no-no-adapt]
      [--all], [--no-all]
```

All the `--no-` options should coexist w/o problems after [this](https://github.com/welaika/wordmove/commit/a8a237eef0497f84347bd3f8cca3c58d385351f9) commit.

Let me know if and when we can close the ticket :)

Good luck!

**Comment by pioneerskies** [comment]
@frontenddevguy said:

> Also what is the command to update wordmove?

`gem update wordmove` is the way to go; `wordmove --version` is useful to check your installed version :)

**Comment by frontenddevguy** [comment]
Nice one, thanks. I am very grateful for all you are doing!
It makes everything so much easier :)

Just one more thing. How can we chain --no-wordpress AND --no-db

I ran wordmove doctor. Very cool..

Just a couple of errors that may be useful to report:

▬▬ ✓ Validating movefile section: production ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    error | [/ssh/port] '7822': not a integer.

▬▬ ✓ Validating movefile section: staging ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    error | [/vhost] 'https://staging.site.com': not matched to pattern /^http:\/\//.
    error | [/database/port] '7822': not a string. 


All the db stuff checked out ok, so ongoing troubleshooting with getting db push to work..

**Comment by pioneerskies** [comment]
> Just one more thing. How can we chain --no-wordpress AND --no-db

Yep! I've updated the documentation with `--no-*` explanation: https://github.com/welaika/wordmove/wiki/Usage-and-flags-explained#--no-

**Comment by pioneerskies** [comment]
> Nice one, thanks. I am very grateful for all you are doing!
> [...]
> I ran wordmove doctor. Very cool..
>
> Just a couple of errors that may be useful to report:

First of all you are welcome! Moreover an issue opened by a proactive user, brings benefit to all the community.

Would you mind to open a specific issue about the `doctor`? We are inspecting its behaviour as well and we already have a couple of improvements to push out. But I'd like to have an in-topic issue where to discuss your notes and maybe add there some notes from the maintainers :)

Close this one if you are happy, please!

**Comment by pioneerskies** [comment]
Accidental closing ;)

**Comment by pioneerskies** [comment]
@frontenddevguy I've annotated your notes about `doctor` [here](https://github.com/welaika/wordmove/projects/1) together with other issues raised from my team :)

**Comment by frontenddevguy** [comment]
Many thanks. I am having a very busy time so apologies for not getting to this sooner!
