### ISSUE TITLE
Rsync path

### ISSUE THREAD

**Issue by Mte90** [welaika/wordmove#440]
Actually we have a vps where `rsync` is on a specific folder and not the usual one but remotely seems that there isn't a parameter to specify where is the command.

**Comment by pioneerskies** [comment]
Hello @Mte90 ,

that's a fact. What's the question?

**Comment by Mte90** [comment]
In few words a parameter in wordmove,yaml file where is possible to specify the path for rsync remotely

**Comment by pioneerskies** [comment]
Understood. Fortunately `rsync` already handle such situations itself with the `--rsync-path` option.

Cheers :)

**Comment by Mte90** [comment]
So how I can do that?
There is no docs for that but https://github.com/welaika/wordmove/issues/392 looking there seems something that can be handled with rsync_options. 
I will try it.

**Comment by pioneerskies** [comment]
No docs for that? Tried to search `rsync` in wikis? We have tons of docs outside of the main README.

[here](https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained), under the `production.ssh` key explanation. Moreover in the movefile.yml generated by `init` you should find

```yml
  # ssh:
  #   host: host
  #   user: user
  #   password: password # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: --verbose --itemize-changes# Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: host
  #     user: user
  #     password: password # password is optional, will use public keys if available.
```

Hope it helps

**Comment by Mte90** [comment]
Yes, sorry from your comment seems wasn't clear that I have to use `rsync_options` for this parameter. I was thinking that was already a parameter in wordmove specific for that.

**Comment by pioneerskies** [comment]
Oh no! My bad, you are right! :D
