### ISSUE TITLE
Need to upload a different folder

### ISSUE THREAD

**Issue by frontenddevguy** [welaika/wordmove#441]
I am using Nextgen gallery on a couple of sites (I know...) and it uses a folder called gallery in wp-content.

Is there a way to specify other folders than the standard ones for upload?
I can do it with scp but with move would be more efficient.

**Comment by pioneerskies** [comment]
Hello @frontenddevguy :)

atm there is no way to manage non-standard folders. As a workaround I'd try to move the folder inside the `uploads` folder and manually make a symlink on both environments. Or you could make a symlink only locally and remotely use an `after.push.remote` hook to `mv`/`rsync` the folder from `uploads` to the parent folder.

My fear about evaluating support for arbitrary folders is:

* it could open up infinite usage scenarios
* it would be hard to find an easy to use configuration interface

**Comment by frontenddevguy** [comment]
fair enough I can do that with scp

**Comment by pioneerskies** [comment]
@frontenddevguy ,

just out of curiosity: have you integrated the scp (anyway I'd use rsync for the task...) command inside the new hook system in an `after.push.remote`? I'm willing to receive feedback about this new feature 😋 

Cheers

**Comment by frontenddevguy** [comment]
I havent tried that. If I end up using it very often I might :)
