### ISSUE TITLE
Permission Denied (public key) error

### ISSUE THREAD

**Issue by mmaltbia** [welaika/wordmove#443]
I've recently updated my OS (El Capitan) and now two of my Wordmove installations are no longer working. 

Here is the error message I'm receiving when trying to pull from my production server:

```
cpanelusername@myserver.com: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.2]
```
I've checked that I am able to SSH into my server via Bash and this is working fine. I've also tried uninstalling and installing the rsync gem. In addition, I have also changed the folder permissions to 644. Also, Wordmove Doctor is showing success for all items. Any advice would be greatly appreciated.

**Comment by pioneerskies** [comment]
Hello @mmaltbia :)

you said:

> I've checked that I am able to SSH into my server via Bash and this is working fine

what is the ssh command you issue?

Moreover

> I have also changed the folder permissions to 644

As far as I can tell, those permissions on `~/.ssh` folder are wrong and unaccepted by ssh, breaking it's functionality. Right permission should be 700 on folder and 600 on `~/.ssh/id_rsa`

**Comment by mmaltbia** [comment]
Changing my folder permissions to the ones listed in the reply did the trick. Thank you!
