### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by frontenddevguy** [welaika/wordmove#444]
I am getting the following error:

/usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.3.0/lib/wordmove/movefile.rb:33:in `expand_path': No such file or directory - getcwd (Errno::ENOENT)

As far as I can tell this Movefile is set up exactly the same as another that works

**Comment by frontenddevguy** [comment]
Oops, I forgot that after deleting and recreating a directory, terminal needs a restart

**Comment by pioneerskies** [comment]
WAT? Really? Did not expected such a behaviour, honestly 😨

**Comment by frontenddevguy** [comment]
Apparently so. Added to my list of things to restart when something doesnt work as expected. Apache often catches me out :p
