### ISSUE TITLE
Latest version not compatible with Ruby 2.5.0?

### ISSUE THREAD

**Issue by nghh** [welaika/wordmove#446]
Hey,
i get an error when trying to install wordmove. 

#####
Error installing wordmove:
There are no versions of wordmove (= 2.4.0) compatible with your Ruby & RubyGems
wordmove requires Ruby version ~> 2.4.0. The current ruby version is 2.5.0.
#####

Wordmove 2.0.0 is running fine...

Is anyone else having this issue?
Thank you.

**Comment by pioneerskies** [comment]
Thank you very much. Never updated to ne last stable ruby. All done in the 2.4.1 version :)

Re-open if it won't work
