### ISSUE TITLE
Does this work with Multisite?

### ISSUE THREAD

**Issue by digisavvy** [welaika/wordmove#45]
hey there,
I'm looking for a scripted method to sync Multisites from one environment to the other. This looks promising. Off the top of your head could this work with a sub-folder multisite setup?

**Comment by torounit** [comment]
Like This?

https://github.com/torounit/wordmove/blob/multisite/lib/wordmove/sql_adapter.rb

**Comment by Mte90** [comment]
This work also for subfolders?

**Comment by torounit** [comment]
@Mte90 This work for subfolder install. not testing for subdomain install.

**Comment by pioneerskies** [comment]
Please @torounit make a pull request from your code, so that we can easily review that. I will be glad to test and review it as soon as I can

+1

**Comment by manolof** [comment]
@torounit fork seems to be working for sub-domains too.

**Comment by jwktje** [comment]
What would it still take to implement this Multisite support in the core of Wordmove?
I can provide a small code bounty if someone can make it work in a stable way.

Just a hobbyist doing some multisite research. So can only miss $30.

**Comment by leFlea-snippets** [comment]
@jwktje Can you share the details of your test here?

**Comment by jwktje** [comment]
Easy. Set up Multisite by using the SubFolder install. Then use Wordmove like normal. After pushing to the live location manually edit the domain and path field in the wp_blogs table in your live database. Then it worked for me

**Comment by kauaicreative** [comment]
remove http:// from the vhost: - both local vhost: and production vhost:
```
vhost: architecture.test
```
