### ISSUE TITLE
moving files on same server

### ISSUE THREAD

**Issue by bnowacky** [welaika/wordmove#450]
I have a staging and production on same machine. it's same local mysql, but different databases. 

any thought to a configuration not relying on environments being on different machines? AKA, I can't ssh to the same server that I'm already on.

any ideas/suggestions?

**Comment by pioneerskies** [comment]
Hello,

as far as I understand you need not to move only files, but database also. Am I right?

Anyway Wordmove is precisely written to mirror between local and remote environments. I'm sorry, but it can't work with 2 local installation.

But writing a little shell script using `rsync` and `wp-cli` should be an affordable task.

Have to close this, but feel free to comment on if you need

**Comment by bnowacky** [comment]
Well it’s also capable of moving files between different enviros like dev staging and production if they are all on different boxes. 

Would be simple enough to add a —local flag that would use Rsync locally. Db works by default now, it’s just rysc which tries to copy between servers. Db can copy between instances on the same machine currently with no issue.
