### ISSUE TITLE
mysqldump: Got error: 2003: Can't connect to MySQL server on '127.0.0.1

### ISSUE THREAD

**Issue by Ebeldev** [welaika/wordmove#451]
Hi, 

I'm trying to work with Wordmove and when i push using the "Wordmove push --all", i get only one error that I just can't get it to work. It's in the last step, connection with my local mysql.
I'm on a mac with MAMP. 

mysqldump: Got error: 2003: Can't connect to MySQL server on '127.0.0.1' (61) when trying to connect

Any idea why? or how to solve this?

Cheers,

**Comment by pioneerskies** [comment]
Hi,

Wordmove simply runs `mysqldump` from your $PATH. You should first check if you can connect to your DB using `mysqldump` in your terminal.

Possible scenarios are:

* mysql server not running
* mysql server not configured to listen on expected port (configurable)
* you have many mysql instances on your system and trying to connect to the wrong one (almost 
a $PATH problem)

**Comment by pioneerskies** [comment]
Feel free to reopen if you have something to deepen.
