### ISSUE TITLE
Calling wordmove outside of the vagrant box

### ISSUE THREAD

**Issue by good3n** [welaika/wordmove#456]
Is it possible to pull/push mysql db's outside of the vagrant box with Wordmove? I'm not sure what the "path" would be in order to do that. I just don't really want to ssh to the vagrant box when I need to push/pull.

Thanks!

**Comment by pioneerskies** [comment]
What's the problem with `vagrant ssh box -c 'wordmove push -d'`?

**Comment by pioneerskies** [comment]
Any reaction?
