### ISSUE TITLE
photocopier requires Ruby version ~> 2.4

### ISSUE THREAD

**Issue by MorganConrad** [welaika/wordmove#458]
Might be related to #363?

Anyway, I get this error:
```
$ sudo gem install wordmove
ERROR:  Error installing wordmove:
	photocopier requires Ruby version ~> 2.4.
```
but
 ```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

I'm a novice with both Ruby and WordMove, but just did an update to Ruby 2.4.1 from 2.3

**Comment by pioneerskies** [comment]
Hi @MorganConrad ,

I can assure that ruby should not be your knowledge, if not just installing gems.

I've noticed an incongruence between required ruby version in wordmove and in its sibling gem photocopier and I want to thank you to have spotted that out.

But!

I do not think it could be a problem in your scenario. Please, paste here the output of

    sudo ruby -v

**Comment by pioneerskies** [comment]
@MorganConrad just for completeness, now we are building against 3 different ruby versions on CI: https://travis-ci.org/welaika/wordmove

**Comment by pioneerskies** [comment]
Any news from your `sudo ruby -v` ? ☺️

**Comment by MorganConrad** [comment]
$ sudo ruby -v
[sudo] password for morgan:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by pioneerskies** [comment]
<img width="675" alt="image 2018-02-25 at 4 26 19 pm" src="https://user-images.githubusercontent.com/904690/36643182-a5ad73ec-1a48-11e8-87a1-a1254c91bb08.png">

:( I don't know how to reproduce this one :(
