### ISSUE TITLE
Support for Amazon RDS?

### ISSUE THREAD

**Issue by sebszocinski** [welaika/wordmove#459]
Is it possible to use WordMove with an Amazon RDS instance?

I would have thought not, but maybe there is another way?

**Comment by pioneerskies** [comment]
As long as you have access to your MySQL through a tcp port, why not?

If Wordpress can connect, generally speaking, also wordmove will.

**Comment by endorama** [comment]
As long as you have access to your MySQL through a tcp port, why not?

This is true, you should try accessing you RDS instance using the mysql command line. If you are able to do so you should be good to go.

    If Wordpress can connect, generally speaking, also wordmove will.

This is generally true outside AWS, but with RDS you could have configuration blocking connection to the RDS instance, like VPC route tables, network acl or security groups from outside AWS. Try connecting using mysql command line, and if you can't, look at networking configurations in AWS for something blocking connection to the RDS instance.

You could also use a ssh tunnel on the instance with WordPress: here applies the suggestion from @pioneerskies ( if WordPress can connect you should be able to connect to it too )

**Comment by sebszocinski** [comment]
Thanks guys got it working.
