### ISSUE TITLE
Movefile syntax higlihgting

### ISSUE THREAD

**Issue by nlemoine** [welaika/wordmove#46]
Hi,

I was wondering why the Movefile is a YAML formatted file but does not receive the .yaml extension ?

It's not a big deal but as many developpers, I'm using Sublime Text and the syntax highlighting is not displaying when no file extension was found.

Could you change this ? I think it would bring some confort while editing Movefile files. 
This can be achieved in a way to preserve backward compatibility : 

``` ruby
      def self.fetch_movefile(path)
        path ||= "Movefile.yaml"
        unless File.exists?(path)
          path = "Movefile"
        end
        unless File.exists?(path)
          raise Thor::Error, "Could not find a valid Movefile"
        end
        YAML::load(File.open(path))
      end
```

I'm not a ruby developper there's probably a smarter way to do this. 

Thanks for considering this request. 

N.

**Comment by nlemoine** [comment]
@pioneerskies Any chance you may mention in the docs that Movefile can also take the `yaml` or `yml`?

**Comment by pioneerskies** [comment]
I could say yes, but I'd be happy to see a wiki contribution or a pull request against the README 💃 
If you can't it'd be probably better to open a new issue in order to keep it in mind

**Comment by nlemoine** [comment]
No problem, I just wanted to ask before submitting a PR 😉 

Just in case, I'm taking a chance to go further, would you consider default `Movefile` to become a `Movefile.yml` file (e.g. file created with `wordmove init`)? I think it would bring some benefits and clarifications about the file format to Wordmove users:
- requires no extra editor configuration (adding a package, configuring it, etc.)
- automatic indentation detection (no need to mention some basic advices on yaml like [those](https://github.com/welaika/wordmove/wiki/Movefile-configurations-explained))
- automatic syntax highlighting in any editor

What do you think?

**Comment by pioneerskies** [comment]
I think that despite I'm really used to not have the extension, I'm totally with you. So if any follower of this conversation would not have something to argue, I'll choose to accept your reasons and implementations

**Comment by nlemoine** [comment]
Thanks for considering the request. Let me know when you will start doing this, I can provide some help with the docs (I suck at ruby).

**Comment by nlemoine** [comment]
@pioneerskies Seems like no one have something to argue :)

Would you consider adding the yaml extension as the default behaviour?

**Comment by pioneerskies** [comment]
@nlemoine you are "lucky" I've got a cold and I'm in the bed with my headache and bored as hell...and so https://github.com/welaika/wordmove/pull/424

Tests are passing. I'm going to di a live test before merging on master.

**Comment by nlemoine** [comment]
Sorry about that ^^ Hope you'll be better soon. 

Thanks for taking care of this change. Since you're bored, sorry for being picky but could the default could be `Movefile.yml`? The shorter extension is kind of a convention when using YAML files (Symfony, etc.) and keeping the capital M will probably handle better some retro compatiblity/OS filesystem edge cases and cause less trouble and misunderstanding around Wordmove users. 

Let me know if I can help.

**Comment by pioneerskies** [comment]
Pls, let's discuss in the PR
