### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by mugurcagdas** [welaika/wordmove#476]
Dear Sir/Madam,

I am computer engineer and graphic designer, I am writing you because I want to design a logo for "wordmove".
May I ask, do you need a NEW logo for this plugin or do you wish to check my design against existing logo?

Kindly waiting your answer.

Best Regards,
Musa Ugur Cagdas
Computer Engineer/Graphic Designer

**Comment by pioneerskies** [comment]
Hi there,

we have our logo in the repository `assets/` folder; we don't need a new logo, but if you are willing to contribute to this open-source project I think and hope that the community would be happy to comment on a draft PR.

Feel yourself at home :)
