### ISSUE TITLE
A strange bug on line #15

### ISSUE THREAD

**Issue by UmeedEmad** [welaika/wordmove#481]
Hi. I am getting a bug while running wordmove pull --all command. On line # 15. Here is my code.
`global:
  sql_adapter: wpcli

local:
  vhost: http://onwardcapital.wp/
  wordpress_path: D:/wamp64/www/onwardcapital # use an absolute path here

  database:
    name: onwardc4_WPALA
    user: onwardc4_WPALA
    password: "9G1LI7OoDwEo3UEhj" # could be blank, so always use quotes around
    host: localhost

production:
  vhost: https://onwardcapitalre.com #line number 15`

**Comment by pioneerskies** [comment]
I'm sorry this never received a reply. BTW the issue had few to none information.

https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting

Closing because stalled.
