### ISSUE TITLE
 mysqldump/mysql instead  dump.php?

### ISSUE THREAD

**Issue by xwulfus** [welaika/wordmove#485]
Is possible to  use mysqldump/mysql directly without any  ftp uploads?

**Comment by pioneerskies** [comment]
Hi,

would you mind to elaborate, please? What is the cause/effect for which you are asking this question?

As a first reply i can tell you that having the database reachable on a public TCP port is a too much specific situation. Supporting all the specific situation is not affordable, so we think that the current strategy is a better fit covering most of the needs.

Thanks a lot

**Comment by pioneerskies** [comment]
Sorry if half a year is passed by...

Let me be a bit sarcastic: you have a VPN and you use FTP to connect to the server? What's the point?

We consider FTP connections an emergency and disappearing scenario; that said and having to deal with the loss of time, I can't imagine to invest resources on FTP connection.

I'm really sorry about that.

Obviously a backward compatible contribution would be welcome.
