### ISSUE TITLE
safety when push/pull

### ISSUE THREAD

**Issue by Bandi017** [welaika/wordmove#493]
is there a possibility of implementing a safety feature for pushing or pulling? I came pretty close to deleting the live DB because my head was on another planet when i was trying to pull the DB. I'm thinking of something in the lines of: 
wordmove push -e production --all 
are you sure you want to push ?? (yes/no)
                          or 
wordmove push -e production -d 
are you sure you want to push the database? (yes/no)

**Comment by nailbrain** [comment]
Great suggestion!

**Comment by pioneerskies** [comment]
@Bandi017 @nailbrain that feature was introduced in https://github.com/welaika/wordmove/releases/tag/v3.0.2

Search `forbid` in https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained

Is that what you - almost - intended?

Turing the feature in an interactive flow will bring problems in automated flows, so I'm a fun of a configuration based one and I actually use it to disable db push to customers' staging. If I **really** need to do a push I manually comment out the forbid directive.

Also in a team scenario it's useful to enforce caution across all the team just using a shared `movefile.yml`.

**Comment by Bandi017** [comment]
@pioneerskies thanks for the answer...i did come across this functionality already. It is a good option to completely skip a forbidden element, and having to redo the process for that specific element...please forgive me for being a bit lazy...another solution would also be: to not introduce a ftp/ssh password for the user -- thus making wordmove ask for the password each time a new element needs to be pulled/pushed :)

**Comment by Bandi017** [comment]
from my point of view yes :) thanks !
