### ISSUE TITLE
Feature Request: List all remotes

### ISSUE THREAD

**Issue by TylerBarnes** [welaika/wordmove#496]
First of all, thanks again for this incredible tool! This has made my job so much easier.

I'm using wordmove on a lot of projects with a few developers. Depending on the project we may have 1 to 3 remotes. When switching between projects I usually need to hunt down the movefile (could be in the themes or root dirs depending on how long ago I started the project) and then I need to open it and check the remote names to use wordmove. Depending on the dev they may name the remote different things. We've tried to keep it consistent but some of our old projects use different conventions. To keep things very explicit in some projects we name the remote the same thing as the vhost url
`wordmove push --all -e sitename.com`. In others we write `live`, `dev`, etc.
A command like `wordmove list` would be super helpful. I figure it could print out a list with each remote and the vhost associated with the remote name.

For example:
```bash
wordmove list
▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Listing Remotes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
dev: https://devsite.com
staging: https://staging.com
sitename.org: https://sitename.org
```

Is this a feature you guys might be interested in adding? I would make a PR but unfortunately my bash skills are pretty bad.

**Comment by pioneerskies** [comment]
Hey there,

glad to hear this tool is helping there!

Honestly this sound like a really nice and tiny feature. I'd like to take it in consideration. I also hope to have a new develop session before the winter.

As a side note: Wordmove is written in Ruby, not in bash - fortunately! :trollface:

**Comment by TylerBarnes** [comment]
Awesome to hear you'll consider it! 
I guess it's been so long since I installed wordmove that I've forgotten it's installed as a gem!
Since my Ruby skills are nonexistant I'm definitely not able to help then, ha.

Thanks again for wordmove and for considering this!

**Comment by akiko-pusu** [comment]
Hi, I've just created a pull request for this feature. #548 
I hope this will be of some help.
Regards,

**Comment by pioneerskies** [comment]
Puts your hand up: we've merged. And really soon we're going to release 🕺 💃

**Comment by TylerBarnes** [comment]
Awesome!!

**Comment by pioneerskies** [comment]
Forgot to close this one, since the release was done ;)
