### ISSUE TITLE
Connecting to Windows' MySQL database through WSL

### ISSUE THREAD

**Issue by Leisors** [welaika/wordmove#499]
Hey everybody!
So, I've been able to successfully install WordMove on Win10 by following your guide, but now I'm a bit stuck. I'm using Laragon on Windows as web server and I'm trying to somehow connect WordMove to it. Ubuntu's shell IS able to execute Windows' binaries such as Laragon's MySQL and MySQLDump but:
1. Can't seem to add a /mnt/c/ subfolder to $PATH (No such file or directory)
2. MySQL and MySQLDump files should be called with the .exe extension
3. I haven't been able to access the interactive MySQL's shell through WSL, even though looks like commands are executing.

Has anybody managed to do something like this? Do you think it's doable?
Thanks!

**Comment by Leisors** [comment]
Alright, I've managed to make it work. I keep thinking about WSL as a separate entity, but you can connect to your Windows web server without any problem. _Everything_ needs to be installed on the Linux shell, though.
To recap, a couple of steps that might be useful to add on the guide (or at least a note explaining to avoid strange cross-system solutions):
1. Install full LAMP stack on the WSL
2. Install wp-cli
3. Change your wp-config file and define the DB_HOST as 127.0.01 instead of "localhost"
4. Install every package needed for your hooks to work (node, gulp, ...)
5. Profit

Wordmove is great tho, totally worth it.

**Comment by planetcappe** [comment]
Hi @tomm-m, maybe it's a dumb question, but I can't figure out how to make it work. I have the Wordpress installations on the Windows side. When you say that you need to have all the tools installed on the Linux shell, you still can have the WP site installed in Windows? Thanks!
