### ISSUE TITLE
Escaped double quotes in deployer/base.rb

### ISSUE THREAD

**Issue by mike2410** [welaika/wordmove#507]
So I tried deploying the database with "wordmove push -d" resulting in the following error message:

`mysqldump: Can't create/write to file '"/var/www/web2077/html/dump.sql"' (Errcode: 2 - No such file or directory)`

So it looks like my remote-end seems to interpret the escaped double quotes added in deployer/base.rb line 134 literally, aka as part of the path? When I removed them, the mysqldump on the remote end passed.

Manually executing the generated mysqldump-command works without an issue on the remote end. So I'm guessing there has to be some sort of encoding problem between my vagrant box that executes the ruby script to the remote end ...

Any thoughts/ideas would be greatly appreciated, I really love what you did with wordmove and am hoping desperately to get it to work!

**Comment by pioneerskies** [comment]
I have to say that I'm looking for the first time at this line of code...

In the official doc https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_result-file the synopsis does not use quotes around `file_name`. That said: wordmove is somewhat widely used and it's the first time I see this issue reported. So I'm pretty confused :P 

I should find the time to investigate, but unfortunately it won't happen before the third weekend in February.

As a reference we have a test explicitly testing the production of the mysqldump's command: https://github.com/welaika/wordmove/blob/master/spec/deployer/base_spec.rb#L66

**Comment by pioneerskies** [comment]
Assuming it is a bug so that it will get scheduled

**Comment by pioneerskies** [comment]
Sorry to close this one w/o results, but i was never able to reproduce this in any way :(
Moreover 6.0.0 will no more wrap `mysqldump` directly.
