### ISSUE TITLE
pulling of database where production path is single slash character

### ISSUE THREAD

**Issue by Shriken** [welaika/wordmove#511]
So inside movefile I use single / for the wordpress_path of the production env. it seems like every instance of '/' in db is replaced with my local wordpress path. so for instance, where it should be 'text/html' it's now 'textmypathhtml'
Obviously it ruins the whole db when I pull it.
Any insights? 

Edit: well that's probably very noobish of me but using './' solved it.

**Comment by pioneerskies** [comment]
Hey there,

the problem should be another one: the [docs](https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained#per-environment-options-local) say `wordpress_path` must be an absolute path.

Anyway the is not a single scenario where `/` (system root) would be a viable location for a WordPress install.

We could add a specific check to the `doctor`, but honestly it's overall a matter of reading the manual 😛 

Resuming: remove the `./` and write the absolute path e.g.: `/Users/fuzzy/dev/mywpsite/`.

I'll close this one, but feel free to ping me and reopen if further help is needed.

**Comment by Shriken** [comment]
@pioneerskies  my production host is http://company.wpengine.com and the wordpress files are located in the root there, what should be the absolute path then? I'm confused :]

**Comment by pioneerskies** [comment]
I'm looking at their docs @ https://wpengine.com/support/getting-started-ssh-gateway/ and it seems to me that the site should be in `cd sites/myenvironment`. What am I missing?

**Comment by Shriken** [comment]
That is not the case for me. I'm using sftp for the transfer and I can log to to wpengine files and can see it's located right under '/'.

**Comment by pioneerskies** [comment]
OH! `*ftp*` protocols! So your path should be different: what's the value of `wordpress_absolute_path` in your `movefile.yml`?

ref: https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained#per-environment-options-remotes

**Comment by pioneerskies** [comment]
Any news, @Shriken ?
