### ISSUE TITLE
Solution to rsync error: error in rsync protocol data stream

### ISSUE THREAD

**Issue by sumitpore** [welaika/wordmove#516]
Hi There,

I was trying to use wordmove but it was throwing the error:
```
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [Receiver=3.1.2]
```
I have figured out the solution to the problem. When this problem occurs, we have to disable SSH host key checking for that particular remote server. Procedure to disable it can be found [here](https://www.shellhacks.com/disable-ssh-host-key-checking/).

**WARNING: There are security implications in disabling SSH Host key. You can read about it [here](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.foto100/hostch.htm).**

**Comment by sumitpore** [comment]
I am not suggesting this to be included in wordmove. This should be done by individuals on their machine.

**Comment by bboytian** [comment]
Hi, I am having the same problem. Could I ask what machine were you using?
I am running rsync on windows, it works when i run it from git bash terminal, but fails when I use the windows command prompt

**Comment by pioneerskies** [comment]
Thanks for sharing.

I'd add that if you connect manually through SSH and you one-time accept the remote server host key as "recognized" replying "yes" to the prompt, then you should be able to avoid that particular problem.

@bboytian probably your `known_hosts` is not shared between the two environments. Unfortunately I don't know how it works on Windows, but trying at first a direct SSH connection maybe could help.

**Comment by cmbuckley** [comment]
I also experienced this error when the destination host was a Synology NAS and the [rsync service](https://www.synology.com/en-global/knowledgebase/DSM/help/DSM/AdminCenter/file_rsync) was not enabled.
