### ISSUE TITLE
command not found: wordmove

### ISSUE THREAD

**Issue by n8sb** [welaika/wordmove#521]
On Mojave 10.14.4 I have upgraded the version of Ruby on my system to 2.6.2 and installed the wordmove gem however I get

`zsh: command not found: wordmove` 
every time that I attempt to use the command.  

`gem list` 
shows wordmove installed

Ive tried this with both homebrew and rbenv for installing ruby.

Thanks

**Comment by mythnc** [comment]
Please check your GEM PATHS by using `gem environment`,
then add the correct path in your shell rc file

ref 
https://stackoverflow.com/questions/2392293/ruby-gems-returns-command-not-found

**Comment by pioneerskies** [comment]
@n8sb why you upgraded the ruby version? Isn't Wordmove compatible with the default shipped ruby version?

Unfortunately I can't help so much with environment setup problems. Moreover if you're using `rbenv` and it does not work for you, I'd advice to reach the `rbenv` community for help; you can tell about wordmove as "a gem that ships an executable".

I can assure that wordmove's executable *per se* is there and is working :)

Best luck

**Comment by n8sb** [comment]
Unfortunately, Wordmove isn't compatible with the default version of ruby on OSX which put me down this road in the first place :/.

**Comment by pioneerskies** [comment]
Understood.

I swear that (re)following this paragraph https://github.com/rbenv/rbenv#homebrew-on-macos about `rbenv`'s installation will do the work.
Probably you just missed something (like: "Follow the printed instructions to set up rbenv shell integration.") :)
