### ISSUE TITLE
Wordmove on debian 9

### ISSUE THREAD

**Issue by kaktux** [welaika/wordmove#523]
hi there,

first: im not a programmer in anyway - just a normal user who when problems occur search for available solutions and try them out. Coming to those solutions myself would probably never happen - therefore i try to keep things as easy as possible.

So my question would be what the easiest way to get wordmove running on debian 9 is.
I couldn't find a list of wordmove requirements (ruby version etc) - but as the current version seems to need ruby 2.4 the main "problem" is that debian 9 offers ruby 2.3 as package.
I know that there are other installation methods like rvm - but these are far more complex to get to work then simply install the ruby-full package.

In some other discussion i found the solution simply to install an older wordmove version:
gem install wordmove -v 2.0.0

So another question would be what the most current wordmove version is that would run with the debian 9 package (https://packages.debian.org/de/stretch/ruby-full).

Or- as i never tried to install ruby before this-  if there is another quite simple method to get wordmove running.

**Comment by pioneerskies** [comment]
Hello,

I totally disagree on the "use an old version" approach. Take a look at when Ruby 2.3 was released: https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/

The common solutions to install Ruby language on Linux - I'd say more officially advised than through the OS repos - are `rbenv` and `RVM`. Another take could be to install LinuxBrew and hence `brew install ruby`.

Trying to use software from 2015 will lead more problems and complication than following any of the aforementioned solutions.

Cheers and good luck :)
