### ISSUE TITLE
Text File Busy when attempting to Gzip local dump.sql file

### ISSUE THREAD

**Issue by HeylonNHP** [welaika/wordmove#524]
I get this error every time I attempt to run a `wordmove push --all -e production`, or `wordmove push -d -e production` from a local Varying Vagrant Vagrants VM that I have installed wordmove inside of.

Terminal output including the error (Database passwords are replaced with XXXXXX):
```▬▬ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | mysqldump --host=localhost --port=3306 --user=bn_wordpress --password=XXXXXX --result-file="/opt/bitnami/apps/wordpress/htdocs/wp-content/dump.sql" bitnami_wordpress
   remote | gzip -9 -f "/opt/bitnami/apps/wordpress/htdocs/wp-content/dump.sql"
   remote | get: /opt/bitnami/apps/wordpress/htdocs/wp-content/dump.sql.gz /srv/www/wordpress/public_html/wp-content/production-backup-1556776338.sql.gz
   remote | delete: /opt/bitnami/apps/wordpress/htdocs/wp-content/dump.sql.gz
    local | mysqldump --host=localhost --user=wp --password=XXXXXX --result-file="/srv/www/wordpress/public_html/wp-content/dump.sql" wordpress
    local | Adapt dump
    local | gzip -9 -f "/srv/www/wordpress/public_html/wp-content/dump.sql"
gzip: /srv/www/wordpress/public_html/wp-content/dump.sql: Text file busy
Traceback (most recent call last):
        14: from /usr/local/bin/wordmove:23:in `<main>'
        13: from /usr/local/bin/wordmove:23:in `load'
        12: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/exe/wordmove:6:in `<top (required)>'
        11: from /var/lib/gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        10: from /var/lib/gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
         9: from /var/lib/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
         8: from /var/lib/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
         7: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:102:in `push'
         6: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `handle_options'
         5: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `each'
         4: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:42:in `block in handle_options'
         3: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:103:in `block in push'
         2: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:38:in `push_db'
         1: from /var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh/default_sql_adapter.rb:14:in `adapt_local_db!'
/var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/deployer/base.rb:93:in `run': Return code reports an error (Wordmove::ShellCommandError)
```

The **[Varying Vagrant Vagrants](https://github.com/Varying-Vagrant-Vagrants/VVV)** VM consists of a **Ubuntu 14.04.6 LTS** instance with [various tools including a web-server](https://github.com/Varying-Vagrant-Vagrants/VVV#software-included) specifically intended to host WordPress installations locally. I've modified the configuration slightly to include lftp and ruby 2.6 (both of which were not pre-installed, but required for wordmove).

I'm attempting to push to an Amazon **[Bitnami](https://aws.amazon.com/marketplace/pp/B00NN8Y43U?qid=1556869794321&sr=0-1&ref_=srh_res_product_title)** box through SSH. There's a working WordPress installation already setup over there which I want to overwrite using wordmove. Just to eliminate Amazon being a potential fault, I also tried pushing to another WordPress installation hosted on **[SiteGround](https://www.siteground.com)**, exactly the same issue occurred so it's likely something occurring locally that's tripping things up.

Running `wordmove doctor` doesn't seem to reveal anything wrong with my configuration:
```
▬▬ Using Movefile: ./Movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Validating movefile section: global ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | Formal validation passed

▬▬ Validating movefile section: local ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | Formal validation passed

▬▬ Validating movefile section: staging ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | Formal validation passed

▬▬ Using Movefile: ./Movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Checking local database commands and connection ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/var/lib/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/doctor/mysql.rb:29: warning: Insecure world writable dir /vagrant/config/homebin/ in PATH, mode 040777
    ✅  success | `mysql` command is in $PATH
    ✅  success | `mysqldump` command is in $PATH
    ✅  success | Successfully connected to the MySQL server
    ✅  success | Successfully connected to the database

▬▬ Checking local wp-cli installation ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | wp-cli is correctly installed
    ✅  success | wp-cli is up to date

▬▬ Checking rsync ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | rsync is installed at version 3.1.0

▬▬ Checking SSH client ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | SSH command found

```

If I run `gzip -9 -f "/srv/www/wordpress/public_html/wp-content/dump.sql"` manually after wordmove crashes I get no errors.

I'm currently using wordmove 4.0.1, but I've also tried using wordmove version 4.0.0, 3.2.3 and 3.1.2 and get exactly the same issue. I've also tried using ruby version 2.4 with no luck.

**Quick update/edit (9th May):**
This problem seems to be intermittent, sometimes wordmove will work without issue, other times I'll get the dreaded **text file busy**. I have narrowed this down to the **Virtual Box File Share** used to share the WordPress installation directory between my host machine (Running Windows 10) and the Vagrant box (Running CLI Ubuntu). The **Virtual Box File Share** appears to be locking any new files in the WordPress installation directory while they're being synced between my Windows host, and the Vagrant (Ubuntu) guest. This problem could be resolved by not using the **wp-content** directory as a working directory to dump the database, instead give the user the ability to specify a custom directory outside the WordPress installation directory.

Let me know if any more details are necessary.

Cheers

**Comment by pioneerskies** [comment]
Since no one replied, and given I can't debug nor troubleshoot virtualbox-related problems, I'd advice to open an issue as a feature request, better elaborating your expectations around

> This problem could be resolved by not using the wp-content directory as a working directory to dump the database

and focusing only on the feature, not on the original problem. That will be labeled as feature and stable bot will never bother.
