### ISSUE TITLE
TLD duplicated in theme mods DB entry after pull

### ISSUE THREAD

**Issue by sbehnfeldt** [welaika/wordmove#525]
When I create a production site, such as **example.com**, I create a local instance at **example.com.local** (which I define in my HOSTS file and vhosts.conf).  After I pull from production, the URL is "translated" as **example.com.local.local** in the theme mods DB entry in wp_options.  I tried with **example.com.home** and got the same results.  Interestingly, the value for the string length is correct - that is, it represents the length of the correct domain, rather than the length of the domain that is actually written to the DB.

**Comment by pioneerskies** [comment]
If it's not too late: I'd need to take a look at you movefile in order to get an idea. And also the output of `wordmove doctor` command.

**Comment by pioneerskies** [comment]
Abandoned
