### ISSUE TITLE
Failed to create shell on gzip with wpengine SSH

### ISSUE THREAD

**Issue by kLOsk** [welaika/wordmove#526]
Guys, I'm trying to run wordmove on a WPEngine staging site. Haven't tried it since they added SSH on their basic plans, however I get an error as shown below. Anyone know if this can be fixed? gzip is installed on the instance, so i'm not sure why it fails. Anyone successfully uses wordmove on WPE these days?

`remote_run': Error code 1 returned by command "gzip -9 -f "/home/wpe-user/sites/mo (Wordmove::ShellCommandError)l"": Failed to create shell`

**Comment by pioneerskies** [comment]
Hi @kLOsk ,

it seems to me that you have not `gzip` command on the remote host. Is it possible? Have you tried to connect by console and run `gzip` from there?

**Comment by kLOsk** [comment]
I thought so too, but I can execute it without problems when logging in via SSH. You have a WPEngine account available for testing?

**Comment by pioneerskies** [comment]
Nope, I'm sorry 🤷‍♂

**Comment by kLOsk** [comment]
<pre>wpe-user@mombizstaging.ssh.wpengine.net:~$ gzip
gzip: compressed data not written to a terminal. Use -f to force compression.
For help, type: gzip -h
wpe-user@mombizstaging.ssh.wpengine.net:~$ 
</pre>

Looks normal? Is it possible to disable sql compression?

**Comment by pioneerskies** [comment]
Would be great to know if it is related to #528
