### ISSUE TITLE
Managing movefile between two (or more) local dev setups

### ISSUE THREAD

**Issue by bongoman** [welaika/wordmove#529]
I maintain a local dev version across two, maybe three different computers.

I'm using a Bedrock based setup, with composer for plugin management and keep it all version controlled using git.

At this stage, my movefile is version controlled. How best to manage the different local environment setups in my movefile?

Should I just take it out of version control perhaps?

**Comment by pioneerskies** [comment]
I think you should go with `.env` files. Take a look at https://github.com/welaika/wordmove#environment-variables

`.env` won't be committed in git.

Feel free to reopen if the answer does not fit your needs :)
