### ISSUE TITLE
ERROR:  Error installing wordmove:

### ISSUE THREAD

**Issue by eirichmond** [welaika/wordmove#534]
I've already had wordmove installed and running and for some reason now if I `wordmove init` I get this error:

```
Traceback (most recent call last):
	2: from /usr/local/bin/wordmove:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem wordmove (>= 0.a) with executable wordmove (Gem::GemNotFoundException)
```
so I tried to reinstall wordmove and now I get this:

```
ERROR:  Error installing wordmove:
	There are no versions of photocopier (~> 1.3, >= 1.3.2) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	photocopier requires Ruby version >= 2.4.0. The current ruby version is 2.3.0.0.
```

**Comment by pioneerskies** [comment]
Hi,

your problem seems clear from this part of the error message:

    requires Ruby version >= 2.4.0. The current ruby version is 2.3.0.0.

While we support 2.4+, I'd advice to go with the latest ruby: in a near future we'll have higher version constrain. Note that 2.3.0 is coming with a Delorian from the 2015 ;)

___

Long story short: update your ruby and enjoy :)

**Comment by pioneerskies** [comment]
P.S.: feel free to reopen if you need further help

**Comment by eirichmond** [comment]
Resolved, thanks
