### ISSUE TITLE
Additional Settings

### ISSUE THREAD

**Issue by Soullighter** [welaika/wordmove#537]
Is it possible to add aditional set?
Like `set sftp:auto-confirm yes;`

**Comment by pioneerskies** [comment]
Hello,

if I'm not wrong you're speaking about LTFP options. Anyway I'd advice to be more explicatory about your context when opening a new issue 😉 

To mange LFTP's flags you should use a `~/.lftprc` (or one of its variants) file. You can find more in depth info in the LFTP's man ([here](https://lftp.yar.ru/lftp-man.html)) in the introductory paragraph.

When invoked by Wordmove, LFTP will honour the loading of its config files :)

Feel free to reopen the issue if you think my answer was not sufficient or if you need further help.

Best

**Comment by Soullighter** [comment]
Thanks to your answer @pioneerskies 
Yes, you helped me a lot, last weeks i was playing with LFTP for Pipeline on GitLab so I'm familiar with some staff from them. I am so happy to see that you guys using it also :)
I never played with Variables in LFTP, but hey, i need to start in some point, and that will be now :-D  
Thank you again!
Cheers
