### ISSUE TITLE
ssh agent forwarding in Vagrant not working

### ISSUE THREAD

**Issue by allysonsouza** [welaika/wordmove#540]
Hi, I'm using ssh-agent forwarding in my [VCCW ](http://vccw.cc/)Vagrant setup, I can connect to my server with my Windows hosted keys, but when I try to run Wordmove it keeps asking me form my password. For now I generated a key from my box, but would be awesome to have agent forwarding working, any ideas why it's not working? (already removed the password from `movefile.yml`)

**Comment by allysonsouza** [comment]
I figured it's working for file pushing, just not for database:

![image](https://user-images.githubusercontent.com/2000638/64131024-58ce0600-cd9c-11e9-8ac2-0cfa58e56568.png)

**Comment by pioneerskies** [comment]
Hello @allysonsouza ,

the real answer here is that wordmove does not aim to directly manage SSH configurations.

My general advice is to simply have in wordmove something like

```yml
ssh:
  host: my_staging_server
```

and delegate all of its configuration to your `~/.ssh/config`.

The fact you're receiving password prompt only when pushing the DB is actually awkward and I have no clue why it should happen... 🤔

**Comment by pioneerskies** [comment]
Seen the reaction, I'm going to close this one, but feel free to reopen if you need :)
