### ISSUE TITLE
Unescaped double quotation marks breaking remote mysql commit database command

### ISSUE THREAD

**Issue by tomathyg** [welaika/wordmove#544]
I've been using Wordmove for some time without issue but have just run into a problem with a host I haven't used before (WPEngine).

The database push is failing on the final command:

remote   mysql --host=127.0.0.1 ... --execute="SET autocommit=0;SOURCE...dump.sql;COMMIT"

However, if I copy and paste the whole command and escape the double quotation marks, it works fine. It also works without escaping them if I log in over SSH and run the command locally.

Is this just a simple fix? Or is there perhaps a mysql option that will sort this?

Regards

Tom

**Comment by pioneerskies** [comment]
Please, refer to https://github.com/welaika/wordmove/issues/528 in order to understand if your problem is related. Other users are using version 4.0.2.pre4 to succesfully work on WPEngine
