### ISSUE TITLE
Is it possible to have gzip run with the `nice` command?

### ISSUE THREAD

**Issue by justinmaurerdotdev** [welaika/wordmove#546]
Hi @pioneerskies, hope you're well. We're still using Wordmove daily and really appreciate its utility.

For some reason, on our server, whenever Wordmove runs `gzip`, it uses massive CPU (and probably memory) resources and actually interferes with NGINX's ability to keep up with our site traffic. A colleague told me about the `nice` command, which is designed to limit the CPU resources of a given command's processes. In fact, [the examples for how to use ](http://www.softpanorama.org/Utilities/nice.shtml)`nice` often include specific references to `gzip`. I haven't used it much, but it seems like it would be appropriate for this use case.

Would it be possible to build this command into Wordmove? It seems like it would be pretty straightforward, and have almost no drawbacks. The default setting could be the maximum resource usage (19 in the -20 to +19 scale that `nice` uses), but users could set a priority as a config option. OR the default could be 0 (medium priority).

I'm not a ruby developer, so I'm not going to submit a pull request, but I think it would look something like this (from the [base.rb file](https://github.com/welaika/wordmove/blob/master/lib/wordmove/deployer/base.rb)):
```
def compress_command(path)
    command = ["nice"]
    command << "-n"
    command << "\"#{nice_priority}\""
    command << "gzip"
    command << "-9"
    command << "-f"
    command << "\"#{path}\""
    command.join(" ")
end
```

I'd be happy to help test or talk through such a feature. Cheers.

**Comment by pioneerskies** [comment]
Hi @360Zen :)

I'm trying to slowly come back on this project after a long stop.

Your idea is really nice and simple from the implementation POV, but it adds a peer dependancies to the whole thing. So first question: is the `nice` command available by default in all linux distribution (Alpine included)?

Second question: although your scenario is a real and understandable one, the problem feels more like a sysadmin's one than a developer's one 👅 I mean: you have for sure one (or more) dedicated user for the deploys, so why do not set the `nice`ty directly on users? Just like a `backup` system user would have?

Let's share!

**Comment by pioneerskies** [comment]
Reactions?

**Comment by 360Zen** [comment]
Sorry for the delay here. I think you are probably right (especially considering the additional dependency requirements) that the best solution here is a system level fix, perhaps like the one here: http://eosrei.net/articles/2013/03/forcing-mysqldump-always-be-nice-cpu-and-io. 

However, I know that a lot of WP devs (like me) aren't exactly expert sysadmins, so if there are things that can be done to prevent Wordmove from using ALL of the IO bandwidth or ALL of the processor power on a server, I would think those would be worth pursuing. 

Feel free to close this ticket though, as I think your assessment is correct. And cheers for making a great product! Wordmove has been invaluable for our purposes.

**Comment by pioneerskies** [comment]
Closing this saying that in the 6.0.0.alpha version `nice` will always be used to compress files both remotely and locally (probably bringing windows incompatibility, but that's the decision at the moment).

**Comment by pioneerskies** [comment]
Hey: never useless and never too late. I'm glad you're still interested to the matter.

And I see your point :) There are so much different scenarios in our works, we can't even imagine!

Best
