### ISSUE TITLE
wordmove requires Ruby version >= 2.6.0.

### ISSUE THREAD

**Issue by huraji** [welaika/wordmove#560]
Hey there,

when I run `sudo gem update wordmove` I get

`wordmove requires Ruby version >= 2.6.0.`

but on `gem env version` I get:

`2.6.14.4`

What's wrong? I'm on Windows Subsystem for Linux

**Comment by pioneerskies** [comment]
I'm a ruby dev, but I have no idea what `gem env version` is ^^"

Please try with a simpler `ruby --version` to see what version of ruby you're running on. 🙏

**Comment by huraji** [comment]
> I'm a ruby dev, but I have no idea what `gem env version` is ^^"

LOL I'm not a ruby developer but `gem env` should give you the specs of rubygems environment, if I remember correctly. But you're right I picked the wrong parameter:

```
RubyGems Environment:                                                                                                                                         │
  - RUBYGEMS VERSION: 2.6.14.4                                                                                                                                │
  - RUBY VERSION: 2.4.9 (2019-10-02 patchlevel 362) [x86_64-linux-gnu]
  [...]
```

Thanks and I apologize for this. Updating it.
We can close this.

**Comment by Bandi017** [comment]
i'm having the same issue: i'm getting an error stating that wordmove needs ruby >=2.6.0 if i check my ruby version i have 2.6.3 installed... any help would be appreciated :)

**Comment by pioneerskies** [comment]
@Bandi017 would you mind to open a new issue and to report the output of your `ruby --version` there? TIA

**Comment by Bandi017** [comment]
@pioneerskies. Problem was solved...the ruby version was 2.6.3; when trying to install wordmove it rendered the error: wordmove needs ruby >=2.6.0.
my solution was to install ruby 2.6.0 via rbenv and set it to global... after that installing wordmove was not problem...so i consider the issue closed for the moment.
