### ISSUE TITLE
500 error at the end of a db pull/push

### ISSUE THREAD

**Issue by fotan** [welaika/wordmove#562]
I recently found Wordmove and immediately fell in lust.  I'm not in love yet, but I'm close.  :)

I'm getting the following 500 error at the end of a pull or push of the database:

`/Users/username/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:378:in `open_http': 500 Internal Server Error (OpenURI::HTTPError)`

The updates don't happen on the target. Anyone have any experience with this?  

TIA

**Comment by pioneerskies** [comment]
Hello and welcome!

Are you on FTP protocol?

**Comment by fotan** [comment]
Yes.  Using SFTP.

**Comment by pioneerskies** [comment]
I'm so sorry, but we only know that your server is having a generic internal error, as reported by wordmove when it tries to connect to the server. This is too few even to start a troubleshoot.

You should have a longer trace from wordmove and you should have a trace about the 500 error on your server error logs. Both of them would be someway interesting to read.

**Comment by pioneerskies** [comment]
News about the trace/logs?
