### ISSUE TITLE
No support for Sockets in DB connection

### ISSUE THREAD

**Issue by psoluch** [welaika/wordmove#564]
I'm using Local by Flywheel for my local development and in order to connect with the database, I need to use a socket file (e.g. /Users/myuser/Library/Application Support/Local/run/VCuvaNDJh/mysqld.sock).

It seems that v5 of wordmove doesn't support sockets. Any chance to add it in?

**Comment by pioneerskies** [comment]
Hello @psoluch ,

in the docs (https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained) you can find all the info about passing additional options to the underling `mysql` and `mysqldump` commands (search for `mysql_options` and `mysqldump_options`); at a glance I think your scenario could be covered by this feature.

Please let me know if I misunderstood anything.

**Comment by pioneerskies** [comment]
Reactions?
