### ISSUE TITLE
Environment Variables are not read in Doctor diagnostics

### ISSUE THREAD

**Issue by psoluch** [welaika/wordmove#566]
If Environment Variables are used for any of the Database fields, they are not read properly by the Doctor and the check might fail.

To reproduce change any of the Database fields for Local environment (e.g. username, password) with Environment Variable. Execute "wordmove doctor". The MySQL test will fail.

It might be similar for other Doctor checks.

**Comment by pioneerskies** [comment]
Hi @psoluch ,

this one duplicates #535; thanks for bumping up the problem. In the older issue it is already accepted as a bug and I'll take it in consideration in a future release :)

Please subscribe to the older issue to continue to contribute to the bug. I'm going to close this one.
