### ISSUE TITLE
Doctor ignores `mysql_options`

### ISSUE THREAD

**Issue by pioneerskies** [welaika/wordmove#572]
Since in the those options we could have important ones about the connection (e.g.: `--socket`), we should use those options while testing the connections.

**Comment by EltonWhybrow** [comment]
The --socket does not work for me:

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Validating movefile section: global ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ✅  success | Formal validation passed

▬▬ Validating movefile section: local ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ✅  success | Formal validation passed

▬▬ Validating movefile section: production ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ✅  success | Formal validation passed

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Checking local database commands and connection ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ✅  success | `mysql` command is in $PATH

    ✅  success | `mysqldump` command is in $PATH

    ❌  error |   We can't connect to the MySQL server using credentials
                specified in the Movefile. Double check them or try
                to debug your system configuration.

                The command used to test was:

                mysql --host=127.0.0.1 --port=10005 --user=root --password=root -e'QUIT'


    ❌  error |   We can't connect to the database using credentials
                specified in the Movefile, or the database does not
                exists. Double check them or try to debug your
                system configuration.

                The command used to test was:

                mysql --host=127.0.0.1 --port=10005 --user=root --password=root local -e'QUIT'


▬▬ Checking local wp-cli installation ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ✅  success | wp-cli is correctly installed

    ✅  success | wp-cli is up to date

▬▬ Checking rsync ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ✅  success | rsync is installed at version 2.6.9

▬▬ Checking SSH client ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬


Any help would be much appreciated.
Here is my movefile.yml

global:
  sql_adapter: "wpcli"

local:
  vhost: http://ingenie.local/
  wordpress_path: /Users/elton/LocalRepos/wordpress/ingenie/app/public # use an absolute path here

  database:
    name: "local"
    user: "root"
    password: "root" # could be blank, so always use quotes around
    host: '127.0.0.1'
    port: '10005'
    mysqldump_options: '--socket "/Users/elton/Library/Application\ Support/Local/run/ZKJm76QFZ/mysql/mysqld.sock"'

production:
  vhost: http://s34647.p257.sites.pressdns.com/
  wordpress_path: /data/s257124/dom34647/dom34647 # use an absolute path here
  ssh:
    host: 52.21.62.182
    user: client_sshelton
    #rsync_options: '--verbose'

  database:
    name: db_dom34647
    user: db_dom34647
    password: password!
    host: host!
    # port: 3308 # Use just in case you have exotic server config
    # mysqldump_options: '--max_allowed_packet=1G' # Only available if using SSH
    # mysql_options: '--protocol=TCP' # mysql command is used to import db

**Comment by pioneerskies** [comment]
@EltonWhybrow thanks for confirming the misbehaviour :) I'll work on this for the next release

**Comment by pioneerskies** [comment]
Let me clarify an aspect: ATM `doctor` is completely ignoring "extra" flags. BTW when we'll fix this bug, it will read options from `mysql_options`, not from `mysqldump_options` since for testing db connection we're using `mysql` command.

Probably a `--socket` option will need to be configured on both `mysql_options` and `mysqldump_options` since both tools need to connect to the server through the socket. We differentiated the configurations because the two commands have some config in common but some others are specific.

As a poor man orientation: `mysql` is used when importing DB, `mysqldump` is used when exporting DB.

In the future we will completely rely on `wp-cli` for these operations so we'll remove a bunch of complexities.

**Comment by pioneerskies** [comment]
Current alpha version dropped entirly the `local.database` section and related `doctor`'s checks. Going to close even if the alpha is ... still an alpha :)
