### ISSUE TITLE
Anyone able to help me get wordmove working with WP Engine?

### ISSUE THREAD

**Issue by thetwopct** [welaika/wordmove#574]
The latest version 5 solves issues I had with other hosts and the database 👍, however the database will still not sync with any sites I administrate on WP Engine. Can anyone share with me how their config looks likes or what steps you take to get it working?

- Wordmove doctor all good
- I'm using MAMP, ZSH
- I've had my IP whitelisted at WP Engine

which mysqldump
/Applications/MAMP/Library/bin/mysqldump

whence -p mysql
/Applications/MAMP/Library/bin/mysql

**Comment by pioneerskies** [comment]
Isn't https://github.com/welaika/wordmove/issues/528 your same issue?

**Comment by thetwopct** [comment]
> Isn't #528 your same issue?

Well the people in the thread are saying they can now connect. I am asking about sharing their config/setup, as WP Engine have told me they require use of a SSH Tunnel, and whatever I try here is not working with movefile. So I am asking here for help from some of the people who say "Yes this works with WP Engine now" - so no, its not same issue.

**Comment by pioneerskies** [comment]
@thetwopct I got you point. Thank you very much.

I'd advice to report what error are you getting in order to give a better context to other users.

I'm planing to open an account on WPEngine to do some tests myself, but I've not a schedule so my timing is all but affordable ATM.
