### ISSUE TITLE
Error at Pushing Database Step. 

### ISSUE THREAD

**Issue by daddydanielt** [welaika/wordmove#575]
Failed to push Database to the production environment.
Anyone able to help me figure out how to handle this issue, thank you.

command: **wordmove push --all -e production --debug --verbose** 
Error: **This does not seem to be a WordPress installation.**

<img width="1253" alt="Screen Shot 2020-01-11 at 15 54 11" src="https://user-images.githubusercontent.com/6659615/72201045-ff34c100-348a-11ea-8cfa-43f8cb895fcf.png">

**Comment by pioneerskies** [comment]
This is `wp-cli` complaining that in the `--path` it cannot find a WP installation. It has something to do with the `wordpress_path` you configured inside `movefile.yml`

**Comment by paulmist** [comment]
Was there a clear fix/problem identified for this? I've got the same issue.

Used Wordmove many times before with no issue.

**Comment by paulmist** [comment]
Took a punt and won.

The path I had defined had spaces - which WP CLI didn't like.

**Comment by pioneerskies** [comment]
Eheh, nobody like them 😉
