### ISSUE TITLE
Wordmove Pull replaces the db with wrong site url and home wp_options 

### ISSUE THREAD

**Issue by OMFG5716** [welaika/wordmove#576]
**Describe the bug**

**Wordmove command**
Command used on the CLI: (e.g.: `wordmove pull --all --no-db`)

**Expected behavior**

**movefile.yml**
Paste (removing personal data) the interesting part, if any, of your `movefile.yml` formatting it inside a code block with `yml` syntax and double checking the indentation.

**Exception/trace**
Paste (removing personal data) the entire trace of error/exception you encountered, if any

**Environment (please complete the following information):**
- OS:
- Ruby: (`ruby --version`)
- Wordmove: (`wordmove --version`)

**Doctor**
* [x] `wordmove doctor` is all green

(If it is not, report the error you got.)

**Comment by pioneerskies** [comment]
Sorry to be a bit rude maybe, but I cannot spend time if you do not spend some on your side neither to fill the info required in the template.

You're welcome to open another issue with complete information.

**Comment by OMFG5716** [comment]
Hey Alessandro, 
My apologies. I actually got around this issue that i was facing and I inadvertently must have hit submit while adding all the information (I was writing all the info somewhere else before pasting it in).

**Comment by pioneerskies** [comment]
Oh I got it! :)

Thank you for the explanation, sorry again for have been so strict and moreover and above all I'm happy you solved your problem 🎉
