### ISSUE TITLE
rsync filename with accented character

### ISSUE THREAD

**Issue by nicobilliotte** [welaika/wordmove#579]
** the bug**
if a filename has a é, à, è character, rsync wont sync it

**Wordmove command**
any wordmove file sync command

**Expected behavior**
Sync all files whatever their encoding (dont know if rsync is using -s, --protect-args
This option sends all filenames and most options to the remote
rsync without allowing the remote shell to interpret them. This
means that spaces are not split in names, and any non-wildcard
special characters are not translated (such as ~, $, ;, &,
etc.). Wildcards are expanded on the remote host by rsync
(instead of the shell doing it).)

**Comment by pioneerskies** [comment]
Hello,

I'm sorry but I've lost a lot of updates from January. I'm trying to remedy.

Sincerly I'd say that the bug are filenames with special characters. 😛 

Fortunately, by the way, Wordmove lets you set whatever `rsync` option you'd like, as documented [here](https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained#ssh). So you'd need `-s` or `-iconv`, you're free to use them :)

Unless the error is from Wordmove program itself complaining about unreadable encoding...but you omitted the eventual exception/trace/error, so I really can't say it for sure

**Comment by pioneerskies** [comment]
Closing for insufficient informations and stale.
