### ISSUE TITLE
Save output of changes in file?

### ISSUE THREAD

**Issue by taliesinpenbardd** [welaika/wordmove#580]
Hello,

Could it be possible to have an option to save the output of verbose push/pull to a file?

I deal sometimes with hacked websites, and while there is an output in the terminal while the files are transferring - helping me to know what files have been changed - my terminal history is sometimes too short to be able to check all those files. 
Could it be possible to have an option to save that output in a text file, so I could go and check which files were changed, so I can replace them easily, without missing something?

Thanks for your attention :)

**Comment by pioneerskies** [comment]
Hey @taliesinpenbardd ,

I have no idea why, but I lost this one in the Great Sea of Issues. I'm really sorry.

Let me ask a question - I swear I'm not trolling you: being Wordmove a command line utility, why aren't you using a simple redirection to save STDOUT to a file? E.g.:

```
wordmove pull -t -e staging > wordmove.log
```

I think this a feature already in the command line. Were you thinking about some other types of logging facility?

**Comment by taliesinpenbardd** [comment]
Well, I simply didn't think about that, but I'm not that good in bash. That performs the operation and saves the output at the same time? Well, that's perfect, then, thanks for pointing it out. 🙂

**Comment by pioneerskies** [comment]
Yeah, it'll do the work. Raw, but functional.

Keep in mind: `>` will overwrite your logfile, while `>>` will append new output at the and of it.

You could also control the size of your history in bash: https://stackoverflow.com/questions/9457233/unlimited-bash-history just to drop a casual link.

There are also more complex command to redirect back the STDOUT to the terminal, but it is a harder way :)
