### ISSUE TITLE
Should wordmove have local en_US.UTF-8 and run ssh-agent?

### ISSUE THREAD

**Issue by gormv** [welaika/wordmove#589]
Hi,

First of all, thanks for a really nice tool! 

I found a couple of issues with welaika/docker and therefore had to create a separate Dockerfile. I just wanted to let you know how I fixed it and if there is something I'm missing.

The two problems I encountered were related to https://github.com/welaika/wordmove/issues/530 and the second was https://github.com/welaika/wordmove/issues/586

With this Dockerfile both of those issues seems solved so not sure if this should be in the main Dockerfile?

```Dockerfile
FROM welaika/wordmove
RUN apt-get update \
        && apt-get install -y locales \
        && rm -r /var/lib/apt/lists/* \
        && sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen \
        && locale-gen \
        && echo "export LC_ALL=en_US.UTF-8" >> ~/.bashrc \
        && echo "export LANG=en_US.UTF-8" >> ~/.bashrc \
        && echo "export LANGUAGE=en_US.UTF-8" >> ~/.bashrc \
        && echo "eval \`ssh-agent -s\`" >> ~/.bashrc
```

**Comment by pioneerskies** [comment]
Hello,

I'd like to think about it and eventually to ask a couple questions, but you should reach me on the [image repo](https://github.com/welaika/docker-wordmove), pls, since the image code is there and Wordmove's issue tracker is already way too much cluttered :)

I hope it will be ok for you. Thanks in advance

**Comment by pioneerskies** [comment]
Since it is staled, I've opened the issue on the right repo to keep track of the suggestion/qustion

**Comment by pioneerskies** [comment]
Said that 6.0.alpha.1 has dropped the `default` `sql_adapter` in favour of `wpcli`, thus circumventing the problem, locales are now preconfigured into `welaika/wordmove:latest` docker image.
