### ISSUE TITLE
Allow Wordmove to push one plugin only

### ISSUE THREAD

**Issue by taliesinpenbardd** [welaika/wordmove#594]
**Is your feature request related to a problem? Please describe.**
I sometimes do updates on one plugin and would like to be able to send that only plugin (or theme, for that matters) and not overwrite others.

**Describe the solution you'd like**
`wordmove push -e environment -p "plugin-name"`
`wordmove push -e environment -t "theme-name"`

Possible ?
Thanks by advance.

**Comment by pioneerskies** [comment]
Hello @taliesinpenbardd ,

this should allow you achieve the same result without additional features https://github.com/welaika/wordmove/wiki/Work-only-on-specific-plugins-or-themes

Let me know if that fits you needs

**Comment by taliesinpenbardd** [comment]
I reckon that'd work, but it's a bit less flexible than just passing it through CLI.

That'd be wonderfull if you could consider adding this to a next update, but I'll make do for now.

Thanks for the tip! :)
