### ISSUE TITLE
Better error message when the env doesn't exist

### ISSUE THREAD

**Issue by Korkey128k** [welaika/wordmove#596]
When you try to perform an action on a env that doesn't exist, the error is unfriendly;
```
wordmove-5.0.2/lib/wordmove/deployer/base.rb:16:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Describe the solution you'd like**
Perhaps an error message that lets you know you used an env you don't have configured, and suggest you add it or select from the ones you have.

**Comment by Korkey128k** [comment]
Created pull request: https://github.com/welaika/wordmove/pull/595

**Comment by pioneerskies** [comment]
Following you on the PR. Nice feature and idea ;)
