### ISSUE TITLE
Own folders within wp-content are ignored

### ISSUE THREAD

**Issue by electricarts** [welaika/wordmove#600]
What is the reason that own folders within wp-content are not synchronized? In my local installation I have a folder "assets" within wp-content, which contains e.g. my own style.css and font files. The complete folder is ignored. 
If I move the folder into the root directory of the WordPress installation, it will be transferred and synchronized without errors. 

Mario

**Comment by pioneerskies** [comment]
Hi,

that's not a bug but the intended software's behaviour. Wordmove can sync

* core
* plugins
* mu-plugins
* languages
* plugins
* themes

These are all managed as single entities.

The common practice used by plugins/themes developers is usually to make a subfolder inside `uploads` with an empty `index.php` inside and all the other assets.

That said Wordmove does not support arbitrary folders.
