### ISSUE TITLE
Is this a typo ??

### ISSUE THREAD

**Issue by eldk** [welaika/wordmove#627]
https://github.com/welaika/wordmove/blob/7b954c7237a46f7bdbc27f76788d4042142cbbf3/lib/wordmove/deployer/ssh.rb#L116

**Comment by pioneerskies** [comment]
It is. But it does not bring to a bug because both method's definition and call have the same typo ;)

Moreover it's fixed in pre-release version. Thanks to have spotted that out, btw.
