### ISSUE TITLE
Problem with permalinks

### ISSUE THREAD

**Issue by AndreaBarghigiani** [welaika/wordmove#66]
Hi weilaka team,

congrats for your amazing work! I've been usign your gem in the last few days and I've been impressed with its easy of use. 

Unfortunatly there is a little problem that I can't understand properly, but I'm sure its my fault ;) Every time I pull or push my work the platform that has been updated it will loose the permalink settings and I have to enter in the admin panel and save again the permalink structure (just to flush the rewriting rules).

There is something wrong with my Movefile? Should I add the .htaccess file in the exclude section?

Thanks in advance for your help!

**Comment by kevinwhoffman** [comment]
I just ran into this problem and wanted to confirm that excluding .htaccess in my Movefile resolved the issue of having to manually refresh permalinks.
