### ISSUE TITLE
Expected Key Error

### ISSUE THREAD

**Issue by coreyallen** [welaika/wordmove#75]
First of all..this is amazing, thanks for woking on this.

I created a move file and tried both SSH and FTP, both times I had the following error

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 12 column 3 (Psych::SyntaxError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.1.0/lib/wordmove/deployer/base.rb:56:in `fetch_movefile'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.1.0/lib/wordmove/deployer/base.rb:18:in `deployer_for'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.1.0/lib/wordmove/cli.rb:56:in `push'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.1.0/bin/wordmove:6:in `<top (required)>'
    from /usr/bin/wordmove:23:in `load'
    from /usr/bin/wordmove:23:in `<main>'
```

**Comment by taliesinpenbardd** [comment]
Hey @harapeko, care to share how you did solve your problem ? :)

**Comment by joelcomit** [comment]
I'm having this exact same problem. Running it through validator and getting same error. Don't know how to fix it. This is where the error is being triggered:

`(<unknown>): did not find expected key while parsing a block mapping at line 12 column 3`

**Comment by harapeko** [comment]
hi @taliesinpenbardd , i fixed syntax error. :)

**Comment by rotexhawk** [comment]
For future visitors use this following url to validate your yaml file. It also pinpoints the error. I think this should be added to the docs to avoid situations like this. 

https://codebeautify.org/yaml-validator

**Comment by pioneerskies** [comment]
@rotexhawk I really appreciate your will to give other users suggestions about troubleshooting, but I'd really like if all Wordmove users will start to use the `doctor` command, which has an integrated and tailored `movefile.yml` parser/checker.

`doctor` was introduced in version 2.3.0 and is documented [here](https://github.com/welaika/wordmove/wiki/Usage-and-flags-explained).

It could need some improvements and therefore is important to point users to use it and eventually to open issues if does not work as expected.

I hope it could be useful also for you :)

Cheers
