### ISSUE TITLE
Problem local database when pull

### ISSUE THREAD

**Issue by dondia-lab** [welaika/wordmove#78]
Hi, I get the error:
`/.rvm/gems/ruby-2.0.0-p451@global/gems/wordmove-1.1.0/lib/wordmove/sql_adapter.rb:44:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)`

**Comment by lindsaymarkward** [comment]
Hi. I had this same problem, also solved by editing sql_adapter.rb manually. It's a year since this issue was closed. Is the problem still there?
I have wordmove 1.3.1 
Running inside VVV
Thanks!

**Comment by pioneerskies** [comment]
This is a no-problem/won't fix.
Please refer to this wiki entry https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db for further informations

**Comment by lindsaymarkward** [comment]
Aha, thanks.It's useful to have this link here for future when finding this issue.

**Comment by pioneerskies** [comment]
Sure! Thanks for asking about!
