### ISSUE TITLE
Error on wordmove pull, and push

### ISSUE THREAD

**Issue by ljuboja** [welaika/wordmove#88]
✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/home/ljuboja/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:370:in `parse': (<unknown>): did not find expected '-' indicator while parsing a block collection at line 23 column 5 (Psych::SyntaxError)
	from /home/ljuboja/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
	from /home/ljuboja/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:318:in `parse'
	from /home/ljuboja/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:245:in `load'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:58:in `fetch_movefile'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:20:in `deployer_for'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/wordmove-1.2.0/lib/wordmove/cli.rb:45:in `pull'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/bin/wordmove:23:in `load'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/bin/wordmove:23:in `<main>'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/ljuboja/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by modernmediagrp** [comment]
I'm having the same issue, when I check my yaml file with the lint service you provided, it seems to strip out allot as well as re arranges the structure, also i get this error with the suggested file from said service

/Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:25:in `deployer_for': You need to specify an environment with --environment parameter (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

Prior using the 'init' to start fresh id get this error
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): found character that cannot start any token while scanning for the next token at line 4 column 1 (Psych::SyntaxError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:58:in `fetch_movefile'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:20:in `deployer_for'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'


is the extension .yml important? Also I'm running this on a separate volume /Volumes/www/vagrant-local
Tried sudo as well. 
I can run 'wordmove' help and i get a list of commands 
Also in OS X 10.10:
---
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
gem -v 2.0.14
---
Thanks  for your work and help

**Comment by delphaber** [comment]
Could you please try with http://codebeautify.org/yaml-validator ? Is it valid?

**Comment by modernmediagrp** [comment]
Yes that validates nice.
When I run 'wordmove push' I still get this error:

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:25:in `deployer_for': You need to specify an environment with --environment parameter (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

Is there an additional flag I am missing?

**Comment by pioneerskies** [comment]
Probably `wordmove push -e younameit`; and I think this happens because you have multiple remote environments. Obviously "younameit" is the name you choose inside your `Movefile`.

In reply of another question: yes, the `.yml` is important :)

Let us know some good news ;)

**Comment by modernmediagrp** [comment]
Success! 
I 'wordmove help push' expanded the list commands and I was a blue to get up and running. Also, I found another post were a user was using VVV vagrant and had a pre-provision script. I was able to get the gem's working on the Virtual Box and OS X 10.10. Thank for your help on this. If I had the link handy to the other post i would add it. Think it might help in the future.

Also, FYI. it might be handy to expand a little more on the error message, as I obviously didn't que in right away. Nonetheless this script has shaved another few steps off the process of developing with Wordpress. Today I will be deploying a them the a stage server, wish me luck.  

Oh! -t does the do the whole directory or is there a flag for 1 theme?

**Comment by pioneerskies** [comment]
Let try to guess something :)

* in order to exlcude themes from pull/push actions the only way you have is to list their path in the @exlcude@ section of the @Movefile@ like

```yaml
staging_environment
  exlcude
    - /wp-content/themes/do_not_push_this
```
remember you can use no more than one configuration (Movefile) file

* @-e staging_environment@ tells wordmove where to push/pull: Wordmove is a multistaging tool, so you can write as many sections as you need inside @Movefile@ just doubling and renaming the @staging@ default section
* @-c@ flag specifies an alternative configuration file instead of the @Movefile@
* @-no-adapt@ is not rly useful: it tells Wordmove to not apply database string substitution; almost useful just for testing
* @--all@ tells Wordmove to pull/push every supported components: plugins, themes, database, core, etc...
* @--no-no-adapt@ and @--no-all@, imho, are just weird commands auto-generated by a library due to a very little bug in our code. Please, just actually ignore theme ;)

Cheers

**Comment by delphaber** [comment]
Can we consider this closed? :)
