### ISSUE TITLE
Compression for SQL transfer?

### ISSUE THREAD

**Issue by Swingline0** [welaika/wordmove#93]
Considering the sweet compression ratio a compressed SQL file gets, it would be cool to leverage this for database migrations. There might be implications I'm overlooking but it seems like it should be feasible for both SSH and FTP transfers... right?

**Comment by ivandoric** [comment]
Hey guys, any updates on this one? Just found about this gem today and I can already see it's going to make my workflow much easier. First push I did was a 30MB db. Took a long time to upload as you can imagine :) so I think adding this feature will make this gem almost perfect. 

Also I think going with gzip initially would be great.

Gonna spread the word about this gem on my blogs.

**Comment by pioneerskies** [comment]
We have plans to work on Wordmove though a few Fridays so it's possible that this feature will be planned for the next weeks and we hope before April will ends

**Comment by ivandoric** [comment]
Thanks @pioneerskies . And once again, really great gem.

**Comment by pioneerskies** [comment]
@Swingline0 @ivandoric @joeguilmette @everybodyaroundtheworld

The feature is shipped in the current pre-release, please `gem install wordmove --pre`, test and report bug if you find one!

Cheers

**Comment by Swingline0** [comment]
Awesome!!!! You're the man!
